import {installPrivacySchema} from './helpers/privacy-schema.mjs';
import {installConsentFixtures} from './helpers/consent-fixtures.mjs';
import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
installPrivacySchema(sql);
installConsentFixtures(sql);
class Prepared{constructor(query,args=[]){this.query=query;this.args=args;}bind(...args){return new Prepared(this.query,args)}async first(){return sql.prepare(this.query).get(...this.args)||null}async all(){return {results:sql.prepare(this.query).all(...this.args)}}async run(){const r=sql.prepare(this.query).run(...this.args);return {meta:{changes:Number(r.changes)}}}}
const DB={prepare:q=>new Prepared(q),async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const stmt of stmts)r.push(await stmt.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__schooldayTest={env:{DB,APP_SECRET:'only-a-test-key',TEACHER_EMAILS:'owner@example.test,teacher@example.test'},headers:new Headers(),cookies:{}};
await build({entryPoints:['app/api/[action]/route.ts'],bundle:true,platform:'node',format:'esm',outfile:'/tmp/schoolday-billing-test.mjs',alias:{'cloudflare:workers':path.join(process.cwd(),'tests/helpers/runtime.mjs'),'next/headers':path.join(process.cwd(),'tests/helpers/headers.mjs')}});
const {GET,POST}=await import('file:///tmp/schoolday-billing-test.mjs');
async function call(action,body){const r=await(body===undefined?GET:POST)(new Request('https://schoolday.test/api/'+action,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:'https://schoolday.test'},body:body===undefined?undefined:JSON.stringify(body)}),{params:Promise.resolve({action:action.split('?')[0]})});return {status:r.status,data:await r.json()};}
function who(id,email){globalThis.__schooldayTest.headers=new Headers(id?{'oai-authenticated-user-id':id,'oai-authenticated-user-email':email}:{});}
const sessions=new Map(),subs=new Map(),requests=[];let seq=0;
globalThis.fetch=async(url,opts={})=>{const u=new URL(url);assert.equal(u.origin,'https://api.stripe.com');const route=u.pathname.slice(4);const body=new URLSearchParams(opts.body||'');requests.push({route,body:Object.fromEntries(body)});if(route==='account')return Response.json({id:'acct_fixture'});if(route.startsWith('prices/'))return Response.json({id:route.slice(7),product:'prod_fixture',active:true,type:'recurring',billing_scheme:'per_unit',currency:'usd',unit_amount:2900,livemode:false,recurring:{interval:'month',interval_count:1,usage_type:'licensed'}});if(route==='billing_portal/configurations')return Response.json({id:'bpc_fixture'});if(route==='webhook_endpoints')return Response.json({id:'we_fixture',secret:'whsec_fixturesecretvalue'});if(route==='checkout/sessions'){const id='cs_test_'+(++seq);sessions.set(id,{id,status:'open',payment_status:'unpaid',url:'https://checkout.stripe.com/c/pay/'+id,client_reference_id:body.get('client_reference_id'),metadata:{schoolday_account:body.get('metadata[schoolday_account]')},customer:body.get('customer')||'cus_'+seq,price:body.get('line_items[0][price]'),quantity:Number(body.get('line_items[0][quantity]'))});return Response.json(sessions.get(id));}if(route.endsWith('/expire')){const s=sessions.get(route.split('/').at(-2));s.status='expired';return Response.json(s);}if(route.startsWith('checkout/sessions/'))return Response.json(sessions.get(route.split('/').at(-1)));if(route.startsWith('subscriptions/'))return Response.json(subs.get(route.split('/').at(-1)));if(route==='billing_portal/sessions')return Response.json({url:'https://billing.stripe.com/p/session_test'});throw new Error('Unexpected Stripe path: '+route);};
function complete(id){const s=sessions.get(id);s.status='complete';s.payment_status='paid';s.subscription='sub_'+id;subs.set(s.subscription,{id:s.subscription,status:'active',customer:s.customer,metadata:s.metadata,livemode:false,cancel_at_period_end:false,items:{data:[{price:{id:s.price},quantity:s.quantity,current_period_end:Math.floor(Date.now()/1000)+86400}]}});return s.subscription;}
const config={mode:'test',familyPrice:'price_family',organizationPrice:'price_school',privacyUrl:'https://example.test/privacy',termsUrl:'https://example.test/terms',supportEmail:'support@example.test'};
let alice,second,sessionId,subscriptionId;
test('adult access and payment lifecycle',async t=>{
 await t.test('anonymous users cannot access an adult roster or create billing',async()=>{who(null);assert.equal((await call('roster')).status,401);assert.equal((await call('account-setup',{name:'Family',kind:'family',adult:true})).status,401);assert.equal((await call('billing-connect',{})).status,403);});
 await t.test('adult account links created learners and recovery is scoped to the owner',async()=>{who('adult_a','family@example.test');assert.equal((await call('account-setup',{name:'Family A',kind:'family',adult:true})).status,200);alice=(await call('profile',{name:'Learner A',grade:6})).data.profile;const originalCookie={...globalThis.__schooldayTest.cookies};assert.equal((await call('roster')).data.learners[0].id,alice.id);who('adult_b','other@example.test');await call('account-setup',{name:'Family B',kind:'family',adult:true});assert.equal((await call('select-learner',{id:alice.id})).status,404);assert.equal((await call('learner-work?id='+alice.id)).status,404);assert.equal((await call('link-learner',{})).status,409);assert.equal((await call('roster')).data.learners.length,0);who('adult_a','family@example.test');globalThis.__schooldayTest.cookies={};assert.equal((await call('status')).data.profile,null);assert.equal((await call('select-learner',{id:alice.id})).status,200);assert.equal((await call('status')).data.profile.id,alice.id);assert.notDeepEqual(globalThis.__schooldayTest.cookies,originalCookie);assert.equal((await call('account-setup',{name:'Family A',kind:'organization',adult:true})).status,400);});
 await t.test('only the app owner configures encrypted, verified payment prices',async()=>{who('teacher','teacher@example.test');assert.equal((await call('billing-connect',{key:'sk_test_fixture_long_enough',config})).status,403);who('owner','owner@example.test');assert.equal((await call('billing-connect',{key:'sk_live_fixture_long_enough',config})).status,400);assert.equal((await call('billing-connect',{key:'sk_test_fixture_long_enough',config:{...config,privacyUrl:'http://example.test'}})).status,400);assert.equal((await call('billing-connect',{key:'sk_test_fixture_long_enough',config})).status,200);assert.notEqual(sql.prepare("SELECT value FROM settings WHERE id='stripe_key'").get().value,'sk_test_fixture_long_enough');const catalog=(await call('account')).data.catalog;assert.equal(catalog.prices.family.amount,2900);assert(!JSON.stringify(catalog).includes('sk_test'));});
 await t.test('checkout uses account-selected prices, reuses pending sessions, and rejects unpaid returns',async()=>{who('adult_a','family@example.test');assert.equal((await call('plan',{})).status,402);const r=await call('checkout',{quantity:1,price:'price_untrusted',entry:'family',grade:8,source:'family_guide'});assert.equal(r.status,200,JSON.stringify(r));sessionId=r.data.url.split('/').at(-1);assert.equal(sessions.get(sessionId).price,'price_family');const again=await call('checkout',{quantity:1});assert.equal(again.data.url,r.data.url);assert.equal(requests.filter(r=>r.route==='checkout/sessions').length,1);assert.equal((await call('checkout',{quantity:0})).status,400);assert.equal((await call('billing-refresh',{sessionId})).status,409);assert.equal((await call('account')).data.entitlement.active,false);});
 await t.test('verified payment grants only its account and its purchased learner quantity',async()=>{subscriptionId=complete(sessionId);who('adult_b','other@example.test');assert.equal((await call('billing-refresh',{sessionId})).status,404);who('adult_a','family@example.test');assert.equal((await call('billing-refresh',{sessionId})).data.active,true);assert.equal((await call('billing-refresh',{sessionId})).data.quantity,1);assert.equal((await call('checkout',{quantity:1})).status,409);assert.equal((await call('billing-portal',{})).status,200);second=(await call('profile',{name:'Learner B',grade:8})).data.profile;assert.equal((await call('plan',{})).status,402);await call('select-learner',{id:alice.id});assert.equal((await call('plan',{})).status,503);const body=requests.find(r=>r.route==='checkout/sessions').body;assert.equal(body.customer_email,'family@example.test');assert.match(body.integration_identifier,/^schoolday-family-[a-z]{8}$/);assert.equal(body.payment_method_types,undefined);assert.equal(body.success_url,'https://schoolday.test/?flow=family&grade=8&utm_source=family_guide&session_id={CHECKOUT_SESSION_ID}');assert.equal(body.cancel_url,'https://schoolday.test/?flow=family&grade=8&utm_source=family_guide&checkout=cancelled');assert(!JSON.stringify(requests).includes('Learner A'));assert(!JSON.stringify(requests).includes('Learner B'));});
 await t.test('renewal and cancellation are rechecked with Stripe, while saved records remain accessible',async()=>{const sub=subs.get(subscriptionId);sub.items.data[0].quantity=2;assert.equal((await call('billing-refresh',{})).data.quantity,2);await call('select-learner',{id:second.id});assert.equal((await call('plan',{})).status,503);sub.status='canceled';assert.equal((await call('billing-refresh',{})).data.active,false);assert.equal((await call('plan',{})).status,402);assert.equal((await call('portfolio')).status,200);assert.equal((await call('roster')).data.learners.length,2);});
 await t.test('changed checkout quantities expire the old unpaid session and canceled plans can resubscribe',async()=>{const first=await call('checkout',{quantity:2});assert.equal(first.status,200,JSON.stringify(first));const firstId=first.data.url.split('/').at(-1);assert.equal(sessions.get(firstId).customer,subs.get(subscriptionId).customer);const changed=await call('checkout',{quantity:3});assert.equal(changed.status,200,JSON.stringify(changed));assert.equal(sessions.get(firstId).status,'expired');assert.notEqual(changed.data.url,first.data.url);});
 await t.test('billing identity cannot be reassigned through account fields or replayed sessions',async()=>{who('adult_b','other@example.test');const overview=(await call('account')).data;assert.equal(overview.entitlement.active,false);assert.equal((await call('billing-portal',{})).status,400);assert.equal((await call('school')).status,403);who('adult_a','family@example.test');assert.equal((await call('billing-refresh',{sessionId:'cs_test_invented'})).status,404);});
});
