import {installPrivacySchema} from './helpers/privacy-schema.mjs';
import {installConsentFixtures} from './helpers/consent-fixtures.mjs';
import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
sql.prepare("INSERT INTO settings(id,value) VALUES('pilot_emails',?)").run(JSON.stringify(['parent@example.test']));
installPrivacySchema(sql);
installConsentFixtures(sql);
class Prepared{constructor(q,args=[]){this.q=q;this.args=args}bind(...args){return new Prepared(this.q,args)}async first(){return sql.prepare(this.q).get(...this.args)||null}async all(){return {results:sql.prepare(this.q).all(...this.args)}}async run(){return {meta:{changes:Number(sql.prepare(this.q).run(...this.args).changes)}}}}
const DB={prepare:q=>new Prepared(q),async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__schooldayTest={env:{DB,APP_SECRET:'continuity-test',TEACHER_EMAILS:'teacher@example.test,other@example.test'},headers:new Headers(),cookies:{}};
await build({entryPoints:['app/api/[action]/route.ts'],bundle:true,platform:'node',format:'esm',outfile:'/tmp/schoolday-continuity-test.mjs',alias:{'cloudflare:workers':path.join(process.cwd(),'tests/helpers/runtime.mjs'),'next/headers':path.join(process.cwd(),'tests/helpers/headers.mjs')}});
const {GET,POST}=await import('file:///tmp/schoolday-continuity-test.mjs');
async function call(action,body){const r=await(body===undefined?GET:POST)(new Request('https://schoolday.test/api/'+action,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:'https://schoolday.test'},body:body===undefined?undefined:JSON.stringify(body)}),{params:Promise.resolve({action:action.split('?')[0]})});return {status:r.status,data:await r.json()};}
function who(id,email){globalThis.__schooldayTest.headers=new Headers(id?{'oai-authenticated-user-id':id,'oai-authenticated-user-email':email}:{});}
const option={text:'One half',feedback:'Private answer feedback'};
const lesson={title:'Fraction model',grade:6,subject:'Math',objective:'Explain equivalent fractions',prerequisite:'Equal wholes',materials:[],sources:[],stages:['notice','teach','model','practice','apply','reflect'].map(kind=>({kind,title:kind,content:'Use equal wholes and compare portions.',prompt:'Explain your thinking.',minutes:5,options:kind==='practice'?[option]:[],answer:kind==='practice'?0:-1,hint:'',rubric:[],example:'',visual:{kind:'none',values:[],labels:[],caption:''}})),checks:[0,1].map(()=>({question:'Compare two fractions.',options:[option,{text:'Two thirds',feedback:'Private wrong feedback'}],answer:0}))};
let learner,cookie,aid,did,requestId;
test('learning continuity and human support',async t=>{
 await t.test('preferences are persistent, learner-scoped, and reject arbitrary profile fields',async()=>{who('parent','parent@example.test');assert.equal((await call('account-setup',{name:'Test family',kind:'family',adult:true})).status,200);learner=(await call('profile',{name:'Learner private name',grade:6})).data.profile;cookie={...globalThis.__schooldayTest.cookies};const p={textSize:'large',focus:true,reducedMotion:true,speechRate:'slow',instruction:'chunked'};assert.equal((await call('preferences',p)).status,200);assert.deepEqual((await call('preferences')).data.preferences,p);assert.equal((await call('preferences',{...p,profileId:'other'})).status,400);who('other-parent','other-parent@example.test');await call('account-setup',{name:'Other fixture family',kind:'family',adult:true});await call('profile',{name:'Other learner',grade:8});who(null);assert.equal((await call('preferences')).data.preferences.textSize,'standard');globalThis.__schooldayTest.cookies=cookie;});
 await t.test('history and progress preserve immutable checks and never expose answer keys',async()=>{did=crypto.randomUUID();aid=crypto.randomUUID();sql.prepare("INSERT INTO days(id,profile_id,day_number,theme,question,status,created_at) VALUES(?,?,1,'Equal portions','What stays equal?','complete',?)").run(did,learner.id,new Date().toISOString());sql.prepare("INSERT INTO activities(id,day_id,subject,title,goal,prerequisite,minutes,position,status,phase,payload) VALUES(?,?,'Math','Fraction model','Explain equivalent fractions','Equal wholes',40,1,'complete','ready',?)").run(aid,did,JSON.stringify(lesson));for(let stage=0;stage<8;stage++)sql.prepare('INSERT INTO evidence(id,profile_id,activity_id,stage,response,choice,correct,self_check,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),learner.id,aid,stage,'Saved explanation.',stage>=6?stage-6:null,stage===3||stage===6?1:stage===7?0:null,'[]',new Date().toISOString());const before=sql.prepare('SELECT * FROM evidence').all();const growth=(await call('progress')).data;assert.equal(growth.totals.responses,8);assert.equal(growth.subjects.find(s=>s.subject==='Math').checks,2);assert.equal(growth.subjects.find(s=>s.subject==='Math').completed,1);assert.equal(growth.revisit[0].revisit,1);assert.equal((await call('history-day?id='+did)).data.activities.length,1);const saved=(await call('resume?id='+aid)).data;assert.equal(JSON.parse(saved.activity.payload).checks[0].answer,-1);assert(!saved.activity.payload.includes('Private answer feedback'));assert.deepEqual(sql.prepare('SELECT * FROM evidence').all(),before);});
 await t.test('adult history and help inbox are scoped to linked learners and assigned teachers',async()=>{who('stranger','stranger@example.test');await call('account-setup',{name:'Other family',kind:'family',adult:true});assert.equal((await call('learner-progress?id='+learner.id)).status,404);assert.equal((await call('learner-history-day?profile='+learner.id+'&id='+did)).status,404);assert.equal((await call('learner-activity?profile='+learner.id+'&id='+aid)).status,404);who('parent','parent@example.test');assert.equal((await call('learner-progress?id='+learner.id)).status,200);assert.equal((await call('learner-activity?profile='+learner.id+'&id='+aid)).status,200);who(null);requestId=(await call('help-request',{id:aid,stage:2,question:'Why do the wholes need to match?'})).data.id;assert(requestId);assert.equal((await call('help-request',{id:aid,stage:2,question:'Please help again.'})).status,409);who('stranger','stranger@example.test');assert.equal((await call('help-inbox')).data.requests.length,0);assert.equal((await call('help-answer',{id:requestId,response:'Unauthorized response'})).status,404);who('teacher','teacher@example.test');assert.equal((await call('help-inbox')).data.requests.length,0);sql.prepare("INSERT INTO school_records(id,kind,profile_id,record_key,data,actor,created_at) VALUES(?,'enrollment',?,?,?,?,?)").run(crypto.randomUUID(),learner.id,learner.id,JSON.stringify({teacherEmail:'teacher@example.test'}),'teacher@example.test',new Date().toISOString());assert.equal((await call('help-inbox')).data.requests.length,1);who('other','other@example.test');assert.equal((await call('help-inbox')).data.requests.length,0);});
 await t.test('human replies are private, single-write, and acknowledged only by the learner',async()=>{who('parent','parent@example.test');assert.equal((await call('help-answer',{id:requestId,response:'Draw two equal rectangles first. Compare their shaded portions.'})).status,200);assert.equal((await call('help-answer',{id:requestId,response:'Overwrite the first reply.'})).status,409);who(null);const own=(await call('help')).data;assert.equal(own.requests[0].status,'answered');assert(!JSON.stringify(own).includes('parent@example.test'));globalThis.__schooldayTest.cookies={};assert.equal((await call('help')).status,401);who('other-parent','other-parent@example.test');const other=(await call('profile',{name:'Legacy unlinked learner',grade:7})).data.profile;sql.prepare('DELETE FROM account_learners WHERE profile_id=?').run(other.id);who(null);assert.equal((await call('help')).status,403);assert.equal((await call('help-resolve',{id:requestId})).status,403);assert.equal((await call('history-day?id='+did)).status,403);globalThis.__schooldayTest.cookies=cookie;assert.equal((await call('help-resolve',{id:requestId})).status,200);assert.equal((await call('help')).data.requests[0].status,'resolved');assert.equal((await call('help-request',{id:aid,stage:2,question:'How do I compare the equal wholes now?'})).status,200);});
 await t.test('future generation receives structured supports without identity or help text',async()=>{globalThis.__schooldayTest.env.OPENAI_API_KEY='test-only';let input,instructions;globalThis.fetch=async(url,opts)=>{if(url.startsWith('https://www2.cde.ca.gov/'))return new Response('<h4>6.NS.1</h4><div style="white-space: pre-wrap; ">Interpret and compute quotients of fractions, and solve contextual problems with fractions.</div>');assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(opts.body);input=JSON.parse(body.input);instructions=body.instructions;return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Use fraction models and equal-sized units to explain division.',annotations:[{type:'url_citation',url:'https://www.thecorestandards.org/Math/Content/6/NS/',title:'Fractions'}]}]}]})};assert.equal((await call('plan',{next:true})).status,200);const activities=(await call('day')).data.activities;assert.equal((await call('generate',{id:activities.find(a=>a.subject==='Math').id})).status,200);assert.equal(input.learnerSupport.instruction,'chunked');assert(!JSON.stringify(input).includes('Learner private name'));assert(!JSON.stringify(input).includes('wholes need to match'));assert(instructions.includes('preserving the grade-level objective'));const routine=activities.find(a=>a.subject==='Arrival');assert.equal((await call('answer',{id:routine.id,stage:6,response:'Routine cannot become an independent check.'})).status,400);});
});
