import {installPrivacySchema} from './helpers/privacy-schema.mjs';
import {installConsentFixtures} from './helpers/consent-fixtures.mjs';
import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
installPrivacySchema(sql);
installConsentFixtures(sql);
class Prepared{constructor(q,args=[]){this.q=q;this.args=args}bind(...args){return new Prepared(this.q,args)}async first(){return sql.prepare(this.q).get(...this.args)||null}async all(){return {results:sql.prepare(this.q).all(...this.args)}}async run(){return {meta:{changes:Number(sql.prepare(this.q).run(...this.args).changes)}}}}
const DB={prepare:q=>new Prepared(q),async batch(stmts){sql.exec('BEGIN');try{const result=[];for(const s of stmts)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};
const state=globalThis.__schooldayTest={env:{DB,APP_SECRET:'test-secret',TEACHER_EMAILS:'owner@example.test',STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_WEBHOOK_SECRET:'whsec_testonlysecret'},headers:new Headers(),cookies:{}};
await build({entryPoints:['app/api/[action]/route.ts'],bundle:true,platform:'node',format:'esm',outfile:'/tmp/schoolday-customer-test.mjs',alias:{'cloudflare:workers':path.join(process.cwd(),'tests/helpers/runtime.mjs'),'next/headers':path.join(process.cwd(),'tests/helpers/headers.mjs')}});
const {GET,POST}=await import('file:///tmp/schoolday-customer-test.mjs');
async function call(action,body){const r=await(body===undefined?GET:POST)(new Request('https://schoolday.test/api/'+action,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:'https://schoolday.test'},body:body===undefined?undefined:JSON.stringify(body)}),{params:Promise.resolve({action:action.split('?')[0]})});return {status:r.status,data:await r.json()};}
function who(id,email){state.headers=new Headers(id?{'oai-authenticated-user-id':id,'oai-authenticated-user-email':email}:{});}
async function webhook(event,offset=0,wrong=false){const raw=JSON.stringify(event),t=String(Math.floor(Date.now()/1000)+offset),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(wrong?'wrong':state.env.STRIPE_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(t+'.'+raw))),signature=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');const r=await POST(new Request('https://schoolday.test/api/payment-webhook',{method:'POST',headers:{'stripe-signature':`t=${t},v1=${signature}`},body:raw}),{params:Promise.resolve({action:'payment-webhook'})});return {status:r.status,data:await r.json()};}
let learner,recovery,code;const subs=new Map(),sessions=new Map();let providerCalls=0,down=false;
globalThis.fetch=async url=>{providerCalls++;if(down)throw new Error('Simulated network outage');const u=new URL(url);assert.equal(u.origin,'https://api.stripe.com');if(u.pathname.includes('checkout/sessions/'))return Response.json(sessions.get(u.pathname.split('/').at(-1)));if(u.pathname.includes('subscriptions/'))return Response.json(subs.get(u.pathname.split('/').at(-1)));throw Error('Unexpected provider request');};
test('customer launch controls',async t=>{
 await t.test('adult PIN protects roster, payment configuration, and educator privileges in learner mode',async()=>{who('owner','owner@example.test');const r=await call('account-setup',{name:'Owner family',kind:'family',adult:true,pin:'123456'});assert.equal(r.status,200,JSON.stringify(r));recovery=r.data.recovery;assert.equal(recovery.length,32);const security=sql.prepare('SELECT * FROM adult_security').get();assert.notEqual(security.pin_hash,'123456');assert.notEqual(security.recovery_hash,recovery);learner=(await call('profile',{name:'Sample learner',grade:6})).data.profile;assert.equal((await call('status')).data.educator,true);await call('adult-lock',{});assert.equal((await call('account')).data.locked,true);assert.equal((await call('roster')).status,423);assert.equal((await call('launch')).status,403);assert.equal((await call('educator')).status,403);assert.equal((await call('status')).data.educator,false);assert.equal((await call('status')).data.profile.id,learner.id);assert.equal((await call('adult-unlock',{pin:'123456'})).status,200);assert.equal((await call('roster')).data.learners.length,1);});
 await t.test('PIN guessing is bounded and a recovery code restores access',async()=>{await call('adult-lock',{});for(let n=0;n<5;n++)assert.equal((await call('adult-unlock',{pin:'999999'})).status,403);assert.equal((await call('adult-unlock',{pin:'123456'})).status,429);sql.prepare('UPDATE adult_security SET blocked_until=?').run(Date.now()-1);assert.equal((await call('adult-unlock',{pin:recovery})).status,200);});
 await t.test('device codes are owner-scoped, expire, and redeem only once without adult rights',async()=>{code=(await call('device-code',{id:learner.id})).data.code;who('stranger','stranger@example.test');await call('account-setup',{name:'Other adult',kind:'family',adult:true});assert.equal((await call('device-code',{id:learner.id})).status,404);who(null);state.cookies={};assert.equal((await call('redeem-device',{code})).status,200);assert.equal((await call('status')).data.profile.id,learner.id);assert.equal((await call('status')).data.educator,false);assert.equal((await call('redeem-device',{code})).status,409);who('owner','owner@example.test');await call('adult-unlock',{pin:'123456'});code=(await call('device-code',{id:learner.id})).data.code;sql.prepare('UPDATE device_codes SET expires_at=0').run();assert.equal((await call('redeem-device',{code})).status,409);});
 await t.test('launch checks keep live checkout closed without all connections',async()=>{const d=(await call('launch')).data;assert.equal(d.canOpen,false);assert.equal((await call('launch',{salesOpen:true,globalDailyLimit:500,learnerDailyLimit:60})).status,409);assert.equal((await call('launch',{salesOpen:false,globalDailyLimit:500,learnerDailyLimit:60})).status,200);});
 await t.test('learner allowances stop extra generation and reviewed work cannot be overwritten',async()=>{const did=crypto.randomUUID(),aid=crypto.randomUUID();sql.prepare("INSERT INTO days(id,profile_id,day_number,theme,question,status,created_at) VALUES(?,?,1,'Quota check','What is saved?','ready',?)").run(did,learner.id,new Date().toISOString());sql.prepare("INSERT INTO activities(id,day_id,subject,title,goal,prerequisite,minutes,position,status,phase) VALUES(?,?,'Math','Saved activity','Explain reasoning','Prior ideas',40,1,'queued','research')").run(aid,did);sql.prepare("UPDATE activities SET standard_id='6.NS.1' WHERE id=?").run(aid);sql.prepare('INSERT INTO learner_usage VALUES(?,?,60)').run(learner.id,new Date().toISOString().slice(0,10));const before=providerCalls;assert.equal((await call('generate',{id:aid})).status,429);assert.equal(providerCalls,before);sql.prepare("UPDATE activities SET status='held',phase='held' WHERE id=?").run(aid);sql.prepare('INSERT INTO drafts(id,profile_id,activity_id,stage,response,choice,self_check,version,updated_at) VALUES(?,?,?,0,?,NULL,?,1,?)').run(crypto.randomUUID(),learner.id,aid,'My original explanation.','[]',new Date().toISOString());assert.equal((await call('retry-held',{id:aid})).status,409);assert.equal(sql.prepare('SELECT response FROM drafts WHERE activity_id=?').get(aid).response,'My original explanation.');});
 const config={mode:'test',prices:{family:{id:'price_family'}},familyPrice:'price_family',organizationPrice:'price_school',privacyUrl:'https://example.test/privacy',termsUrl:'https://example.test/terms',supportEmail:'help@example.test',accountId:'acct_test'};
 const event={id:'evt_checkout1',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_one'}}};
 await t.test('signed webhook grants access without a buyer return and rejects forged or stale events',async()=>{sql.prepare("INSERT INTO settings(id,value) VALUES('billing_config',?)").run(JSON.stringify(config));sql.prepare('INSERT INTO checkout_attempts VALUES(?,?,?,?)').run('cs_test_one','owner',1,Date.now());sessions.set('cs_test_one',{id:'cs_test_one',status:'complete',payment_status:'paid',subscription:'sub_one',client_reference_id:'owner',metadata:{schoolday_account:'owner'}});subs.set('sub_one',{id:'sub_one',status:'active',customer:'cus_owner',metadata:{schoolday_account:'owner'},livemode:false,cancel_at_period_end:false,items:{data:[{price:{id:'price_family'},quantity:1,current_period_end:Math.floor(Date.now()/1000)+86400}]}});who(null);state.cookies={};assert.equal((await webhook(event,0,true)).status,400);assert.equal((await webhook(event,-601)).status,400);assert.equal(sql.prepare('SELECT count(*) AS n FROM subscriptions').get().n,0);assert.equal((await webhook(event)).status,200);assert.equal(sql.prepare('SELECT status FROM subscriptions').get().status,'active');const calls=providerCalls;assert.equal((await webhook(event)).data.duplicate,true);assert.equal(providerCalls,calls);});
 await t.test('out-of-order subscription events use current provider state; failures can retry',async()=>{subs.get('sub_one').status='canceled';const update={id:'evt_update1',type:'customer.subscription.updated',livemode:false,data:{object:{id:'sub_one',status:'active'}}};down=true;assert.equal((await webhook(update)).status,500);assert.equal(sql.prepare('SELECT status FROM payment_events WHERE id=?').get(update.id).status,'error');down=false;assert.equal((await webhook(update)).status,200);assert.equal(sql.prepare('SELECT status FROM subscriptions').get().status,'canceled');});
 await t.test('provider outages preserve account access and bounded cached subscriptions',async()=>{who('owner','owner@example.test');await call('adult-unlock',{pin:'123456'});sql.prepare("UPDATE subscriptions SET status='active',checked_at=?").run(Date.now()-600000);down=true;const r=await call('account');assert.equal(r.status,200);assert.equal(r.data.entitlement.stale,true);assert.equal(r.data.entitlement.active,true);sql.prepare('UPDATE subscriptions SET checked_at=?').run(Date.now()-90000000);const old=await call('account');assert.equal(old.status,200);assert(old.data.billingError);assert.equal((await call('roster')).status,200);down=false;});
});
