import {installPrivacySchema} from './helpers/privacy-schema.mjs';
import {installConsentFixtures} from './helpers/consent-fixtures.mjs';
import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
installPrivacySchema(sql);
installConsentFixtures(sql);
class Prepared{constructor(q,args=[]){this.q=q;this.args=args}bind(...args){return new Prepared(this.q,args)}async first(){return sql.prepare(this.q).get(...this.args)||null}async all(){return {results:sql.prepare(this.q).all(...this.args)}}async run(){return {meta:{changes:Number(sql.prepare(this.q).run(...this.args).changes)}}}}
const DB={prepare:q=>new Prepared(q),async batch(stmts){sql.exec('BEGIN');try{const result=[];for(const s of stmts)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};
const state=globalThis.__schooldayTest={env:{DB,APP_SECRET:'test-secret',TEACHER_EMAILS:'owner@example.test',STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_WEBHOOK_SECRET:'whsec_testonlysecret'},headers:new Headers(),cookies:{}};
await build({entryPoints:['app/api/[action]/route.ts'],bundle:true,platform:'node',format:'esm',outfile:'/tmp/schoolday-family-test.mjs',alias:{'cloudflare:workers':path.join(process.cwd(),'tests/helpers/runtime.mjs'),'next/headers':path.join(process.cwd(),'tests/helpers/headers.mjs')}});
const {GET,POST}=await import('file:///tmp/schoolday-family-test.mjs');
async function call(action,body){const r=await(body===undefined?GET:POST)(new Request('https://schoolday.test/api/'+action,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:'https://schoolday.test'},body:body===undefined?undefined:JSON.stringify(body)}),{params:Promise.resolve({action:action.split('?')[0]})});return {status:r.status,data:await r.json()};}
function who(id,email){state.headers=new Headers(id?{'oai-authenticated-user-id':id,'oai-authenticated-user-email':email}:{});}
const schoolYear='2026-2027',date='2026-09-07';let learner,setup,journal;
const notes='I independently checked each example and answer, compared the task with the exact standard, and found the materials and explanations usable.';
async function digest(s){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(v=>v.toString(16).padStart(2,'0')).join('');}
async function signature(){return digest('curriculum-modules-2026-09-09-v2|family-launch-generation-v5|gpt-4.1-mini|test-only');}
function result(value,urls=[]){return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:typeof value==='string'?value:JSON.stringify(value),annotations:urls.map(url=>({type:'url_citation',url,title:'Official source'}))}]}]});}
test('family records and evidence-based launch controls',async t=>{
 await t.test('anonymous or learner-only sessions cannot create profiles or family records',async()=>{who(null);assert.equal((await call('profile',{name:'No adult',grade:6})).status,401);assert.equal((await call('family?profile='+crypto.randomUUID())).status,401);who('parent','parent@example.test');await call('account-setup',{name:'Parent family',kind:'family',adult:true});learner=(await call('profile',{name:'Learner',grade:7})).data.profile;who(null);assert.equal((await call('family?profile='+learner.id)).status,401);});
 await t.test('family setup includes missing subject areas without claiming legal completion',async()=>{who('parent','parent@example.test');const r=await call('family?profile='+learner.id+'&year='+schoolYear);assert.equal(r.status,200,JSON.stringify(r));assert(r.data.subjects.some(s=>s.id==='language'));assert(r.data.subjects.some(s=>s.id==='pe'));assert.equal(r.data.records.length,0);setup={schoolYear,pathway:'private_home',schoolName:'Family school',recordReference:'Private records folder',instructor:'Parent',checks:['pathway'],subjects:r.data.subjects.map(s=>({id:s.id,plan:'Parent-led instruction and a weekly resource plan for '+s.label}))};assert.equal((await call('family-setup',{profile:learner.id,revision:0,setup})).status,200);assert.equal((await call('family-setup',{profile:learner.id,revision:0,setup})).status,409);assert.equal((await call('family-setup',{profile:learner.id,revision:1,setup:{...setup,subjects:setup.subjects.slice(1)}})).status,400);assert.equal((await call('family-setup',{profile:learner.id,revision:1,setup})).data.setupRevision,2);});
 await t.test('daily attendance is adult-confirmed, date-validated, idempotent, and revision-preserving',async()=>{journal={id:crypto.randomUUID(),profile:learner.id,schoolYear,date,revision:0,attendance:'present',instruction:'We reviewed fraction reasoning, read together, practiced Spanish, and completed physical education.',nextStep:'Try a new independent example tomorrow.',adultConfirmed:true};assert.equal((await call('family-journal',{...journal,adultConfirmed:false})).status,400);assert.equal((await call('family-journal',{...journal,date:'2027-02-30'})).status,400);assert.equal((await call('family-journal',{...journal,date:'2025-09-01'})).status,400);assert.equal((await call('family-journal',journal)).status,200);assert.equal((await call('family-journal',journal)).status,200);assert.equal(sql.prepare('SELECT count(*) n FROM family_journal').get().n,1);assert.equal((await call('family-journal',{...journal,id:crypto.randomUUID()})).status,409);assert.equal((await call('family-journal',{...journal,id:crypto.randomUUID(),revision:1,attendance:'half_absent',instruction:'Correction: instruction took place for only half of our scheduled day.'})).status,200);const home=(await call('family?profile='+learner.id+'&year='+schoolYear)).data;assert.equal(home.records.length,1);assert.equal(home.records[0].revision,2);assert.equal(home.records[0].data.attendance,'half_absent');const exported=(await call('family-export?profile='+learner.id+'&year='+schoolYear)).data;assert.equal(exported.revisions.length,2);assert.match(exported.notice,/never inferred/);});
 await t.test('other adults cannot read, update, or export the family records',async()=>{who('stranger','stranger@example.test');await call('account-setup',{name:'Other family',kind:'family',adult:true});for(const action of ['family','family-export'])assert.equal((await call(action+'?profile='+learner.id+'&year='+schoolYear)).status,404);assert.equal((await call('family-journal',{...journal,id:crypto.randomUUID(),revision:2})).status,404);assert.equal((await call('family-setup',{profile:learner.id,revision:2,setup})).status,404);});
 await t.test('public generation requires a paid license or explicit pilot access',async()=>{who('parent','parent@example.test');state.env.OPENAI_API_KEY='test-only';assert.equal((await call('plan',{})).status,402);who('owner','owner@example.test');await call('launch',{salesOpen:false,globalDailyLimit:500,learnerDailyLimit:60,pilotEmails:['parent@example.test']});assert.deepEqual((await call('launch')).data.pilotEmails,['parent@example.test']);});
 await t.test('provider verification tests structured answers and web search and excludes learner information',async()=>{let calls=[];globalThis.fetch=async(url,opts)=>{const b=JSON.parse(opts.body);calls.push(b);return b.tools?result('Official source found.',['https://www.cde.ca.gov/ci/ma/']):result({answer:21});};assert.equal((await call('validate-ai',{})).status,200);assert.equal(calls.length,2);assert(calls[0].text.format.strict);assert.deepEqual(calls[1].tool_choice,{type:'web_search'});assert(!JSON.stringify(calls).includes('Learner'));assert.equal((await call('launch-validation')).data.probeReady,true);assert.equal((await call('launch')).data.canOpen,false);state.env.OPENAI_API_KEY='changed-key';assert.equal((await call('launch-validation')).data.probeReady,false);state.env.OPENAI_API_KEY='test-only';globalThis.fetch=async()=>result({answer:22});assert.equal((await call('validate-ai',{})).status,502);assert.equal((await call('launch-validation')).data.probeReady,false);});
 await t.test('lesson review requires an exact released copy, current configuration, and human findings',async()=>{const did=crypto.randomUUID(),id=crypto.randomUUID(),payload=JSON.stringify({alignment:{standardId:'7.RP.1'}}),snapshot=JSON.stringify({id:'7.RP.1',text:'Official snapshot fixture'}),fingerprint=await digest(payload+'|'+snapshot),reviews=JSON.stringify(['Subject accuracy reviewer','Instruction and accessibility reviewer','Standards alignment reviewer'].map(role=>({role,pass:true,issues:[],summary:'Synthetic test review.'})));sql.prepare("INSERT INTO days(id,profile_id,day_number,theme,question,status,created_at) VALUES(?,?,1,'Fixture day','Fixture?','ready',?)").run(did,learner.id,new Date().toISOString());sql.prepare("INSERT INTO activities(id,day_id,subject,title,goal,prerequisite,minutes,position,status,phase,standard_id,payload,standard_snapshot,content_hash,reviews,generation_signature) VALUES(?,?,'Math','Fixture','Fixture goal','Fixture prerequisite',40,1,'ready','ready','7.RP.1',?,?,?,?,?)").run(id,did,payload,snapshot,fingerprint,reviews,await signature());assert.equal((await call('launch-review',{kind:'lesson',id,contentHash:fingerprint,notes,confirmed:false})).status,400);assert.equal((await call('launch-review',{kind:'lesson',id,contentHash:'a'.repeat(64),notes,confirmed:true})).status,409);assert.equal((await call('launch-review',{kind:'lesson',id,contentHash:fingerprint,notes,confirmed:true})).status,200);assert.equal((await call('launch-validation')).data.matrix.find(c=>c.grade===7&&c.subject==='Math').approved,true);sql.prepare("UPDATE activities SET status='held' WHERE id=?").run(id);assert.equal((await call('launch-validation')).data.matrix.find(c=>c.grade===7&&c.subject==='Math').approved,false);assert.equal((await call('launch-review',{kind:'day',id:did,notes,confirmed:true})).status,409);who('parent','parent@example.test');assert.equal((await call('launch-review',{kind:'lesson',id,contentHash:fingerprint,notes,confirmed:true})).status,403);});
 await t.test('quota pauses never accumulate defective-content failures',async()=>{who('parent','parent@example.test');const id=sql.prepare('SELECT id FROM activities LIMIT 1').get().id;sql.prepare("UPDATE activities SET status='queued',phase='research',standard_id='7.RP.1',payload=NULL,generation_signature=NULL WHERE id=?").run(id);sql.prepare('INSERT INTO learner_usage(profile_id,day,calls) VALUES(?,?,60)').run(learner.id,new Date().toISOString().slice(0,10));for(let n=0;n<5;n++){sql.prepare('UPDATE activities SET next_retry_at=0 WHERE id=?').run(id);assert.equal((await call('generate',{id})).status,429);}const a=sql.prepare('SELECT status,generation_attempts FROM activities WHERE id=?').get(id);assert.equal(a.status,'error');assert.equal(a.generation_attempts,0);});
 await t.test('family price connection works alone and rejects an advertised-price mismatch',async()=>{who('owner','owner@example.test');let amount=3900;globalThis.fetch=async(url)=>{const path=new URL(url).pathname;if(path.endsWith('/account'))return Response.json({id:'acct_fixture'});if(path.includes('/prices/'))return Response.json({id:'price_family',product:'prod_family',currency:'usd',active:true,type:'recurring',billing_scheme:'per_unit',unit_amount:amount,livemode:false,recurring:{usage_type:'licensed',interval:'month',interval_count:1}});if(path.endsWith('/configurations'))return Response.json({id:'bpc_fixture'});if(path.endsWith('/webhook_endpoints'))return Response.json({id:'we_fixture',secret:'whsec_fixture_secret'});throw Error('Unexpected path');};const body={key:'sk_test_fixture_long_secret',config:{mode:'test',familyPrice:'price_family',privacyUrl:'https://example.test/privacy',termsUrl:'https://example.test/terms',supportEmail:'support@example.test'}};assert.equal((await call('billing-connect',body)).status,400);amount=2900;assert.equal((await call('billing-connect',body)).status,200);const c=(await call('account')).data.catalog;assert.equal(c.prices.family.amount,2900);assert.equal(c.prices.organization,undefined);assert.equal((await call('family-offer')).data.available,false);who('parent','parent@example.test');assert.equal((await call('generate',{id:sql.prepare('SELECT id FROM activities LIMIT 1').get().id})).status,429);});
});

test('owner-authorized early access defers advisory evidence without bypassing technical or consent checks',async()=>{
 who('owner','owner@example.test');state.cookies={};state.env.OPENAI_API_KEY='test-only';
 const save=(id,value)=>sql.prepare('INSERT INTO settings(id,value) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').run(id,value);
 save('billing_config',JSON.stringify({mode:'live',prices:{family:{id:'price_family',amount:2900,interval:'month',intervalCount:1}},privacyUrl:'https://example.test/privacy',termsUrl:'https://example.test/terms',supportEmail:'owner@example.test'}));
 save('ai_probe',JSON.stringify({signature:await signature(),checkedAt:new Date().toISOString()}));save('webhook_changed_at','');
 sql.prepare("INSERT INTO payment_events(id,type,livemode,status,created_at) VALUES('evt_early','customer.created',1,'ignored',?)").run(new Date().toISOString());
 sql.exec(fs.readFileSync('drizzle/0019_owner_early_access.sql','utf8'));
 const r=await call('launch');assert.equal(r.status,200);assert.equal(r.data.salesOpen,true);assert.equal(r.data.canOpen,true);
 for(const id of ['lessons','pilots','notices']){const c=r.data.checks.find(c=>c.id===id);assert.equal(c.blocking,false);assert.equal(c.ready,false);assert.equal(c.status,'deferred');}
 assert.equal(sql.prepare("SELECT count(*) n FROM launch_reviews WHERE kind='day'").get().n,0);
 state.env.OPENAI_API_KEY='changed-key';assert.equal((await call('launch')).data.salesOpen,false);state.env.OPENAI_API_KEY='test-only';
 who('parent','parent@example.test');state.cookies={};sql.prepare("UPDATE family_consents SET status='revoked' WHERE account_id='parent'").run();assert.equal((await call('checkout',{quantity:1})).status,403);
 assert.equal((await call('launch',{salesOpen:true,globalDailyLimit:500,learnerDailyLimit:60})).status,403);
});
test('parent verification checkout checks Stripe permissions before creating a paid session',async()=>{
 who('auto-parent','auto-parent@example.test');state.cookies={};
 assert.equal((await call('consent-request',{name:'Test Parent',pin:'654321',guardian:true,notice:true,squads:false})).status,200);
 sql.prepare("DELETE FROM family_consents WHERE account_id='auto-parent'").run();assert.equal((await call('consent-request',{name:'Test Parent',guardian:true,notice:true,squads:false})).status,200);
 const old=globalThis.fetch;let allowed=false,created=0;globalThis.fetch=async(url,options)=>{const u=String(url);if(u.includes('/checkout/sessions')&&options.method==='POST'){created++;const p=new URLSearchParams(options.body);assert.equal(p.get('metadata[schoolday_account]'),'auto-parent');assert(p.get('metadata[schoolday_consent]'));assert.match(p.get('success_url'),/family-privacy\?session_id/);assert.equal(p.get('consent_collection[terms_of_service]'),'required');return Response.json({id:'cs_auto_parent',url:'https://checkout.stripe.com/c/pay/cs_auto_parent'});}assert(/invoice_payments|payment_intents|charges/.test(u));return allowed?Response.json({data:[]}):new Response('{}',{status:403});};
 try{assert.equal((await call('checkout',{quantity:1,verifyParent:true})).status,502);assert.equal(created,0);allowed=true;const r=await call('checkout',{quantity:1,verifyParent:true});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(created,1);assert.equal(sql.prepare("SELECT status FROM family_consents WHERE account_id='auto-parent'").get().status,'pending');assert.equal(sql.prepare("SELECT count(*) n FROM account_learners WHERE account_id='auto-parent'").get().n,0);}finally{globalThis.fetch=old;}
});
