import {installPrivacySchema} from './helpers/privacy-schema.mjs';
import {installConsentFixtures} from './helpers/consent-fixtures.mjs';
import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
const root=process.cwd();
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
sql.prepare("INSERT INTO settings(id,value) VALUES('pilot_emails',?)").run(JSON.stringify(['fixture-parent@example.test']));
installPrivacySchema(sql);
installConsentFixtures(sql);
class Prepared{constructor(query,args=[]){this.query=query;this.args=args;}bind(...args){return new Prepared(this.query,args)}async first(){return sql.prepare(this.query).get(...this.args)||null}async all(){return {results:sql.prepare(this.query).all(...this.args)}}async run(){const r=sql.prepare(this.query).run(...this.args);return {meta:{changes:Number(r.changes)}}}}
const DB={prepare(q){return new Prepared(q)},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__schooldayTest={env:{DB,APP_SECRET:'local-test-encryption-key',TEACHER_EMAILS:'educator@example.test'},headers:new Headers(),cookies:{}};
await build({entryPoints:['app/api/[action]/route.ts'],bundle:true,platform:'node',format:'esm',outfile:'/tmp/schoolday-reliability-test.mjs',alias:{'cloudflare:workers':path.join(root,'tests/helpers/runtime.mjs'),'next/headers':path.join(root,'tests/helpers/headers.mjs')}});
await build({entryPoints:['lib/quality.ts'],bundle:true,platform:'node',format:'esm',outfile:'/tmp/schoolday-reliability-quality-test.mjs'});
const {GET,POST}=await import('file:///tmp/schoolday-reliability-test.mjs');const {checkLesson,reviewsPass}=await import('file:///tmp/schoolday-reliability-quality-test.mjs');
async function call(action,body){const r=await(body===undefined?GET:POST)(new Request('https://schoolday.test/api/'+action,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:'https://schoolday.test'},body:body===undefined?undefined:JSON.stringify(body)}),{params:Promise.resolve({action:action.split('?')[0]})});return {status:r.status,data:await r.json()};}
const options=[{text:'One and a half portions',feedback:'Three sixths contains one and a half groups of two sixths.'},{text:'Two fifths',feedback:'We do not add denominators; they name the size of the equal parts.'},{text:'One sixth',feedback:'That is the difference, not the total of the two fractions.'}];
const source='https://www.thecorestandards.org/Math/Content/6/NS/';
const fixture={alignment:{standardId:'6.NS.1',evidence:'The teaching, worked model, application and both exit checks address division of fractions.'},title:'Divide using a common unit',subject:'Math',grade:6,objective:'Interpret and compute division of fractions using equal-sized units.',prerequisite:'Represent equivalent fractions on equal wholes.',materials:['Paper and pencil'],sources:[{title:'Common Core fraction standards',url:source,supports:'Adding fractions with unlike denominators using equivalent fractions.'}],stages:['notice','teach','model','practice','apply','reflect'].map((kind,i)=>({kind,title:['Notice the portions','Use the same-sized parts','Watch a worked example','Add the portions','Explain your model','Reflect on common units'][i],content:i===3?'How many one-third-cup portions fit into one half cup?':('Equivalent fractions describe the same quantity using different-sized equal parts. To divide one half by one third, rewrite each in sixths: one half is three sixths and one third is two sixths. Three sixths contains one and a half groups of two sixths, so the quotient is three halves. This works because both counts now refer to the same-sized part. Keep the whole the same size. ').repeat(i===1?2:1),prompt:'Explain why both fractions need the same-sized parts.',minutes:5,options:i===3?options:[],answer:i===3?0:-1,hint:i===3?'Draw two equal wholes divided into sixths.':'' ,rubric:i===4?['Use equal wholes','Explain a common denominator']:[],example:i===4?'I changed one half to three sixths and one third to two sixths. Dividing three equal units into groups of two gives one and a half portions.':'',visual:{kind:'none',values:[],labels:[],caption:''}})),checks:[{question:'How many one-half-cup portions fit into three fourths cup?',options:[{text:'One and a half',feedback:'Three fourths divided by two fourths is three halves.'},{text:'Two sixths',feedback:'Use equal-sized parts rather than adding denominators.'},{text:'One fourth',feedback:'One fourth is the difference rather than the sum.'}],answer:0},{question:'How many one-sixth-meter pieces can be cut from one third meter?',options:[{text:'Two pieces',feedback:'One third is two sixths, so two one-sixth pieces fit.'},{text:'Two ninths',feedback:'Adding denominators changes the size of the parts incorrectly.'},{text:'One sixth',feedback:'That is the difference rather than the sum.'}],answer:0}]};
const goodReview={solutions:['practice','check1','check2'].map(item=>({item,answerIndex:0,reasoning:'Solve independently using the quantities and the common unit.'})),role:'reviewer',pass:true,issues:[],summary:'The worked examples, keys, explicit instruction, and transfer tasks meet this lesson brief.'};
let fetchQueue=[],apiInputs=[];
globalThis.fetch=async(url,opts)=>{if(String(url).startsWith('https://www2.cde.ca.gov/')){const catalog=JSON.parse(fs.readFileSync('data/standards-catalog.json'));const code=catalog.find(s=>s.url===String(url)).id;return new Response('<h4>'+code+'</h4><div style="white-space: pre-wrap; "><b>Standard</b>: Interpret and compute quotients of fractions and solve contextual problems using division of fractions.</div>');}if(String(url).includes('/v1/models/'))return Response.json({id:'gpt-4.1-mini'});apiInputs.push(JSON.parse(opts.body));const result=fetchQueue.shift();if(result instanceof Error)throw result;if(!result)throw new Error('Unexpected AI call');return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:typeof result==='string'?result:JSON.stringify(result),annotations:typeof result==='string'?[{type:'url_citation',url:source,title:'Fractions'}]:[]}]}]});};
let alice,bob,cookieA,cookieB,lessonId,dayId;

const catalog=JSON.parse(fs.readFileSync('data/standards-catalog.json'));
const state=globalThis.__schooldayTest;
const out=(value)=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:typeof value==='string'?value:JSON.stringify(value),annotations:[{type:'url_citation',url:source,title:'Official source'}]}]}]});
const plan={theme:'Newer valid plan',question:'How do we use evidence to understand a problem?',items:['Literacy','Math','Science','Humanities','Studio'].map(subject=>({standardId:{Literacy:'RI.6.1',Math:'6.NS.1',Science:'MS-LS1-1',Humanities:'HSS-6.1.1',Studio:'W.6.2'}[subject],subject,title:'Explore '+subject,goal:'Use evidence to explain this assigned '+subject+' objective.',prerequisite:'Recall a connected idea in '+subject,minutes:40}))};
let handler=async()=>out(plan),officialDown=false,aiCalls=0;
globalThis.fetch=async(url,opts)=>{if(String(url).startsWith('https://www2.cde.ca.gov/')){if(officialDown)return new Response('Unavailable',{status:503});const c=catalog.find(s=>s.url===String(url));return new Response('<h4>'+c.id+'</h4><div style="white-space: pre-wrap; "><b>Standard</b>: Interpret and compute quotients of fractions, and solve word problems involving division of fractions by fractions.</div>');}aiCalls++;return handler(JSON.parse(opts.body));};
function educator(){state.headers=new Headers({'oai-authenticated-user-email':'educator@example.test'});}
function deferred(){let resolve,started;const ready=new Promise(r=>started=r),response=new Promise(r=>resolve=r);return {ready,resolve:r=>resolve(r),handler:async()=>{started();return response}};}
async function profileNew(){state.headers=new Headers({'oai-authenticated-user-id':'fixture-parent','oai-authenticated-user-email':'fixture-parent@example.test'});state.cookies={};await call('account-setup',{name:'Fixture family',kind:'family',adult:true});const p=(await call('profile',{name:'Reliability learner',grade:6})).data.profile;state.headers=new Headers();return p;}
async function digest(s){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(v=>v.toString(16).padStart(2,'0')).join('');}
async function seed(pid,status='queued',phase='research'){const did=crypto.randomUUID(),id=crypto.randomUUID(),n=Number(sql.prepare('SELECT COALESCE(MAX(day_number),0)+1 n FROM days WHERE profile_id=?').get(pid).n);sql.prepare("INSERT INTO days(id,profile_id,day_number,theme,question,status,created_at) VALUES(?,?,?,'Reliability','What stays saved?','ready',?)").run(did,pid,n,new Date().toISOString());sql.prepare("INSERT INTO activities(id,day_id,subject,title,goal,prerequisite,minutes,position,status,phase,standard_id) VALUES(?,?,'Math','Divide fractions','Interpret division of fractions','Equivalent units',40,0,?,?,'6.NS.1')").run(id,did,status,phase);return id;}
async function released(pid){const id=await seed(pid,'ready','ready');const payload=JSON.stringify(fixture),snapshot=JSON.stringify({id:'6.NS.1',version:'test-snapshot'}),reviews=['Subject accuracy reviewer','Instruction and accessibility reviewer','Standards alignment reviewer'].map(role=>({...goodReview,role}));sql.prepare('UPDATE activities SET payload=?,standard_snapshot=?,content_hash=?,reviews=? WHERE id=?').run(payload,snapshot,await digest(payload+'|'+snapshot),JSON.stringify(reviews),id);return id;}
test('standards and generation reliability',async t=>{
 state.env.OPENAI_API_KEY='test-only';
 await t.test('provider rate limits preserve the assignment without consuming repair attempts',async()=>{const p=await profileNew(),id=await seed(p.id);handler=async()=>new Response('rate limited',{status:429});assert.equal((await call('generate',{id})).status,429);const row=sql.prepare('SELECT * FROM activities WHERE id=?').get(id);assert.equal(row.generation_attempts,0);assert.equal(row.phase,'research');assert.equal(row.standard_id,'6.NS.1');assert.equal(row.lock_token,null);assert(row.next_retry_at>Date.now());});
 await t.test('network interruption retains the source pack and resumes the saved author step',async()=>{const p=await profileNew(),id=await seed(p.id);handler=async()=>out('Grounded source brief.');await call('generate',{id});const pack=sql.prepare('SELECT source_pack FROM activities WHERE id=?').get(id).source_pack;handler=async()=>{throw new Error('network interrupted')};assert.equal((await call('generate',{id})).status,502);const row=sql.prepare('SELECT * FROM activities WHERE id=?').get(id);assert.equal(row.phase,'author');assert.equal(row.source_pack,pack);assert.equal(row.payload,null);assert.equal(row.lock_token,null);});
 await t.test('catalog covers every supported grade/subject and preserves California integrated science placements',()=>{for(const grade of [6,7,8])for(const subject of ['Math','Literacy','Science','Humanities','Studio'])assert(catalog.some(s=>s.grade===grade&&s.subject===subject));assert(catalog.some(s=>s.grade===6&&s.id==='MS-PS3-4'));assert(!catalog.some(s=>s.grade===8&&s.id==='MS-PS3-4'));assert(catalog.some(s=>s.grade===8&&s.id==='MS-ESS1-1'));assert.equal(new Set(catalog.filter(s=>s.subject==='Science').map(s=>s.id)).size,59);});
 await t.test('day targets cannot be replaced by a model or an untrusted caller',async()=>{const p=await profileNew();handler=async()=>out({...plan,items:plan.items.map(s=>s.subject==='Math'?{...s,standardId:'7.RP.1'}:s)});const before=aiCalls;assert.equal((await call('plan',{standardId:'7.RP.1'})).status,200);assert.equal(aiCalls,before);assert.equal(sql.prepare("SELECT a.standard_id FROM activities a JOIN days d ON a.day_id=d.id WHERE d.profile_id=? AND a.subject='Math'").get(p.id).standard_id,'6.NS.1');});
 await t.test('expired planner lease cannot overwrite a newer plan or append duplicate activities',async()=>{const p=await profileNew(),slow=deferred(),batch=DB.batch;let first=true;DB.batch=async stmts=>{if(first&&stmts.some(s=>s.query.includes('INSERT INTO activities'))){first=false;await slow.handler();}return batch.call(DB,stmts)};const older=call('plan',{});await slow.ready;sql.prepare('UPDATE days SET locked_until=0 WHERE profile_id=?').run(p.id);assert.equal((await call('plan',{})).status,200);slow.resolve(null);assert.equal((await older).status,409);DB.batch=batch;assert.equal(sql.prepare('SELECT count(*) n FROM activities a JOIN days d ON a.day_id=d.id WHERE d.profile_id=?').get(p.id).n,9);});
 await t.test('official source outage fails closed before a model call; retry preserves the same assignment',async()=>{const p=await profileNew(),id=await seed(p.id);sql.prepare('DELETE FROM standard_cache').run();officialDown=true;const before=aiCalls;assert.equal((await call('generate',{id})).status,502);assert.equal(aiCalls,before);assert.equal((await call('generate',{id})).status,429);officialDown=false;sql.prepare('UPDATE activities SET next_retry_at=0 WHERE id=?').run(id);handler=async()=>out('Grounded source brief.');assert.equal((await call('generate',{id})).status,200);assert.equal(sql.prepare('SELECT phase FROM activities WHERE id=?').get(id).phase,'author');});
 await t.test('concurrent generation has one lease and a report permanently defeats the late result',async()=>{const p=await profileNew(),id=await seed(p.id);handler=async()=>out('Grounded source brief.');await call('generate',{id});const slow=deferred();handler=slow.handler;const pending=call('generate',{id});await slow.ready;const before=aiCalls;assert.equal((await call('generate',{id})).status,409);assert.equal(aiCalls,before);assert.equal((await call('report',{id,reason:'The example appears incorrect.'})).status,200);slow.resolve(out(fixture));assert.equal((await pending).status,409);const a=sql.prepare('SELECT * FROM activities WHERE id=?').get(id);assert.equal(a.status,'held');assert.equal(a.payload,null);assert.equal(a.lock_token,null);});
 await t.test('malformed responses stop after four failures and keep the last successful source step',async()=>{const p=await profileNew(),id=await seed(p.id);handler=async()=>out('Grounded source brief.');await call('generate',{id});const pack=sql.prepare('SELECT source_pack FROM activities WHERE id=?').get(id).source_pack;handler=async()=>out('{bad json');for(let n=0;n<4;n++){sql.prepare('UPDATE activities SET next_retry_at=0 WHERE id=?').run(id);assert.equal((await call('generate',{id})).status,502);}const a=sql.prepare('SELECT * FROM activities WHERE id=?').get(id);assert.equal(a.status,'held');assert.equal(a.generation_attempts,4);assert.equal(a.source_pack,pack);assert.equal((await call('generate',{id})).status,409);});
 await t.test('reviewer disagreement and an incorrect standard never produce a ready lesson',async()=>{const p=await profileNew(),id=await seed(p.id);let results=['Grounded source brief.',fixture,{...goodReview,solutions:goodReview.solutions.map(s=>({...s,answerIndex:1}))},goodReview,goodReview];handler=async()=>out(results.shift());for(let n=0;n<5;n++)assert.equal((await call('generate',{id})).status,200);assert.equal(sql.prepare('SELECT phase FROM activities WHERE id=?').get(id).phase,'revise');const bad=structuredClone(fixture);bad.alignment.standardId='7.RP.1';assert(checkLesson(bad,6,'Math',[source],'6.NS.1',40).length);bad.alignment.standardId='6.NS.1';bad.stages[0].options=options;bad.stages[0].answer=-1;assert(checkLesson(bad,6,'Math',[source],'6.NS.1',40).length);});
 await t.test('changed released content is withheld from the day and answer API',async()=>{const p=await profileNew(),id=await released(p.id);const changed=structuredClone(fixture);changed.stages[3].answer=1;sql.prepare('UPDATE activities SET payload=? WHERE id=?').run(JSON.stringify(changed),id);const day=await call('day');const a=day.data.activities.find(a=>a.id===id);assert.equal(a.status,'held');assert.equal(a.payload,null);assert.equal((await call('answer',{id,stage:0,response:'My reasoning stays safe.'})).status,409);});
 await t.test('simultaneous exit responses retain exactly one first response and agree on its result',async()=>{const p=await profileNew(),id=await released(p.id);for(let stage=0;stage<6;stage++)assert.equal((await call('answer',{id,stage,response:'This is my explanation of fraction division.',choice:stage===3?0:null})).status,200);const results=await Promise.all([call('answer',{id,stage:6,choice:0}),call('answer',{id,stage:6,choice:1})]);assert(results.every(r=>r.status===200));assert.equal(results[0].data.correct,results[1].data.correct);assert.equal(sql.prepare('SELECT count(*) n FROM evidence WHERE activity_id=? AND stage=6').get(id).n,1);});
 await t.test('replacement keeps earlier work, removes only the obsolete block from the current day, and rejects duplicate replacements',async()=>{const p=await profileNew(),id=await released(p.id);await call('answer',{id,stage:0,response:'Earlier evidence must remain attached to its original lesson.'});await call('report',{id,reason:'A problem in the model needs review.'});educator();const r=await call('replace-lesson',{id,standardId:'6.NS.1'});assert.equal(r.status,200);assert.equal((await call('replace-lesson',{id,standardId:'6.NS.1'})).status,409);assert.equal(sql.prepare('SELECT response FROM evidence WHERE activity_id=?').get(id).response,'Earlier evidence must remain attached to its original lesson.');state.headers=new Headers();const d=(await call('day')).data;assert.equal(d.activities.length,1);assert.equal(d.activities[0].id,r.data.id);assert.equal(d.activities[0].standard_id,'6.NS.1');assert.equal((await call('generate',{id})).status,409);});

});
