import type {Metadata} from 'next';
import {PolicyShell,BusinessContact} from '../policy-shell';
export const metadata:Metadata={title:'Privacy policy · Schoolday OS',alternates:{canonical:'https://schoolday-os.sickyicky.chatgpt.site/privacy'}};
export default function Page(){return <PolicyShell title='Privacy policy'><p>This notice covers Schoolday OS, operated by NovaPath LLC, including its public preview, adult accounts, learner workspaces and optional Squads. For privacy questions, access, correction or deletion requests, email <a href="mailto:Dan@explorenovapath.com">Dan@explorenovapath.com</a>.</p>
<h2>Information we collect and why</h2>
<ul><li><strong>Adult account information:</strong> sign-in identifier, email, account name, account type, security settings and account–learner relationships. We use these to authenticate adults, protect controls and provide support.</li><li><strong>Learner information:</strong> a name or nickname, grade, learning preferences, assigned lessons, drafts, answers, checks, progress and saved place in the workflow. These support instruction, feedback and resuming work. Use a nickname and avoid unnecessary identifying information.</li><li><strong>Family records:</strong> the educational pathway, school-year plans, attendance confirmations, subject plans and notes you choose to enter. These are parent records, not a certification of school compliance.</li><li><strong>Squad information:</strong> room membership, learner display names and discussion contributions when you choose to collaborate.</li><li><strong>Billing information:</strong> Stripe customer and subscription identifiers, purchased learner quantity, payment status and billing periods. Stripe collects payment details on its checkout and billing pages; the Schoolday application does not store full card numbers.</li><li><strong>Adult email interest:</strong> email, audience, campaign source, consent and confirmation records, and message-delivery status when you request updates.</li><li><strong>Technical information:</strong> session identifiers, browser requests, network information, security and error logs, and usage counts needed to operate the service, investigate failures and limit abuse.</li></ul>
<h2>AI generation and review</h2>
<p>OpenAI processes curriculum objectives, grade-level context, learning preferences, source material, generated lesson drafts and review instructions to prepare and check lessons. Generation requests are designed to omit learner names and account contact details. Information entered into free-text fields can still contain identifying details, so do not enter addresses, medical records, passwords or other sensitive information. AI output can be inaccurate and needs adult review.</p>
<p>The app requests that Responses API outputs not be stored for later retrieval. This setting does not mean that providers retain no data: security, abuse-monitoring and other provider retention rules may still apply. See <a href="https://developers.openai.com/api/docs/guides/your-data">OpenAI’s API data controls</a>. Public web search is used to retrieve instructional sources.</p>
<h2>Who receives information</h2>
<p>Authorized adults can view records in their workspace. NovaPath operators may access records when operating the service, responding to support requests or reviewing reported problems. In a Squad, other members can see the display name and contributions shared with that room. Room codes should be treated as private. Solo learning does not require sharing contributions with peers.</p>
<p>Service providers process information needed for their functions: OpenAI/ChatGPT for sign-in and AI services; Sites and Cloudflare for hosting, storage and request processing; Stripe for subscriptions and payments; and Resend for adult emails when email delivery is enabled. Providers may process data in the United States and other countries. Their separate services have their own policies, including <a href="https://stripe.com/privacy">Stripe</a>, <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a> and <a href="https://resend.com/legal/privacy-policy">Resend</a>.</p>
<p>We do not sell learner information or use it for targeted advertising. The app does not install advertising trackers. We may disclose information when legally required or reasonably necessary to protect accounts, rights and safety. Schoolday does not publicly publish private learner records.</p>
<h2>Children and parental control</h2>
<p>Accounts and purchases must be managed by an adult. A parent or guardian can export or delete linked learner records and revoke consent in <a href="/family-privacy">Privacy controls</a>. Contact support for corrections or help. We may ask for proportionate verification of the requester’s authority before releasing or changing records. Do not email a child’s identity documents unless a secure process has first been arranged.</p>
<p>For a child under 13, direct parental notice and verifiable parental consent must be completed before collection that requires consent. Adult sign-in, a checkbox, or an invitation alone does not establish this. Family learner setup stays blocked until verification through a successful paid card subscription matching the parent’s saved consent choices, or until a NovaPath operator reviews a signed consent form or completes a verification video call. Payment verification checks the actual invoice and card charge, including its receipt; a trial, checkbox or checkout redirect alone is insufficient. We store a payment reference, not full card details. Start in Privacy controls; do not submit child information in the request. Squad sharing requires separate optional permission. Revoking consent blocks learner access and invalidates learner sessions; it does not cancel billing or delete saved contributions. Delete a learner to remove their active records.</p>
<h2>Retention and deletion</h2>
<p>Learning records and saved work support continuation and parent recordkeeping. Subscription cancellation does not automatically delete them. Use Privacy controls to download records or permanently delete a learner. Deletion removes the learner’s active lessons, work, discussions and profile, and closes rooms they hosted. It does not remove copies other people already exported. Export records you need first. Learner records expire after 365 days without learner access. Expired access is blocked immediately; bounded maintenance removes expired records on subsequent app requests. Subscription cancellation alone does not erase records. Adult consent, transaction and security records are separate; contact support to request their deletion and learn about any legally required retention.</p>
<p>Active launch-list entries are removed after 90 days on the next signup or owner review, or sooner through the private removal link or owner action. Removing an entry stops pending app messages; messages already sent to the delivery provider may still arrive. Provider logs, suppression records needed to honor unsubscribe requests, backups and previously downloaded exports are separate from the active list. They are not all erased by unsubscribing.</p>
<h2>Cookies, choices and security</h2>
<p>Necessary cookies and local browser state keep sessions, security controls and learning progress working. Blocking them may prevent sign-in or resuming work. The app does not use browsing information for cross-context behavioral advertising, so there is no advertising sale or sharing to opt out of in this app. We do not change these practices based on a browser’s Do Not Track setting.</p>
<p>Access controls and encrypted server-side credentials help protect the service; no system can promise absolute security. Keep adult sign-in, PINs, recovery codes and room codes private. Marketing consent is optional, and adult emails include an unsubscribe or removal method. Depending on applicable law, you may have additional access, correction, deletion and other privacy rights. Contact support to exercise them without discrimination for doing so.</p>
<h2>Changes and contact</h2>
<p>We update the effective date when this notice changes and provide additional notice or obtain consent when required before materially changing how personal information is used. Questions or a suspected privacy issue: <a href="mailto:Dan@explorenovapath.com">Dan@explorenovapath.com</a>.</p><h2>Business contact</h2><BusinessContact/></PolicyShell>}
