'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,BookOpen,Check,HelpCircle,Loader2,RefreshCw,Settings2} from 'lucide-react';
import {NumericVisual} from './numeric-visual';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';

async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d;}
export const defaultPreferences={textSize:'standard',focus:false,reducedMotion:false,speechRate:'normal',instruction:'standard'};
export function ReadingSettings({value,onChange}:{value:typeof defaultPreferences;onChange:(p:typeof defaultPreferences)=>void}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(value),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <><button onClick={()=>{setDraft(value);setError('');setOpen(true)}}><Settings2 size={17}/>Reading settings</button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>Make this space work for you</DialogTitle><DialogDescription>Saved with your learner profile. Change these whenever you need.</DialogDescription><form className="reading-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await api('preferences',draft);onChange(r.preferences);setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 <label>Text size<Select value={draft.textSize} onValueChange={textSize=>setDraft({...draft,textSize})}><SelectTrigger aria-label="Text size"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="standard">Standard</SelectItem><SelectItem value="large">Larger</SelectItem></SelectContent></Select></label>
 <label>Read-aloud speed<Select value={draft.speechRate} onValueChange={speechRate=>setDraft({...draft,speechRate})}><SelectTrigger aria-label="Read-aloud speed"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="normal">Normal</SelectItem><SelectItem value="slow">Slower</SelectItem></SelectContent></Select></label>
 <label>New lesson explanations<Select value={draft.instruction} onValueChange={instruction=>setDraft({...draft,instruction})}><SelectTrigger aria-label="Explanation style"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="standard">Standard</SelectItem><SelectItem value="chunked">Shorter chunks, numbered steps</SelectItem></SelectContent></Select></label><p className="micro">Explanation style applies to future generation. Your learning goals and saved lessons stay intact.</p>
 <label className="adult-check"><Checkbox checked={draft.focus} onCheckedChange={v=>setDraft({...draft,focus:v===true})}/>Focus view · keep lesson extras tucked away</label><label className="adult-check"><Checkbox checked={draft.reducedMotion} onCheckedChange={v=>setDraft({...draft,reducedMotion:v===true})}/>Reduce animation</label>{error&&<p role="alert" className="thread-error">{error}</p>}<Button className="primary" disabled={busy}>{busy?'Saving…':'Save reading settings'}</Button></form></DialogContent></Dialog></>;
}

export function ProgressPanel({learnerId,onContinue}:{learnerId?:string;onContinue?:(id:string)=>void}){
 const [data,setData]=useState<any>(null),[day,setDay]=useState<any>(null),[review,setReview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{let gone=false;setData(null);setDay(null);setReview(null);api(learnerId?'learner-progress?id='+learnerId:'progress').then(d=>{if(!gone)setData(d)}).catch(e=>{if(!gone)setError(e.message)});return()=>{gone=true}},[learnerId]);
 const inspect=(id:string)=>run(async()=>setReview(await api(learnerId?'learner-activity?profile='+learnerId+'&id='+id:'resume?id='+id)));
 const lesson=review?.activity.payload?JSON.parse(review.activity.payload):null;
 return <section className="progress-space">{error&&<p className="thread-error" role="alert">{error}</p>}{!data?<p><Loader2 className="spin" size={18}/>Loading learning history…</p>:<>
 <div className="section-heading"><h2>{learnerId?data.learner.name+'’s learning':'Your learning so far'}</h2><span>{Number(data.totals.responses)*10} total XP</span></div><p className="progress-caption">First independent answers show where to return. They are practice signals, not a mastery score.</p>
 <div className="subject-progress-grid">{data.subjects.map((s:any)=><article key={s.subject}><span>{s.subject}</span><strong>{s.completed}<small> activities completed</small></strong><p>{s.checks?`${s.correct} of ${s.checks} first check answers correct`:'Independent checks will appear here.'}</p></article>)}</div>
 {data.coverage&&<details className="workspace-card"><summary>Standards addressed</summary><p>Counts show assigned standards and completed lessons—not mastery or full-year curriculum coverage. Studio tracks writing and project communication.</p>{data.coverage.map((s:any)=><p key={s.subject}><strong>{s.subject}</strong>: {s.planned} of {s.available} catalog targets assigned; {s.withCompletedLessons} have a completed lesson.</p>)}{data.standards?.map((s:any)=><p key={s.subject+s.standard_id}><a href={s.url} target="_blank" rel="noreferrer">{s.standard_id}</a> · {s.subject} · {s.completed} completed lessons</p>)}</details>}
 {!!data.revisit.length&&<section className="revisit-list"><h3>Ideas to revisit</h3>{data.revisit.map((a:any)=><button disabled={busy} key={a.id} onClick={()=>inspect(a.id)}><BookOpen size={19}/><span><strong>{a.title}</strong><small>{a.subject} · Day {a.day_number} · {a.revisit} check{a.revisit===1?'':'s'} to revisit</small></span><ArrowRight size={17}/></button>)}</section>}
 <div className="section-heading"><h3>Saved days</h3><span>Most recent 60</span></div>{data.days.length?<div className="history-grid">{data.days.map((d:any)=><button key={d.id} disabled={busy} className={day?.day.id===d.id?'selected':''} onClick={()=>run(async()=>setDay(await api(learnerId?'learner-history-day?profile='+learnerId+'&id='+d.id:'history-day?id='+d.id)))}><span>DAY {d.day_number}</span><strong>{d.theme}</strong><small>{d.completed} / {d.blocks} activities complete</small></button>)}</div>:<p>Your first learning day will appear here.</p>}
 {day&&<section className="history-detail"><h3>Day {day.day.day_number} · {day.day.theme}</h3><p>{day.day.question}</p>{day.activities.map((a:any)=><div className="history-activity" key={a.id}><div><strong>{a.title}</strong><small>{a.subject} · {a.status==='complete'?'Completed':a.status==='held'?'Awaiting review':a.status==='ready'?'Ready':'In preparation'}</small></div>{a.status==='complete'||learnerId?<Button variant="outline" disabled={busy} onClick={()=>inspect(a.id)}>View work</Button>:onContinue&&<Button variant="outline" disabled={busy} onClick={()=>onContinue(a.id)}>Continue<ArrowRight size={15}/></Button>}</div>)}</section>}
 </>}
 <Dialog open={!!review} onOpenChange={o=>!o&&setReview(null)}><DialogContent className="work-dialog lesson-review"><DialogTitle>{review?.activity.title}</DialogTitle><DialogDescription>Read-only lesson and saved work. Reviewing does not change first check results.</DialogDescription>{review&&<><p>{review.activity.goal}</p>{lesson?<>{lesson.stages.map((s:any,i:number)=><details key={i} open={i===2}><summary>Step {i+1} · {s.title}</summary><div className="review-content">{s.content.split('\n').filter(Boolean).map((p:string,j:number)=><p key={j}>{p}</p>)}<NumericVisual visual={s.visual}/><strong>{s.prompt}</strong>{s.options.map((o:any,j:number)=><p key={j}>{String.fromCharCode(65+j)}. {o.text}</p>)}{review.evidence.filter((e:any)=>e.stage===i).map((e:any)=><blockquote key={e.id}><small>Saved response</small>{e.response||s.options[e.choice]?.text}</blockquote>)}</div></details>)}{lesson.checks.map((c:any,i:number)=>{const e=review.evidence.find((e:any)=>e.stage===i+6);return <section className="review-check" key={i}><h3>Independent check {i+1}</h3><p>{c.question}</p>{e?<><p>First response: {c.options[e.choice]?.text||e.response}</p><strong>{e.correct===1?'Correct first response':'Return to the model to revisit this idea.'}</strong></>:<p>No submitted answer yet.</p>}</section>})}</>:review.evidence.length?review.evidence.map((e:any)=><blockquote key={e.id}>{e.response||'Activity completed'}</blockquote>):<p>This activity has no saved work yet.</p>}{lesson?.sources?.length>0&&<details><summary>Lesson sources</summary>{lesson.sources.map((source:any)=><p key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a></p>)}</details>}{onContinue&&review.activity.status!=='complete'&&<Button className="primary" onClick={()=>{const id=review.activity.id;setReview(null);onContinue(id)}}>Continue this activity<ArrowRight size={16}/></Button>}</>}</DialogContent></Dialog>
 </section>;
}

export function LearnerHelp({activityId,stage=0,compact=false,onContinue}:{activityId?:string;stage?:number;compact?:boolean;onContinue?:(id:string)=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<any>(null),[question,setQuestion]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setData(await api('help'));}
 useEffect(()=>{let gone=false;api('help').then(d=>{if(!gone)setData(d)}).catch(e=>{if(!gone)setError(e.message)});return()=>{gone=true}},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const replies=data?.requests.filter((h:any)=>h.status==='answered').length||0;
 return <><button className={compact?'help-trigger':'help-home'} onClick={()=>{setOpen(true);run(load)}}><HelpCircle size={19}/>{compact?'Ask for help':replies?`${replies} help ${replies===1?'reply':'replies'} ready`:'Questions & help'}{replies>0&&compact&&<span className="reply-count">{replies}</span>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="work-dialog"><DialogTitle>A little help, right where you are</DialogTitle><DialogDescription>Your linked adult or assigned teacher can reply here. You can continue other work while you wait.</DialogDescription>{error&&<p role="alert" className="thread-error">{error}</p>}{message&&<p role="status" className="save-message">{message}</p>}{activityId&&data?.available&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await api('help-request',{id:activityId,stage,question});setQuestion('');await load();setMessage('Your question is saved for your adult. Replies appear here.');})}}><label htmlFor="help-question">What part would you like help with?</label><Textarea id="help-question" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} rows={3} placeholder="I tried… I’m unsure about…"/><Button className="primary" disabled={busy||question.trim().length<5}>Save question</Button></form>}{data&&!data.available&&<p>An adult needs to link this learner profile or assign a teacher before questions can reach them. Ask someone nearby for help in the meantime.</p>}<div className="section-heading"><h3>Your questions</h3><Button variant="ghost" disabled={busy} onClick={()=>run(load)}><RefreshCw size={15}/>Refresh</Button></div>{data?.requests.length?data.requests.map((h:any)=><article className="help-thread" key={h.id}><small>{h.subject} · Step {h.stage+1} · {h.status==='open'?'Waiting for a reply':h.status==='answered'?'Reply ready':'Reviewed'}</small><h3>{h.title}</h3><p>{h.question}</p>{h.response&&<blockquote><strong>{h.responder}</strong><p>{h.response}</p></blockquote>}<div className="help-actions">{h.status==='answered'&&<Button variant="outline" disabled={busy} onClick={()=>run(async()=>{await api('help-resolve',{id:h.id});await load()})}><Check size={15}/>I’ve read this</Button>}{onContinue&&h.activity_id!==activityId&&<Button variant="ghost" onClick={()=>{setOpen(false);onContinue(h.activity_id)}}>Open activity<ArrowRight size={15}/></Button>}</div></article>):<p>No questions saved yet. Use Ask for help inside a lesson when you need a hand.</p>}</DialogContent></Dialog></>;
}

export function HelpInbox(){
 const [requests,setRequests]=useState<any[]|null>(null),[response,setResponse]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setRequests((await api('help-inbox')).requests);}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="support-inbox"><div className="section-heading"><div><h2>Learner questions</h2><p>Questions from your linked learners and learners assigned to you.</p></div><Button variant="outline" disabled={busy} onClick={()=>run(load)}><RefreshCw size={16}/>Refresh</Button></div>{error&&<p role="alert" className="thread-error">{error}</p>}{requests===null?<p>Opening questions…</p>:requests.length?requests.map(h=><article className="help-thread" key={h.id}><span className="eyebrow">{h.name} · GRADE {h.grade} · {h.status==='open'?'NEEDS A REPLY':h.status==='answered'?'REPLY SAVED':'REVIEWED BY LEARNER'}</span><h3>{h.title}</h3><small>{h.subject} · Step {h.stage+1} · {new Date(h.created_at).toLocaleDateString()}</small><p>{h.question}</p>{h.response?<blockquote>{h.response}</blockquote>:selected===h.id?<form onSubmit={e=>{e.preventDefault();run(async()=>{await api('help-answer',{id:h.id,response});setSelected('');setResponse('');await load()})}}><label htmlFor="adult-help-response">Give a useful next step</label><Textarea id="adult-help-response" value={response} onChange={e=>setResponse(e.target.value)} maxLength={4000} placeholder="Start with the model. Notice how…"/><p className="micro">This reply appears in the learner’s app. It does not send an email or text.</p><Button className="primary" disabled={busy||response.trim().length<5}>Save reply</Button></form>:<Button variant="outline" onClick={()=>{setSelected(h.id);setResponse('')}}>Reply</Button>}</article>):<div className="workspace-empty"><HelpCircle size={32}/><h3>No questions waiting.</h3><p>Learners can ask from any prepared lesson without losing their place.</p></div>}</section>;
}
