'use client';
import {YearPanel} from './year-panel';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Please try again.');return d;}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function FamilyPanel({roster,onGradeChange}:{roster:any[];onGradeChange?:()=>Promise<void>}){const [pid,setPid]=useState(roster[0]?.id||''),[year,setYear]=useState(''),[data,setData]=useState<any>(null),[setup,setSetup]=useState<any>(null),[date,setDate]=useState(today),[attendance,setAttendance]=useState('present'),[instruction,setInstruction]=useState(''),[next,setNext]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[saveId,setSaveId]=useState('');
 function accept(d:any){setData(d);const saved=d.setup||{schoolYear:d.schoolYear,pathway:'exploring',schoolName:'',recordReference:'',instructor:'',checks:[],subjects:[]};setSetup({...saved,subjects:d.subjects.map((s:any)=>saved.subjects.find((p:any)=>p.id===s.id)||{id:s.id,plan:''})});}
 async function load(){if(pid)accept(await api('family?profile='+pid+(year?'&year='+year:'')));}
 useEffect(()=>{let gone=false;setData(null);setError('');if(pid)api('family?profile='+pid+(year?'&year='+year:'')).then(d=>{if(!gone)accept(d)}).catch(e=>{if(!gone)setError(e.message)});return()=>{gone=true}},[pid,year]);
 useEffect(()=>{const r=data?.records.find((r:any)=>r.school_date===date)?.data;setAttendance(r?.attendance||'present');setInstruction(r?.instruction||'');setNext(r?.nextStep||'');setConfirmed(false);setSaveId(crypto.randomUUID())},[date,data]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!roster.length)return <section className="workspace-card"><h2>Your homeschool organizer</h2><p>Add a learner first. Then keep their schooling arrangement, subject plan, and daily register here.</p></section>;
 return <section className="family-space"><div className="section-heading"><div><h2>Your homeschool organizer</h2><p>Plan the learning. Review the work. Keep the records.</p></div><Button variant="outline" disabled={busy} onClick={()=>run(load)}>Reload records</Button></div><div className="school-form-grid"><Select value={pid} disabled={busy} onValueChange={setPid}><SelectTrigger aria-label="Learner for homeschool records"><SelectValue/></SelectTrigger><SelectContent>{roster.map(p=><SelectItem key={p.id} value={p.id}>{p.name} · Grade {p.grade}</SelectItem>)}</SelectContent></Select><Select value={year||data?.schoolYear||''} disabled={busy} onValueChange={setYear}><SelectTrigger aria-label="School year"><SelectValue placeholder="School year"/></SelectTrigger><SelectContent>{Array.from({length:7},(_,i)=>new Date().getFullYear()-5+i).map(y=><SelectItem key={y} value={y+'-'+(y+1)}>{y}–{y+1}</SelectItem>)}</SelectContent></Select></div>{error&&<p className="thread-error" role="alert">{error}</p>}{message&&<p className="save-message" role="status">{message}</p>}{data&&setup?<>
 <section className="workspace-card"><h3>California · parent-directed learning</h3><p>Schoolday supplies learning software and a record organizer. You or your enrolled program operate the school, provide instruction, and determine which requirements apply. These checkboxes record your planning; they do not verify legal compliance.</p><p><a href="/family-guide" target="_blank" rel="noreferrer">Read the California family guide and what the app covers</a></p></section>
 <div className="workspace-card"><YearPanel key={pid} learnerId={pid} onGradeChange={async()=>{await load();await onGradeChange?.();}}/></div>
 <form className="workspace-card reading-form" onSubmit={e=>{e.preventDefault();run(async()=>{accept(await api('family-setup',{profile:pid,revision:data.setupRevision,setup}));setMessage('Schooling plan saved.');})}}><h3>1. Set up your school year</h3><label>Schooling arrangement<Select value={setup.pathway} onValueChange={v=>setSetup({...setup,pathway:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="exploring">Still arranging our schooling path</SelectItem><SelectItem value="private_home">Parent-operated California private home school</SelectItem><SelectItem value="enrolled_program">Enrolled in a school or program</SelectItem></SelectContent></Select></label><label>School or program name<Input maxLength={150} value={setup.schoolName} onChange={e=>setSetup({...setup,schoolName:e.target.value})}/></label><label>Responsible instructor<Input maxLength={150} value={setup.instructor} onChange={e=>setSetup({...setup,instructor:e.target.value})}/></label><label>Where you keep filing / enrollment / instructor records<Input maxLength={300} value={setup.recordReference} onChange={e=>setSetup({...setup,recordReference:e.target.value})} placeholder="For example: our private school folder"/></label><p className="micro">Keep addresses, health information, IDs, and official documents in your private school records.</p>{data.checklist.map((c:any)=><div key={c.id}><label className="adult-check"><Checkbox checked={setup.checks.includes(c.id)} onCheckedChange={v=>setSetup({...setup,checks:v?[...new Set([...setup.checks,c.id])]:setup.checks.filter((x:string)=>x!==c.id)})}/>{c.label}</label><p className="micro">{c.detail}</p></div>)}<h3>2. Plan every area of study</h3><p>The generated day supports core learning. Name the resources, teaching, and schedule you will use for the whole course, including subjects outside the app. Blank plans stay visible as gaps.</p>{data.subjects.map((s:any)=><label key={s.id}>{s.label}<span className="micro block">{s.coverage}</span><Textarea rows={2} maxLength={1200} value={setup.subjects.find((x:any)=>x.id===s.id)?.plan||''} onChange={e=>setSetup({...setup,subjects:setup.subjects.map((x:any)=>x.id===s.id?{...x,plan:e.target.value}:x)})} placeholder="Resource, instructor, and weekly schedule"/></label>)}<Button className="primary" disabled={busy}>Save school-year plan</Button></form>
 <form className="workspace-card reading-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api('family-journal',{id:saveId,profile:pid,schoolYear:data.schoolYear,date,revision:data.records.find((r:any)=>r.school_date===date)?.revision||0,attendance,instruction,nextStep:next,adultConfirmed:confirmed});await load();setMessage('Daily register saved. Earlier versions are retained.');})}}><h3>3. Close the day together</h3><p>Review one explanation and the independent checks. Ask your learner to try a new example without help. Record what needs reteaching; a completed activity is not proof of understanding.</p><label>California school date<Input type="date" required max={today()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Parent-reported attendance<Select value={attendance} onValueChange={v=>{setAttendance(v);setSaveId(crypto.randomUUID())}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="present">Present · no absence of half a day or more</SelectItem><SelectItem value="half_absent">Absent for half a day</SelectItem><SelectItem value="absent">Absent for the full day</SelectItem><SelectItem value="not_scheduled">School not scheduled</SelectItem></SelectContent></Select></label><label>Instruction and work actually reviewed<Textarea rows={4} maxLength={6000} value={instruction} onChange={e=>{setInstruction(e.target.value);setSaveId(crypto.randomUUID())}} placeholder="Include offline subjects. Note a new example they could explain and where they needed help."/></label><label>What should happen next?<Textarea rows={2} maxLength={1500} value={next} onChange={e=>{setNext(e.target.value);setSaveId(crypto.randomUUID())}} placeholder="For example: revisit the model together before moving on."/></label><label className="adult-check"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>I reviewed this record and confirm it reflects our actual day.</label><Button className="primary" disabled={busy||!confirmed}>Save daily register</Button><p className="micro">Attendance is never filled in from logins, lesson duration estimates, or scores. This register does not submit attendance to a school or claim public funds.</p></form>
 <section className="workspace-card"><div className="section-heading"><h3>Your records · {data.schoolYear}</h3><Button variant="outline" disabled={busy} onClick={()=>run(async()=>{const archive=await api('family-export?profile='+pid+'&year='+data.schoolYear);const url=URL.createObjectURL(new Blob([JSON.stringify(archive,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='schoolday-family-'+data.schoolYear+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('School-year records and work samples exported.');})}>Export records & work</Button></div><p>{data.records.length} dates recorded. {setup.subjects.filter((s:any)=>!s.plan.trim()).length} areas still need a written plan.</p>{data.records.slice(0,14).map((r:any)=><details key={r.id}><summary>{r.school_date} · {r.data.attendance.replaceAll('_',' ')} · revision {r.revision}</summary><p className="record-text">{r.data.instruction||'No instruction entered.'}</p><p className="record-text">{r.data.nextStep}</p><Button variant="ghost" onClick={()=>setDate(r.school_date)}>Review this date</Button></details>)}<p className="micro">The latest 14 dates appear here. The export includes the selected year’s register, revision history, plan, and saved app work. Keep a separate copy with your school records.</p></section>
 </>:!error&&<p>Opening your family records…</p>}</section>;
}
