'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {campaignHref,campaignSource,pipelineOrigin} from '@/lib/pipeline-content';
async function api(action:string,body?:unknown){const r=await fetch('/api/'+action,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}
export function PipelinePanel(){const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reviewed,setReviewed]=useState(false),[source,setSource]=useState('parent_referral'),[grade,setGrade]=useState('6');
 useEffect(()=>{api('pipeline').then(setData).catch(e=>setError(e.message))},[]);
 async function run(action:string,body:unknown|undefined,success:string){setBusy(true);setError('');setMessage('');try{setData(await api(action,body));setMessage(success)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const link=pipelineOrigin+campaignHref('/try?grade='+grade,source);
 return <section className="workspace-card customer-pipeline" id="customer-pipeline"><div className="section-heading"><div><span className="eyebrow">CUSTOMER PIPELINE</span><h3>From first lesson to first week</h3></div><strong>{data?.config?.enabled?'New sequences enabled':data?.config?.prepared?'Prepared · paused':'Draft · no sequences running'}</strong></div><p>Give parents a useful sample, follow up with permission, and help new families begin.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <div className="pipeline-metrics">{[['leads','Parent signups'],['confirmed','Confirmed emails'],['accounts','Family accounts'],['subscribers','Live active plans'],['learning','Started learning']].map(([key,label])=><div key={key}><strong>{data?data.totals[key]:'—'}</strong><span>{label}</span></div>)}</div><p className="micro">Counts cover family signups retained in the last 90 days, matched to an adult account by email. Live plans exclude sandbox payments and trials. Started learning means at least one generated lesson completed; it can include pilots. These are overlapping milestones, not visitor conversion rates.</p>
 <details open><summary>1. Share a sample and track its source</summary><div className="pipeline-link-fields"><label>Campaign name<Input value={source} maxLength={60} onChange={e=>setSource(e.target.value)} placeholder="parent_referral"/></label><label>Sample grade<select value={grade} onChange={e=>setGrade(e.target.value)}>{[6,7,8].map(g=><option key={g} value={g}>Grade {g}</option>)}</select></label></div><label>Shareable sample link<Input readOnly value={link} onFocus={e=>e.target.select()}/></label><div className="launch-links"><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Sample link copied.')}catch{setError('Select the sample link above and copy it.')}}}>Copy sample link</Button><a href={link} target="_blank" rel="noreferrer">Open sample</a></div><p className="micro">Source: {campaignSource(source)}. Links preserve the source through the sample and signup. This creates a link; it does not post, send messages, or purchase ads.</p><details><summary>First traffic experiment</summary><p>Start with parents and community partners who choose to share the sample. Once live learning and checkout are verified, test searches such as “6th grade homeschool curriculum” with a separately approved total budget of $150. Track paid families and learning completion before increasing spend.</p><p>Describe Schoolday as parent-led learning software. Advertising and referral performance are not yet measured.</p></details></details>
 <details><summary>2. Review all six follow-up messages</summary><p>Only adults who explicitly request these emails and confirm their address are eligible. Existing launch-list consent is not expanded. A live subscription changes the sequence after its provider contact update succeeds.</p>{data?.messages.map((m:any)=><article className="pipeline-preview" key={m.id}><span className="eyebrow">{m.flow==='prospect'?'AFTER CONFIRMATION':'AFTER LIVE SUBSCRIPTION'} · {m.day===0?'IMMEDIATELY':'DAY '+m.day}</span><h4>{m.subject}</h4><p>{m.body}</p><a href={m.path} target="_blank" rel="noreferrer">{m.label}</a></article>)}<p className="micro">Each email includes the verified business sender, mailing address, and Resend unsubscribe link. No learner names, answers, or lesson records are sent to Resend.</p></details>
 <details open><summary>3. Connect the sequence</summary><p>{data?.senderReady?'Verified sender saved.':'Connect your verified Resend sender in Email follow-up below.'} The key also needs access to contacts, contact properties, templates, events, and automations. Preparing creates templates and disabled automations; it sends no messages.</p><div className="launch-links"><Button variant="outline" disabled={busy||!data?.senderReady||data?.config?.enabled} onClick={()=>run('pipeline-prepare',{},'Templates prepared. The two sequences remain paused until you enable them.')}>{busy?'Working…':'Prepare Resend sequences'}</Button><a href="https://resend.com/automations" target="_blank" rel="noreferrer">Open Resend automations</a></div><label className="adult-check"><Checkbox checked={reviewed} onCheckedChange={v=>setReviewed(v===true)}/>I reviewed these messages and authorize follow-up to newly confirmed, consenting parents.</label><div className="launch-links"><Button disabled={busy||!reviewed||!data?.config?.prepared||!data?.sendingEnabled||data?.config?.enabled||data?.needsRefresh} onClick={()=>run('pipeline-switch',{enabled:true,reviewed:true},'New consenting signups can now begin the reviewed sequences.')}>Enable new sequences</Button><Button variant="outline" disabled={busy||!data?.config?.prepared} onClick={()=>run('pipeline-switch',{enabled:false,reviewed:true},'New sequence starts paused. Review in-flight runs in Resend.')}>Pause new sequences</Button></div><p className="micro">Resend runs accepted sequences in the background. Pausing stops new starts; in-flight runs may finish. Purchases, cancellations, and removals update the contact state used before each email. Failed state updates need attention below; messages already accepted may still arrive. No campaign or email is enabled by this deployment.</p></details>
 <details><summary>Campaign results and delivery checks</summary>{data?.sources?.length?<div className="pipeline-table-wrap"><table><thead><tr><th>Source</th><th>Signups</th><th>Confirmed</th><th>Live plans</th></tr></thead><tbody>{data.sources.map((r:any)=><tr key={r.source}><td>{r.source}</td><td>{r.leads}</td><td>{r.confirmed}</td><td>{r.subscribers}</td></tr>)}</tbody></table></div>:<p>No family signups recorded yet. Share a sample link to begin.</p>}<div className="launch-links"><Button variant="outline" disabled={busy} onClick={()=>run('pipeline',undefined,'Pipeline refreshed.')}>Refresh</Button><Button variant="outline" disabled={busy||!data?.config?.prepared} onClick={()=>run('pipeline-retry',{},'Retried safe contact updates. Uncertain sequence triggers are not resent.')}>Retry 3 contact updates</Button></div>{data?.recent?.map((r:any)=><article className="pipeline-preview" key={r.lead_id}><strong>{r.state}</strong><p>Sample sequence: {r.prospect_status} · Getting started: {r.customer_status}</p>{r.error&&<p role="status">{r.error}</p>}</article>)}<p className="micro">Accepted means Resend accepted a sequence trigger, not inbox delivery. Check its run log for delayed steps and send failures. Uncertain triggers are held for review to avoid duplicate sequences.</p></details></section>;
}
