'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,Clock,MessageCircle,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export const modeNames:Record<string,string>={solo:'Solo',solo_async:'Solo',squad_live:'Squad · live',squad_async:'Squad · at our pace'};
export const modeDescriptions:Record<string,string>={solo:'Move through today’s path independently.',solo_async:'Stop anywhere. Return to your saved step and draft.',squad_live:'Share the lesson and move through each step together.',squad_async:'Contribute on your schedule. Return to respond to teammates.'};
export function ModePicker({value,onChange,disabled=false}:{value:string;onChange:(value:string)=>void;disabled?:boolean}){return <Select value={value.startsWith('squad')?'squad':'solo'} onValueChange={v=>onChange(v==='squad'?'squad_async':'solo_async')} disabled={disabled}><SelectTrigger className="learning-mode-picker" aria-label="How you want to learn"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="solo">Solo</SelectItem><SelectItem value="squad">Squads</SelectItem></SelectContent></Select>}

async function request(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);return d;}
export function SquadPanel({room,code,busy,advance,onChange,discussion=false}:{room:any;code:string;busy:boolean;advance:()=>void;onChange:()=>void;discussion?:boolean}){
 const [target,setTarget]=useState(''),[reply,setReply]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [threadStage,setThreadStage]=useState('4'),[thread,setThread]=useState<any>(null);
 useEffect(()=>{if(!discussion){setThread(null);return;}let gone=false;request(`room?code=${code}&stage=${threadStage}`).then(d=>{if(!gone)setThread(d)}).catch(e=>{if(!gone)setError(e.message)});return()=>{gone=true}},[code,discussion,threadStage]);
 const current=discussion?(thread||room):room,me=current.members.find((m:any)=>m.isYou),asyncMode=current.room.effectiveMode==='async';const roles=['Question asker','Evidence finder','Connector','Summarizer'];
 async function submit(){setSaving(true);setError('');try{await request('reply',{code,target,response:reply});setReply('');setTarget('');if(discussion)setThread(await request(`room?code=${code}&stage=${threadStage}`));onChange();}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="live-squad"><span className="eyebrow"><Users size={16}/>{asyncMode?'ASYNCHRONOUS':'LIVE'} SQUAD {code}</span><h3>{discussion?'Build on a teammate’s idea':roles[((me?.ordinal||0)+current.room.stage)%4]}</h3><p>{asyncMode?'Save your own thinking first. Read and respond when teammates contribute. Your next step stays available.':'Think first, then give everyone following live a turn.'}</p>
 {discussion&&<Select value={threadStage} onValueChange={setThreadStage}><SelectTrigger aria-label="Discussion step"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="4">Application ideas</SelectItem><SelectItem value="5">Reflections</SelectItem></SelectContent></Select>}
 <div className="member-readiness">{current.members.map((m:any)=><span key={m.profile_id} className={m.ready?'ready':''}>{m.ready?<Check size={15}/>:<Clock size={15}/>} {m.name}<small>{m.cursor>=8?'Lesson finished':`Step ${m.cursor+1} of 8`}{m.pacing==='solo'?' · solo':m.pacing==='async'?' · at own pace':''}</small></span>)}</div>
 {error&&<p className="thread-error" role="alert">{error}</p>}
 {current.room.stage>=6?<p className="micro">Independent checks stay private. Visit your Squad’s application and reflection discussions after you finish.</p>:current.responses.length?<><h4>{asyncMode?'Ideas so far':current.allReady?'All voices are in.':'Your saved thinking'}</h4>{current.responses.map((r:any)=><div className="peer-contribution" key={r.id}><blockquote><strong>{current.members.find((m:any)=>m.profile_id===r.profile_id)?.name}</strong>{r.response}</blockquote>{current.replies?.filter((reply:any)=>reply.target_id===r.id).map((reply:any)=><div className="peer-reply" key={reply.id}><strong>{reply.name}</strong><p>{reply.response}</p></div>)}{r.profile_id!==me?.profile_id&&<button className="text-button" onClick={()=>{setTarget(r.id);setReply('')}}><MessageCircle size={14}/>Build on this idea</button>}{target===r.id&&<div className="reply-editor"><label htmlFor={`reply-${r.id}`}>What would you add, question, or revise?</label><Textarea id={`reply-${r.id}`} rows={3} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Your evidence made me think…"/><Button className="primary" onClick={submit} disabled={saving||reply.trim().length<10}>Save my response</Button></div>}</div>)}{asyncMode&&current.responses.length===1&&<p className="micro">You can keep learning. Teammates’ ideas will appear here after they contribute.</p>}</>:<p className="micro">Save your own contribution at this step to open the discussion.</p>}
 {!asyncMode&&current.allReady&&current.room.host&&<Button className="primary" onClick={advance} disabled={busy}>{current.room.stage===7?'Finish together':'We’re ready to continue'}<ArrowRight size={17}/></Button>}
 </div>
}
