'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,Download,Loader2,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {api} from './client-api';

export function YearPanel({learnerId,onContinue,onGradeChange}:{learnerId?:string;onContinue?:(id:string)=>void;onGradeChange?:()=>void|Promise<void>}){
  const [savedDay,setSavedDay]=useState<any>(null),[savedWork,setSavedWork]=useState<any>(null),[data,setData]=useState<any>(null),[year,setYear]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState(''),[outside,setOutside]=useState<any[]>([]),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState('');
  function accept(d:any){setData(d);setNotes(d.year?.review?.notes||'');setOutside(d.outside.map((s:any)=>d.year?.review?.outside?.find((r:any)=>r.id===s.id)||{id:s.id,resource:'',evidence:'',completed:false}));setConfirmed(false);}
  async function load(selected=year){const q=new URLSearchParams();if(learnerId)q.set('profile',learnerId);if(selected)q.set('year',selected);const d=await api((learnerId?'learner-year':'year')+'?'+q);accept(d);}
  useEffect(()=>{let gone=false;setData(null);setSavedDay(null);setSavedWork(null);setError('');const q=new URLSearchParams();if(learnerId)q.set('profile',learnerId);if(year)q.set('year',year);api((learnerId?'learner-year':'year')+'?'+q).then(d=>{if(!gone)accept(d)}).catch(e=>{if(!gone)setError(e.message)});return()=>{gone=true}},[learnerId,year]);
  async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function updateOutside(id:string,field:string,value:unknown){setOutside(rows=>rows.map(r=>r.id===id?{...r,[field]:value}:r));}
  return <section className="year-panel">
    <div className="section-heading"><h2>Your school year</h2><Button variant="ghost" disabled={busy} onClick={()=>run(()=>load())}><RotateCcw size={16}/>Refresh</Button></div>
    {error&&<p className="thread-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    {!data?!error&&<p><Loader2 className="spin"/>Opening the year…</p>:<>
      {data.years.length>1&&<Select value={year||data.year.id} onValueChange={setYear}><SelectTrigger aria-label="Saved learning year"><SelectValue/></SelectTrigger><SelectContent>{data.years.map((y:any)=><SelectItem key={y.id} value={y.id}>Grade {y.grade} · started {String(y.created_at).slice(0,10)}</SelectItem>)}</SelectContent></Select>}
      <div className="year-overview"><span className="eyebrow">GRADE {data.grade} · 36 WEEKS</span><h3>{data.reviewCurrent?'Year review saved':data.coreComplete?'Your core learning year is complete':`${data.completedDays} of 180 learning days complete`}</h3><Progress value={data.completedDays/180*100} aria-label="Completed learning days"/><p>{data.year?'Your place stays saved across breaks. The days follow your learning pace, with review at the end of each unit.':data.notice}</p></div>
      {!!data.pending.length&&<details className="year-pending" open={data.days.length===180&&!data.coreComplete}><summary>Unfinished work · {data.pending.length} activities</summary><p>Held lessons stay unfinished until a replacement is completed. They are never counted as learned or silently dropped.</p>{data.pending.slice(0,45).map((a:any)=><div className="year-task" key={a.id}><span><strong>Day {a.year_day} · {a.subject}</strong><small>{a.title} · {a.status==='held'?'needs review':a.status}</small></span>{onContinue&&<Button variant="outline" disabled={busy} onClick={()=>onContinue(a.id)}>Open<ArrowRight size={15}/></Button>}</div>)}{data.pending.length>45&&<p>Open a week below to find the other unfinished days.</p>}</details>}
      <div className="year-weeks" aria-label="All 36 learning weeks">{Array.from({length:36},(_,w)=>{const weekDays=data.days.filter((d:any)=>d.year_day>w*5&&d.year_day<=(w+1)*5),finished=weekDays.filter((d:any)=>d.status==='complete'&&d.completed===9).length;return <details key={w} className={finished===5?'finished':''}><summary>Week {w+1}<span>{finished===5?<Check size={16}/>:finished+'/5'}</span></summary>{Array.from({length:5},(_,i)=>{const n=w*5+i+1,d=weekDays.find((d:any)=>d.year_day===n),next=data.pending.find((a:any)=>a.year_day===n);return <div key={n}><strong>Day {n}</strong><small>{d?d.status==='complete'&&d.completed===9?'Complete':`${d.completed}/9 blocks complete`:'Coming up'}</small>{next&&onContinue?<Button variant="ghost" onClick={()=>onContinue(next.id)}>Continue<ArrowRight size={14}/></Button>:d&&<Button variant="ghost" disabled={busy} onClick={()=>run(async()=>{setSavedWork(null);setSavedDay(await api(learnerId?'learner-history-day?profile='+learnerId+'&id='+d.id:'history-day?id='+d.id));})}>View saved day</Button>}</div>})}</details>})}</div>
      {savedDay&&<section className="year-saved-day"><h3>Saved day {savedDay.day.year_day||savedDay.day.day_number}</h3>{savedDay.activities.map((a:any)=><div key={a.id} className="year-task"><span><strong>{a.subject}</strong><small>{a.title}</small></span><Button variant="outline" disabled={busy} onClick={()=>onContinue?onContinue(a.id):run(async()=>setSavedWork(await api('learner-activity?profile='+learnerId+'&id='+a.id)))}>View work</Button></div>)}</section>}
      {savedWork&&<section className="year-saved-work"><h3>{savedWork.activity.title}</h3>{savedWork.evidence.length?savedWork.evidence.map((e:any)=><article key={e.id}><strong>{e.stage>=6?'Independent check '+(e.stage-5):'Step '+(e.stage+1)}</strong><p>{e.response||('Selected option '+String.fromCharCode(65+(e.choice||0)))}</p>{e.correct!==null&&<small>{e.correct===1?'Correct on this response':'An idea to revisit'}</small>}</article>):<p>No submitted work is saved for this activity yet.</p>}</section>}
      <details className="year-map"><summary>What you’ll learn this year</summary><p>Every applicable target in the app’s core catalog has scheduled instruction. Completed lessons supply evidence; they do not establish full-standard mastery.</p>{['Literacy','Math','Science','Humanities','Studio'].map(subject=><section key={subject}><h3>{subject}</h3>{data.coverage.find((s:any)=>s.subject===subject)&&<p>{data.coverage.find((s:any)=>s.subject===subject).withEvidence} / {data.coverage.find((s:any)=>s.subject===subject).total} targets have completed lesson evidence.</p>}{data.units.filter((u:any)=>u.subject===subject).map((u:any)=><details key={u.id}><summary>Days {u.start}–{u.end} · {u.title}</summary><div className="year-targets">{u.targets.map((s:any)=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.id}</a>)}</div></details>)}</section>)}</details>
      <details className="year-outside" open={data.coreComplete&&!data.reviewCurrent}><summary>Complete the year with your adult</summary><p>These areas need instruction beyond the generated core. Keep the resources and actual work in your homeschool organizer throughout the year.</p><ul>{data.outside.map((s:any)=><li key={s.id}><strong>{s.label}</strong><p>{s.coverage}</p></li>)}</ul>{!learnerId&&<p>Your adult can review the full year in the Family workspace after you finish the core path.</p>}
        {learnerId&&data.coreComplete&&<form className="reading-form" onSubmit={e=>{e.preventDefault();run(async()=>{accept(await api('year-review',{profile:learnerId,year:data.year.id,notes,outside,adultConfirmed:confirmed}));setMessage('Your year review is saved.');})}}>{data.outside.map((s:any)=>{const row=outside.find(r=>r.id===s.id);return <fieldset key={s.id}><legend>{s.label}</legend><label>Instruction and resources used<Input required maxLength={1200} value={row?.resource||''} onChange={e=>updateOutside(s.id,'resource',e.target.value)}/></label><label>Evidence reviewed across the year<Textarea required minLength={20} maxLength={3000} value={row?.evidence||''} onChange={e=>updateOutside(s.id,'evidence',e.target.value)}/></label><label className="adult-check"><Checkbox checked={row?.completed===true} onCheckedChange={v=>updateOutside(s.id,'completed',v===true)}/>We completed and reviewed this course of study.</label></fieldset>})}<label>Year-end learning review<Textarea required minLength={20} maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What can the learner explain independently? What still needs support?"/></label><label className="adult-check"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>I reviewed the learner’s work and confirm this reflects the instruction provided.</label><Button className="primary" disabled={busy||!confirmed||outside.some(r=>!r.completed)}>Save adult year review</Button></form>}
      </details>
      {learnerId&&data.year&&<div className="year-actions"><Button variant="outline" disabled={busy} onClick={()=>run(async()=>{const report=await api('year-export?profile='+learnerId+'&year='+data.year.id);const url=URL.createObjectURL(new Blob([JSON.stringify({...report,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`schoolday-grade-${data.grade}-year-report.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}><Download size={17}/>Export year report</Button>{data.reviewCurrent&&data.grade<8&&data.years[0].id===data.year.id&&<Button className="primary" disabled={busy} onClick={()=>run(async()=>{const d=await api('advance-year',{profile:learnerId,year:data.year.id,adultConfirmed:true});setYear(d.year.id);accept(d);await onGradeChange?.();setMessage('The next grade is ready. Open the learner’s day when you want to begin.');})}>Start grade {data.grade+1}<ArrowRight size={17}/></Button>}</div>}
      <p className="micro">{data.notice}</p>
    </>}
  </section>;
}
