import type {Metadata} from 'next';
import {PolicyShell,BusinessContact} from '../policy-shell';
export const metadata:Metadata={title:'Subscription terms · Schoolday OS',alternates:{canonical:'https://schoolday-os.sickyicky.chatgpt.site/terms'}};
export default function Page(){return <PolicyShell title='Subscription terms'><p>These terms govern the Schoolday OS family subscription supplied by NovaPath LLC. The purchasing adult must be at least 18 and authorized to manage the learners added to the account. The <a href="/privacy">privacy policy</a> explains information handling.</p>
<h2>What you are buying</h2>
<p>Schoolday provides grades 6–8 learning software with generated core lessons, saved work and progress, and Solo or optional live/asynchronous Squad workflows. The family plan is a monthly software subscription. It does not include school enrollment, a live teacher, accreditation, a diploma, special education services or a determination that your family meets compulsory-education requirements. Review the <a href="/family-guide">family guide and subject coverage</a> and arrange required instruction and services separately.</p>
<h2>Price and automatic renewal</h2>
<p><strong>$29 USD per learner per month. Your subscription renews automatically each month until you cancel.</strong> One learner costs $29 per month; two cost $58. The selected learner quantity, total charge and any applicable taxes are shown before you confirm payment. There is no annual commitment or separate setup fee for the standard family plan.</p>
<p>By confirming a subscription purchase, you authorize NovaPath, through Stripe, to charge the displayed amount to your payment method at purchase and on each monthly renewal until cancellation. Review the next billing date in your billing portal. A free sample or launch-list signup does not start a subscription or authorize a charge. Any separately offered trial or promotion must state its own duration and subsequent price before enrollment.</p>
<h2>Cancel online</h2>
<p>Open <a href="/?adult=billing">your adult billing workspace</a>, open the Stripe billing portal, and choose cancellation. You can cancel online without a phone call. Cancellation stops the next renewal; access continues through the end of the paid billing period shown in the portal. Keep the cancellation confirmation. Cancel before the next renewal to avoid its charge.</p>
<p>If you cannot access cancellation, email <a href="mailto:Dan@explorenovapath.com?subject=Cancel%20Schoolday%20subscription">Dan@explorenovapath.com</a> from your account email. Include the account email and request cancellation; do not include card details. Deleting browser data, leaving a Squad, or ceasing to use lessons does not cancel a subscription. Cancellation and deletion of learning records are separate requests.</p>
<h2>Changing learner quantity and refunds</h2>
<p>Review any prorated charge or credit and the new recurring total before confirming a learner-quantity change in the billing portal. Reducing licenses can restrict generated access for learners beyond the new quantity. Contact support if you need help selecting the right quantity.</p>
<p>Cancellation does not automatically refund the current paid period. Contact support for billing errors, duplicate charges, or a refund request related to a service problem. We review requests individually and correct confirmed billing errors. This policy does not limit refunds or other remedies required by applicable law.</p>
<h2>Learning, availability and adult responsibilities</h2>
<p>AI-generated content and automated checks can make mistakes. Adults are responsible for reviewing learner understanding, addressing flagged material and arranging additional teaching or experiences. Completing a workflow does not guarantee mastery, grade promotion, a test result or legal school compliance. Curriculum references guide original generation; Schoolday is not endorsed by those publishers.</p>
<p>New lesson preparation depends on AI-provider availability, usage allowances and quality checks. It may pause for limits, outages or content review. The subscription is not an unlimited API service or a guarantee that every new lesson is instantly available. Families use the app’s configured provider and are not asked to obtain a separate API key for the standard family offer. Contact support if a failure materially prevents your paid use.</p>
<p>Use accounts only for authorized learners. Do not share adult credentials, submit others’ private information, harass Squad members, upload unlawful material, or attempt to bypass security or payment controls. Choose trusted Squad participants and supervise collaboration as appropriate. NovaPath may restrict access to address abuse, security threats, nonpayment or legal obligations; contact support to resolve an error.</p>
<h2>Your work and content rights</h2>
<p>You retain your rights in work you submit. You permit NovaPath and its service providers to store, process and display that work as needed to provide the service, including sharing you choose within a Squad. This does not authorize advertising use of learner work. Use Schoolday materials for your household’s learning; third-party source materials remain subject to their own licenses. AI output may not be unique.</p>
<h2>Notices and changes</h2>
<p>Billing acknowledgments, renewal information and required notices use the adult account contact. Keep that email current. Material subscription changes and any price change will be disclosed in advance as required by applicable law; a website edit alone is not permission for an undisclosed charge. You may cancel before a change takes effect. Current prepaid access will not be shortened solely by updating these terms.</p>
<h2>Questions and consumer rights</h2>
<p>Contact <a href="mailto:Dan@explorenovapath.com">Dan@explorenovapath.com</a> for subscriptions, refunds, accessibility, privacy or content concerns. These terms do not waive non-waivable consumer rights or require private arbitration. If a provision cannot be enforced, the remaining provisions continue to apply to the extent permitted by law.</p><h2>Business contact</h2><BusinessContact/></PolicyShell>}
