import {adultAllowed,lockAdult,setAdultPin} from './adult-lock';
import {headers,cookies} from 'next/headers';
import {z} from 'zod';
import {db,hash,HttpError,now,profile,runtime,uid} from './server';
export async function identity(){const h=await headers(),id=h.get('oai-authenticated-user-id'),email=h.get('oai-authenticated-user-email');return id&&email?{id,email:email.toLowerCase()}:null;}
export async function operator(){const h=await headers();return await adultAllowed()&&!!h.get('oai-authenticated-user-email')&&h.get('oai-authenticated-user-email')!.toLowerCase()===(runtime().APP_OWNER_EMAIL||(runtime().TEACHER_EMAILS||'').split(',')[0]).trim().toLowerCase();}
export async function requireOperator(){if(!await operator())throw new HttpError('App owner access required.',403);}
export async function account(required=true){if(!await adultAllowed()){if(required)throw new HttpError('Unlock your adult workspace first.',423);return null;}const who=await identity();if(!who){if(required)throw new HttpError('Sign in to open your adult workspace.',401);return null;}const a=await db().prepare('SELECT * FROM accounts WHERE id=?').bind(who.id).first();if(!a&&required)throw new HttpError('Set up your adult workspace first.',409);return a;}
export async function setupAccount(body:unknown){const who=await identity();if(!who)throw new HttpError('Sign in to open your adult workspace.',401);const b=z.object({name:z.string().trim().min(2).max(150),kind:z.enum(['family','organization']),adult:z.literal(true),pin:z.string().regex(/^\d{6}$/).optional()}).parse(body);if(!await adultAllowed())throw new HttpError('Unlock your adult workspace first.',423);const existing=await account(false);const live=JSON.parse(String((await db().prepare("SELECT value FROM settings WHERE id='billing_config'").first())?.value||'null'))?.mode==='live';if(live&&!b.pin&&!await db().prepare('SELECT account_id FROM adult_security WHERE account_id=?').bind(who.id).first())throw new HttpError('Set a six-digit adult PIN to finish your account.',409);if(existing&&existing.kind!==b.kind)throw new HttpError('Account type is fixed after setup. Contact the app owner to change it.');await db().prepare('INSERT INTO accounts(id,email,name,kind,created_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email').bind(who.id,who.email,b.name,b.kind,now()).run();const recovery=b.pin?await setAdultPin(b.pin):null;return {ok:true,recovery};}
export async function ownLearner(pid:string){const a=await account();const p=await db().prepare('SELECT p.id,p.name,p.grade FROM profiles p JOIN account_learners l ON l.profile_id=p.id WHERE l.account_id=? AND p.id=?').bind(a!.id,pid).first();if(!p)throw new HttpError('This learner is not in your workspace.',404);return p;}
export async function linkLearner(){const a=await account(),p=await profile();const old=await db().prepare('SELECT account_id FROM account_learners WHERE profile_id=?').bind(p.id).first();if(old&&old.account_id!==a!.id)throw new HttpError('This learner already belongs to another adult workspace.',409);await db().prepare('INSERT OR IGNORE INTO account_learners(profile_id,account_id,created_at) VALUES(?,?,?)').bind(p.id,a!.id,now()).run();return {ok:true};}
export async function learnerRoster(){const a=await account();return (await db().prepare("SELECT p.id,p.name,p.grade,s.mode,s.stage,s.title,s.paused,(SELECT count(*) FROM evidence e WHERE e.profile_id=p.id) AS evidence_count,(SELECT count(*) FROM activities x JOIN days d ON d.id=x.day_id WHERE d.profile_id=p.id AND x.status='complete') AS completed FROM profiles p JOIN account_learners l ON l.profile_id=p.id LEFT JOIN (SELECT ls.*,act.title FROM learning_state ls LEFT JOIN activities act ON act.id=ls.activity_id) s ON s.profile_id=p.id WHERE l.account_id=? ORDER BY l.created_at").bind(a!.id).all()).results;}
export async function selectLearner(body:unknown){const b=z.object({id:z.string().uuid()}).parse(body);const p=await ownLearner(b.id);const token=uid()+uid();await db().prepare('UPDATE profiles SET session=? WHERE id=?').bind(await hash(token),p.id).run();(await cookies()).set('schoolday_session',token,{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:60*60*24*365});await lockAdult();return {profile:p};}
export async function learnerWork(pid:string){await ownLearner(pid);return {evidence:(await db().prepare('SELECT e.*,a.title,a.subject,a.goal FROM evidence e JOIN activities a ON a.id=e.activity_id WHERE e.profile_id=? ORDER BY e.updated_at DESC LIMIT 500').bind(pid).all()).results};}
export async function attachCreatedLearner(pid:string){const a=await account(false);if(a)await db().prepare('INSERT INTO account_learners(profile_id,account_id,created_at) VALUES(?,?,?)').bind(pid,a.id,now()).run();}
