import {headers,cookies} from 'next/headers';
import {z} from 'zod';
import {db,hash,HttpError,seal} from './server';
async function user(){const id=(await headers()).get('oai-authenticated-user-id');if(!id)throw new HttpError('Sign in to your adult account first.',401);return id;}
async function pinHash(pin:string,salt:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},k,256);return Array.from(new Uint8Array(bits),b=>b.toString(16).padStart(2,'0')).join('');}
async function session(id:string,pinHash:string){(await cookies()).set('schoolday_adult',await seal(JSON.stringify({id,pinHash,until:Date.now()+1800000})),{httpOnly:true,secure:true,sameSite:'strict',path:'/',maxAge:1800});}
export async function adultAllowed(){const id=(await headers()).get('oai-authenticated-user-id');if(!id)return true;const row=await db().prepare('SELECT pin_hash FROM adult_security WHERE account_id=?').bind(id).first();if(!row)return true;const token=(await cookies()).get('schoolday_adult')?.value;if(!token)return false;try{const s=JSON.parse(await seal(token,true));return s.id===id&&s.pinHash===row.pin_hash&&s.until>Date.now()}catch{return false;}}
export async function setAdultPin(pin:string){const id=await user();if(!/^\d{6}$/.test(pin))throw new HttpError('Choose a six-digit adult PIN.');if(!await adultAllowed())throw new HttpError('Unlock your adult workspace first.',423);const salt=crypto.randomUUID(),digest=await pinHash(pin,salt),recovery=crypto.randomUUID().replace(/-/g,'').toUpperCase();await db().prepare('INSERT INTO adult_security(account_id,pin_hash,salt,recovery_hash,failed_attempts,blocked_until) VALUES(?,?,?,?,0,0) ON CONFLICT(account_id) DO UPDATE SET pin_hash=excluded.pin_hash,salt=excluded.salt,recovery_hash=excluded.recovery_hash,failed_attempts=0,blocked_until=0').bind(id,digest,salt,await hash(recovery)).run();await session(id,digest);return recovery;}
export async function unlockAdult(body:unknown){const b=z.object({pin:z.string().trim().min(6).max(40)}).strict().parse(body),id=await user();const row=await db().prepare('SELECT * FROM adult_security WHERE account_id=?').bind(id).first();if(!row)throw new HttpError('Set up your adult workspace first.',409);if(Number(row.blocked_until)>Date.now())throw new HttpError('Too many attempts. Try again in 15 minutes.',429);const recovery=b.pin.replace(/[\s-]/g,'').toUpperCase();const good=/^[A-F0-9]{32}$/.test(recovery)?await hash(recovery)===row.recovery_hash:/^\d{6}$/.test(b.pin)&&await pinHash(b.pin,String(row.salt))===row.pin_hash;if(!good){await db().prepare('UPDATE adult_security SET failed_attempts=CASE WHEN blocked_until>0 THEN 1 ELSE failed_attempts+1 END,blocked_until=CASE WHEN blocked_until=0 AND failed_attempts>=4 THEN ? ELSE 0 END WHERE account_id=?').bind(Date.now()+900000,id).run();throw new HttpError('That PIN or recovery code did not match.',403);}await db().prepare('UPDATE adult_security SET failed_attempts=0,blocked_until=0 WHERE account_id=?').bind(id).run();await session(id,String(row.pin_hash));return {ok:true};}
export async function lockAdult(){(await cookies()).set('schoolday_adult','',{httpOnly:true,secure:true,sameSite:'strict',path:'/',maxAge:0});return {ok:true};}
