import {standardsFor} from './standards';
import {z} from 'zod';
import {headers} from 'next/headers';
import {account,ownLearner} from './accounts';
import {activityFor,db,educator,HttpError,now,runtime,uid} from './server';
import {SUBJECTS} from './types';

export const preferenceSchema=z.object({textSize:z.enum(['standard','large']).default('standard'),focus:z.boolean().default(false),reducedMotion:z.boolean().default(false),speechRate:z.enum(['slow','normal']).default('normal'),instruction:z.enum(['standard','chunked']).default('standard')}).strict();
export async function preferences(pid:string){const r=await db().prepare('SELECT preferences FROM learner_preferences WHERE profile_id=?').bind(pid).first();return preferenceSchema.parse(JSON.parse(String(r?.preferences||'{}')));}
export async function savePreferences(pid:string,body:unknown){const p=preferenceSchema.parse(body);await db().prepare('INSERT INTO learner_preferences(profile_id,preferences,updated_at) VALUES(?,?,?) ON CONFLICT(profile_id) DO UPDATE SET preferences=excluded.preferences,updated_at=excluded.updated_at').bind(pid,JSON.stringify(p),now()).run();return {preferences:p};}
export async function generationSupport(pid:string){const p=await preferences(pid);return {instruction:p.instruction};}

export async function progress(pid:string){
 const days=(await db().prepare("SELECT d.id,d.day_number,d.theme,d.question,d.status,d.created_at,count(a.id) AS blocks,COALESCE(sum(a.status='complete'),0) AS completed FROM days d LEFT JOIN activities a ON a.day_id=d.id AND a.superseded_by IS NULL WHERE d.profile_id=? GROUP BY d.id ORDER BY d.day_number DESC LIMIT 60").bind(pid).all()).results;
 const totals=await db().prepare("SELECT count(*) AS responses,COALESCE(sum(stage>=6),0) AS checks,COALESCE(sum(stage>=6 AND correct=1),0) AS correct FROM evidence WHERE profile_id=?").bind(pid).first();
 const groups=(await db().prepare("SELECT a.subject,count(*) AS checks,COALESCE(sum(e.correct=1),0) AS correct FROM evidence e JOIN activities a ON a.id=e.activity_id WHERE e.profile_id=? AND e.stage>=6 GROUP BY a.subject").bind(pid).all()).results;
 const counts=(await db().prepare("SELECT a.subject,count(*) AS started,COALESCE(sum(a.status='complete'),0) AS completed FROM activities a JOIN days d ON d.id=a.day_id WHERE d.profile_id=? AND EXISTS(SELECT 1 FROM evidence e WHERE e.activity_id=a.id AND e.profile_id=?) GROUP BY a.subject").bind(pid,pid).all()).results;
 const revisit=(await db().prepare("SELECT a.id,a.title,a.subject,a.goal,a.status,d.day_number,count(*) AS checks,COALESCE(sum(e.correct=0),0) AS revisit FROM evidence e JOIN activities a ON a.id=e.activity_id JOIN days d ON d.id=a.day_id WHERE e.profile_id=? AND e.stage>=6 GROUP BY a.id HAVING sum(e.correct=0)>0 ORDER BY d.day_number DESC,a.position LIMIT 20").bind(pid).all()).results;
 const learner=await db().prepare('SELECT grade FROM profiles WHERE id=?').bind(pid).first();const coverage=(await db().prepare("SELECT a.subject,a.standard_id,count(*) AS planned,sum(a.status='complete') AS completed FROM activities a JOIN days d ON d.id=a.day_id WHERE d.profile_id=? AND a.standard_id IS NOT NULL GROUP BY a.subject,a.standard_id").bind(pid).all()).results;
 return {days,totals,coverage:SUBJECTS.map(subject=>({subject,available:standardsFor(Number(learner?.grade),subject).length,planned:coverage.filter(s=>s.subject===subject).length,withCompletedLessons:coverage.filter(s=>s.subject===subject&&Number(s.completed)>0).length})),standards:coverage.map(s=>({...s,url:standardsFor(Number(learner?.grade),String(s.subject)).find(t=>t.id===s.standard_id)?.url})),subjects:SUBJECTS.map(subject=>({subject,checks:0,correct:0,started:0,completed:0,...groups.find(g=>g.subject===subject),...counts.find(g=>g.subject===subject)})),revisit};
}
export async function adultProgress(pid:string){const learner=await ownLearner(pid);return {learner,...await progress(pid),preferences:await preferences(pid)};}
export async function historyDay(pid:string,id:string){const day=await db().prepare('SELECT id,day_number,year_day,theme,question,status,created_at FROM days WHERE id=? AND profile_id=?').bind(id,pid).first();if(!day)throw new HttpError('This learning day was not found.',404);const activities=(await db().prepare('SELECT id,title,subject,goal,status,minutes FROM activities WHERE day_id=? AND superseded_by IS NULL ORDER BY position').bind(id).all()).results;return {day,activities};}

async function supportAccess(){const a=await account(false),isTeacher=await educator();const email=isTeacher?(await headers()).get('oai-authenticated-user-email')!.toLowerCase():'';return {a,email};}
const assigned="(SELECT json_extract(s.data,'$.teacherEmail') FROM school_records s WHERE s.profile_id=h.profile_id AND s.kind='enrollment' ORDER BY s.rowid DESC LIMIT 1)";
const accessible=`(EXISTS(SELECT 1 FROM account_learners l WHERE l.profile_id=h.profile_id AND l.account_id=?) OR (?!='' AND ${assigned}=?))`;
export async function helpInbox(){const {a,email}=await supportAccess();if(!a&&!email)throw new HttpError('Sign in to your adult workspace first.',401);return {requests:(await db().prepare(`SELECT h.*,p.name,p.grade,a.title,a.subject FROM help_requests h JOIN profiles p ON p.id=h.profile_id JOIN activities a ON a.id=h.activity_id WHERE ${accessible} ORDER BY CASE h.status WHEN 'open' THEN 0 WHEN 'answered' THEN 1 ELSE 2 END,h.created_at DESC LIMIT 100`).bind(a?.id||'',email,email).all()).results};}
export async function learnerHelp(pid:string){const owner=await db().prepare('SELECT account_id FROM account_learners WHERE profile_id=?').bind(pid).first();const assigned=await db().prepare("SELECT data FROM school_records WHERE profile_id=? AND kind='enrollment' ORDER BY rowid DESC LIMIT 1").bind(pid).first();const teacherEmail=assigned?JSON.parse(String(assigned.data)).teacherEmail:'';const available=!!owner||!!teacherEmail&&(runtime().TEACHER_EMAILS||'').toLowerCase().split(',').map(s=>s.trim()).includes(teacherEmail);return {available,requests:(await db().prepare('SELECT h.id,h.activity_id,h.stage,h.question,h.response,h.responder,h.status,h.created_at,h.answered_at,a.title,a.subject FROM help_requests h JOIN activities a ON a.id=h.activity_id WHERE h.profile_id=? ORDER BY h.created_at DESC LIMIT 100').bind(pid).all()).results};}
export async function requestHelp(pid:string,body:unknown){const b=z.object({id:z.string().uuid(),stage:z.number().int().min(0).max(7),question:z.string().trim().min(5).max(2000)}).strict().parse(body);const a=await activityFor(b.id,pid);if(!['ready','complete'].includes(String(a.status)))throw new HttpError('Open a prepared activity before asking for help.',409);if(!(await learnerHelp(pid)).available)throw new HttpError('An adult needs to link your learner profile or assign your teacher before help requests can reach them.',409);const count=await db().prepare("SELECT count(*) AS n FROM help_requests WHERE profile_id=? AND status='open'").bind(pid).first();if(Number(count?.n)>=20)throw new HttpError('Your adult has your open questions. Check for replies before adding another.',429);const openKey=pid+':'+b.id+':'+b.stage,id=uid();const result=await db().prepare("INSERT OR IGNORE INTO help_requests(id,profile_id,activity_id,stage,question,status,open_key,created_at) VALUES(?,?,?,?,?,'open',?,?)").bind(id,pid,b.id,b.stage,b.question,openKey,now()).run();if(!result.meta.changes)throw new HttpError('A question for this step is already waiting for your adult. Your new text is still here.',409);return {id};}
export async function answerHelp(body:unknown){const b=z.object({id:z.string().uuid(),response:z.string().trim().min(5).max(4000)}).strict().parse(body);const {a,email}=await supportAccess();const h=await db().prepare(`SELECT h.id,h.profile_id FROM help_requests h WHERE h.id=? AND ${accessible}`).bind(b.id,a?.id||'',email,email).first();if(!h)throw new HttpError('Help request not found.',404);const linked=!!a&&!!await db().prepare('SELECT profile_id FROM account_learners WHERE profile_id=? AND account_id=?').bind(h.profile_id,a.id).first();const r=await db().prepare("UPDATE help_requests SET response=?,responder=?,status='answered',answered_at=?,open_key=NULL WHERE id=? AND status='open'").bind(b.response,linked?'Your adult':'Your teacher',now(),b.id).run();if(!r.meta.changes)throw new HttpError('This question already has a reply. Refresh to read it.',409);return {ok:true};}
export async function resolveHelp(pid:string,body:unknown){const b=z.object({id:z.string().uuid()}).strict().parse(body);const r=await db().prepare("UPDATE help_requests SET status='resolved' WHERE id=? AND profile_id=? AND status='answered'").bind(b.id,pid).run();if(!r.meta.changes)throw new HttpError('Read the reply to your own question before marking it helpful.',409);return {ok:true};}
