import type {Subject} from './types';
export const moduleVersion='curriculum-modules-2026-09-09-v2';
// Curated instructional summaries, not a mirror of publishers' lesson banks.
// Keep provider/version restrictions explicit when adding or replacing an adapter.
const guides:Record<Subject,{name:string;url:string;rights:string;routine:string;limits:string}>={
 Math:{name:'OUR / Illustrative Mathematics 6–8, 2017–2019 edition',url:'https://im.kendallhunt.com/MS/index.html',rights:'CC BY 4.0; Open Up Resources 2017–2019, Illustrative Mathematics adaptations 2019. https://creativecommons.org/licenses/by/4.0/',routine:'Begin with a concrete problem. Connect a representation to a worked strategy, compare approaches, make the mathematical relationship explicit, and assess a new application.',limits:'Use this explicitly licensed middle-school edition only. Do not infer permission for newer IM editions or third-party images. Original examples; no certification or endorsement claim.'},
 Science:{name:'OpenSciEd middle-school instructional model',url:'https://openscied.org/why-openscied/instructional-model/',rights:'Middle-school curriculum: CC BY 4.0, OpenSciEd. https://creativecommons.org/licenses/by/4.0/ License scope: https://openscied.org/knowledge/what-does-it-mean-that-these-units-are-licensed-as-cc-by-4-0/',routine:'Introduce an observable phenomenon and a question. Elicit an initial model, examine supplied evidence, identify what the model cannot yet explain, and revise it. Reconnect findings to the question and identify what to investigate next.',limits:'Middle-school reference only; no blanket permission for elementary, high-school, professional learning, videos, or third-party assets. Supply safe data-based alternatives; do not claim these replace required hands-on instruction.'},
 Literacy:{name:'Louisiana ELA Guidebooks — middle-school design reference',url:'https://doe.louisiana.gov/educators/instructional-support/ela-guidebooks',rights:'Louisiana Department of Education, ELA Guidebooks units: CC BY 4.0 as documented in A Closer Look (October 2022). https://creativecommons.org/licenses/by/4.0/',routine:'Build knowledge around a connected text set and a meaningful question. Read and reread grade-level passages, study vocabulary in context, collect textual evidence, and express understanding in a supported written response. Model the quality criteria before independent application.',limits:'Use the documented 2018–2022 open units or independently verified CC BY materials. Do not assume the 2024 edition or third-party books, passages and images share that license. Supply original or separately cleared texts. Maintain California standards; this adapter is not the full Guidebooks sequence.'},
 Humanities:{name:'Reading Like a Historian — Digital Inquiry Group, formerly SHEG',url:'https://www.inquirygroup.org/history-lessons',rights:'Pedagogical reference only; no commercial republication license assumed.',routine:'Ask a historical question. Identify author, date, audience and context for evidence; compare sources and their limitations; then support a qualified claim. Distinguish documents from modern summaries.',limits:'Use verified primary sources with their own rights or clearly labeled original summaries. Never fabricate documents or quotes. Do not copy DIG worksheets. The DBQ Project is a separate publisher.'},
 Studio:{name:'Louisiana ELA Guidebooks — writing design reference',url:'https://doe.louisiana.gov/educators/instructional-support/ela-guidebooks',rights:'Louisiana Department of Education, ELA Guidebooks units: CC BY 4.0 as documented in A Closer Look (October 2022). https://creativecommons.org/licenses/by/4.0/',routine:'Plan backward from an evidence-based writing task. Collect relevant evidence while reading, inspect an original model against clear criteria, plan and draft a response, revise the reasoning, and explain the revision. Include an independent transfer check.',limits:'Use original or separately cleared texts and examples. Unit licensing does not cover every anchor book or third-party passage. Preserve California grade-level writing standards and the assigned school-year target. No claim to implement the complete publisher sequence or a comprehensive arts course.'}
};
export function curriculumModule(grade:number,subject:string){
 if(![6,7,8].includes(grade)||!Object.prototype.hasOwnProperty.call(guides,subject))throw new Error('No curriculum module for this grade and subject.');
 return {version:moduleVersion,grade,subject,...guides[subject as Subject],structure:['notice','teach','model','practice','apply','reflect'],delivery:{solo:'All essential inputs are included. Complete your own response and compare with a supplied model; no partner required.',squad_live:'Think and respond individually first, compare reasoning with teammates, then revise your own work. Independent checks stay private.',squad_async:'Post your own reasoning before viewing peers. If nobody has posted, compare with the supplied model and continue without waiting.'},contract:'Keep objective, standard, examples, rubric and individual checks identical across delivery modes. Modules must stand alone with a prerequisite recap and all required source text/data. Refer to earlier work only optionally. Peer interaction must never be the only source of essential evidence.'};
}
export function moduleAttribution(module:ReturnType<typeof curriculumModule>){return {title:module.name,url:module.url,supports:'Instructional design reference. '+module.rights+' Schoolday supplies original generated tasks and adaptations; no publisher endorsement. '+module.limits};}
export function deliveryPrompt(squad:boolean,live:boolean){return squad?(live?'Think first. Share your reasoning, compare approaches, then submit your own work.':'Post your thinking first. Compare with teammates when available; otherwise use the worked model and keep going.'):'Work at your own pace. Use the worked model to check your reasoning; no partner is required.';}
