import {z} from 'zod';
import {account,ownLearner} from './accounts';
import {db,HttpError,now} from './server';
import {familyChecklist,familyGuideVersion,familySubjects,familySources} from './family-guide';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v,'Use a valid date.');
const year=z.string().regex(/^20\d{2}-20\d{2}$/).refine(v=>Number(v.slice(5))===Number(v.slice(0,4))+1,'Use consecutive school years.');
const setupSchema=z.object({schoolYear:year,pathway:z.enum(['exploring','private_home','enrolled_program']),schoolName:z.string().trim().max(150),recordReference:z.string().trim().max(300),instructor:z.string().trim().max(150),checks:z.array(z.enum(['pathway','affidavit','instruction','records','services'])).max(5),subjects:z.array(z.object({id:z.string().max(30),plan:z.string().trim().max(1200)}).strict()).max(10)}).strict();
async function owner(pid:string){const a=await account();if(a!.kind!=='family')throw new HttpError('Use a family workspace for these parent records.',403);const p=await ownLearner(pid);return {a:a!,p};}
export function currentSchoolYear(){const y=Number(now().slice(0,4))-(Number(now().slice(5,7))<7?1:0);return y+'-'+(y+1);}
export async function familyHome(pid:string,schoolYear=currentSchoolYear()){
 const {a,p}=await owner(pid);year.parse(schoolYear);
 const setup=await db().prepare('SELECT * FROM family_setups WHERE account_id=? AND profile_id=? AND school_year=?').bind(a.id,pid,schoolYear).first();
 const records=(await db().prepare('SELECT * FROM family_journal j WHERE account_id=? AND profile_id=? AND school_year=? AND revision=(SELECT MAX(revision) FROM family_journal WHERE account_id=j.account_id AND profile_id=j.profile_id AND school_date=j.school_date) ORDER BY school_date DESC').bind(a.id,pid,schoolYear).all()).results;
 const summary=await db().prepare("SELECT count(*) AS activities,sum(a.status='complete') AS completed,sum(a.status IN ('held','error')) AS needs_review FROM activities a JOIN days d ON d.id=a.day_id WHERE d.profile_id=? AND a.superseded_by IS NULL AND a.phase!='routine'").bind(pid).first();
 return {learner:p,schoolYear,version:familyGuideVersion,sources:familySources,checklist:familyChecklist,subjects:familySubjects(Number(p.grade)),setup:setup?JSON.parse(String(setup.data)):null,setupRevision:Number(setup?.revision||0),records:records.map(r=>({...r,data:JSON.parse(String(r.data))})),summary};
}
export async function saveFamilySetup(body:unknown){const b=z.object({profile:z.string().uuid(),revision:z.number().int().min(0),setup:setupSchema}).strict().parse(body);const {a,p}=await owner(b.profile);const expected=familySubjects(Number(p.grade)).map(s=>s.id);if(b.setup.subjects.length!==expected.length||new Set(b.setup.subjects.map(s=>s.id)).size!==expected.length||b.setup.subjects.some(s=>!expected.includes(s.id)))throw new HttpError('Include one plan for each area of study.',400);
 const r=b.revision===0?await db().prepare('INSERT INTO family_setups(account_id,profile_id,school_year,data,revision,updated_at) VALUES(?,?,?,?,1,?) ON CONFLICT DO NOTHING').bind(a.id,b.profile,b.setup.schoolYear,JSON.stringify(b.setup),now()).run():await db().prepare('UPDATE family_setups SET data=?,revision=revision+1,updated_at=? WHERE account_id=? AND profile_id=? AND school_year=? AND revision=?').bind(JSON.stringify(b.setup),now(),a.id,b.profile,b.setup.schoolYear,b.revision).run();
 if(!r.meta.changes)throw new HttpError('This plan changed in another window. Reload before saving.',409);
 return familyHome(b.profile,b.setup.schoolYear);
}
export async function saveFamilyJournal(body:unknown){const b=z.object({id:z.string().uuid(),profile:z.string().uuid(),schoolYear:year,date,revision:z.number().int().min(0),attendance:z.enum(['present','half_absent','absent','not_scheduled']),instruction:z.string().trim().max(6000),nextStep:z.string().trim().max(1500),adultConfirmed:z.literal(true)}).strict().parse(body);const {a}=await owner(b.profile);
 const localToday=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 if(b.date>localToday||b.date<b.schoolYear.slice(0,4)+'-07-01'||b.date>b.schoolYear.slice(5)+'-06-30')throw new HttpError('Choose a date in this school year that has already begun in California.',400);
 if(['present','half_absent'].includes(b.attendance)&&b.instruction.length<10)throw new HttpError('Describe the instruction or work you actually reviewed.',400);
 const data=JSON.stringify({attendance:b.attendance,instruction:b.instruction,nextStep:b.nextStep,adultConfirmed:true});
 const existing=await db().prepare('SELECT * FROM family_journal WHERE id=?').bind(b.id).first();if(existing){if(existing.account_id!==a.id||existing.profile_id!==b.profile||existing.school_date!==b.date||existing.data!==data)throw new HttpError('This save identifier was already used. Reload the record.',409);return {ok:true,revision:existing.revision};}
 const r=await db().prepare('INSERT INTO family_journal(id,account_id,profile_id,school_year,school_date,revision,data,actor,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE COALESCE((SELECT MAX(revision) FROM family_journal WHERE account_id=? AND profile_id=? AND school_date=?),0)=? ON CONFLICT DO NOTHING').bind(b.id,a.id,b.profile,b.schoolYear,b.date,b.revision+1,data,a.id,now(),a.id,b.profile,b.date,b.revision).run();if(!r.meta.changes)throw new HttpError('This date changed in another window. Reload before saving.',409);return {ok:true,revision:b.revision+1};
}
export async function familyExport(pid:string,schoolYear:string){const home=await familyHome(pid,schoolYear);const {a}=await owner(pid);const revisions=(await db().prepare('SELECT * FROM family_journal WHERE account_id=? AND profile_id=? AND school_year=? ORDER BY school_date,revision LIMIT 5001').bind(a.id,pid,schoolYear).all()).results;if(revisions.length>5000)throw new HttpError('This record is too large for one export. Contact the app owner.',409);const work=(await db().prepare('SELECT e.*,a.title,a.subject,a.standard_id,a.content_hash FROM evidence e JOIN activities a ON a.id=e.activity_id WHERE e.profile_id=? AND e.updated_at>=? AND e.updated_at<? ORDER BY e.updated_at LIMIT 10001').bind(pid,schoolYear.slice(0,4)+'-07-01',schoolYear.slice(5)+'-07-01').all()).results;if(work.length>10000)throw new HttpError('This work archive needs a larger export from the app owner.',409);return {...home,exportedAt:now(),notice:'Parent-maintained homeschool records and app work samples. Attendance is reported by the adult, never inferred from clicks, planned minutes, or scores. No school enrollment, legal certification, or mastery certification is issued.',revisions:revisions.map(r=>({...r,data:JSON.parse(String(r.data))})),work};}
