export const familyResources=[
 {slug:'middle-school-math-check-at-home',title:'A free middle-school math check to try at home',description:'Three short tasks with worked answers: grade 6 fractions, grade 7 rates and grade 8 linear relationships. See the reasoning, then try a lesson.',intro:'Use paper and pencil and let your learner explain each decision. Begin with the task for their grade, then try an earlier task if needed. This informal check is not a placement test or a diagnosis. A wrong answer is a starting point for a conversation.',sections:[
 {title:'Grade 6: how many servings?',body:'A jug contains 3/4 liter of juice. Each serving is 1/8 liter. How many servings can you pour? Before calculating, decide whether the answer should be greater or less than one.',items:['Worked answer: 3/4 = 6/8. Six pieces of size 1/8 fit inside 6/8, so there are 6 servings.','The calculation is (3/4) ÷ (1/8) = 6. Ask the learner to draw a whole divided into eighths and shade six parts.','If the learner multiplies the two fractions, return to the question: we are counting how many small servings fit in the jug.','Try a new case: 2/3 liter in servings of 1/6 liter. Answer: 4 servings, because 2/3 = 4/6.']},
 {title:'Grade 7: compare two rates',body:'One store sells 4 notebooks for $6. Another sells 6 notebooks for $8.40. Assume you can buy any number at the same per-notebook rate. Which is cheaper per notebook, and what would 10 cost at that store?',items:['Worked answer: $6 ÷ 4 = $1.50 per notebook. $8.40 ÷ 6 = $1.40 per notebook. The second store is cheaper.','Ten notebooks at the second store cost 10 × $1.40 = $14. Units matter: dollars divided by notebooks gives dollars per notebook.','Ask why comparing the package prices alone is misleading. The packages contain different quantities.','Try a new case: 3 notebooks cost $5.10. Answer: $1.70 each, so this offer is more expensive per notebook.']},
 {title:'Grade 8: a fee plus a rate',body:'A rental costs a $5 starting fee plus $3 for each hour. Write a rule for the total cost y after x hours. Find the cost at 4 hours. Is the relationship proportional?',items:['Worked answer: y = 3x + 5. At 4 hours, y = 3 × 4 + 5 = $17.','The relationship is linear but not proportional: at x = 0, the rule gives y = 5, not 0. The starting fee keeps the graph from passing through the origin.','Compare with y = 4x, a rental with no starting fee. Both cost $20 at 5 hours, because 3 × 5 + 5 = 4 × 5.','Ask the learner to explain which rental costs less at 2 hours and at 8 hours. Answers: y = 4x at 2 hours ($8 versus $11); y = 3x + 5 at 8 hours ($29 versus $32).']},
 {title:'Choose the next useful step',body:'Save one explanation and note the first step that needed help. A learner who can explain a correct answer may be ready to apply the idea elsewhere. If the reasoning is unclear, use a drawing, table or concrete example, then return to a new problem.',items:['Avoid assigning a grade or labeling ability from three questions.','Ask what changed after the worked example. This helps separate unfamiliar wording from a mathematical gap.','Try the free grade-level sample below to see a fuller sequence of explanation, practice and reflection. No account or card is required.']}
 ]},

 {slug:'middle-school-homeschool-schedule',title:'Build a middle-school homeschool routine',description:'A flexible sample routine for grades 6–8, with independent work, breaks and a short parent check-in.',intro:'Start with a sequence your learner can repeat. Choose a starting time that fits your household, keep the next task visible, and decide when an adult will be available for questions. The example below is a planning aid, not a required timetable.',sections:[
 {title:'A starting routine',body:'Try this order for a week, then adjust using the work your learner produces. These times describe the Schoolday app’s planned blocks; a learner may need more time, a shorter segment or additional instruction.',items:['Arrival and intention — 10 minutes. Name today’s question and gather paper and pencil.','Literacy and math — 40 minutes each. Pause after the worked example to explain the idea aloud.','Movement — 20 minutes. Step away from the screen and move comfortably.','Science — 40 minutes, followed by lunch and a screen break — 40 minutes.','Humanities and writing Studio — 40 minutes each. Save the explanation or draft, not just a completion check.','Reflection — 15 minutes. Identify one idea you can explain and one question to revisit.']},
 {title:'Make the adult check-in specific',body:'Ask your learner to show one piece of work and explain one decision. Look for the reasoning behind a correct answer and the point where an incorrect answer started to go wrong. A short conversation can tell you more than a row of finished activities.',items:['Before work: agree on what to do if a question feels confusing.','During work: use the explanation and model before asking for another answer.','After work: choose one question to bring into the next session.']},
 {title:'Adapt a day that gets interrupted',body:'Resume the saved activity instead of restarting the whole day. If an activity needs review, keep it on the unfinished list and use available prepared work. On days with appointments, separate the learning sequence into morning and afternoon sessions.',items:['Keep reading materials and drafts easy to find.','Plan time for subjects and experiences outside the app’s generated core.','Use your learner’s actual evidence and needs to adjust the plan; elapsed time alone does not show understanding.']}
 ]},
 {slug:'solo-and-asynchronous-homeschool',title:'Solo or a small learning Squad?',description:'Choose between independent, live small-group and asynchronous learning for a middle-school learner.',intro:'Collaboration works best when every learner has something to contribute. Begin with individual thinking, use conversation to compare ideas, and finish with a response that shows what each person understands.',sections:[
 {title:'Choose Solo when flexibility matters most',body:'Solo work fits changing schedules and learners who benefit from thinking before discussing. A useful independent lesson includes the reading or data, an explanation, a worked example and a way to apply the idea. It should not require someone else’s answer to continue.',items:['Ask the learner to explain the worked example in their own words.','Have a predictable way to reach an adult when the explanation is not enough.','Keep independent work connected to real conversations, reading and experiences.']},
 {title:'Choose a live Squad for shared discussion',body:'A live Squad works when learners can meet at the same time. In Schoolday, a small same-grade group can compare reasoning after contributing their own thinking. The adult should agree on a meeting time and how to help when someone gets stuck.',items:['Start with a question everyone can consider independently.','Compare methods and evidence; avoid having one learner do the work for everyone.','Finish with individual checks so a group answer does not conceal a gap.']},
 {title:'Choose asynchronous Squads for different schedules',body:'An asynchronous group leaves contributions for one another to read later. A learner should be able to continue using a supplied model if nobody has replied yet. Returning later to compare approaches can add value without turning a peer’s schedule into a barrier.',items:['Post your own reasoning before reading the group’s ideas.','Respond to the idea: explain what agrees, differs or needs evidence.','Keep essential tasks independently finishable; arrange any required interactive teaching separately.']}
 ]},
 {slug:'middle-school-curriculum-checklist',title:'A parent’s middle-school curriculum checklist',description:'Check teaching depth, subject coverage, saved evidence and family fit before choosing a grades 6–8 learning app.',intro:'A curriculum label is a starting point. Before choosing an app, look at what the learner reads, sees modeled, practices and explains. Try an actual lesson and inspect the evidence it creates.',sections:[
 {title:'Inspect a complete lesson',body:'A polished quiz is not a complete teaching sequence. Look for a clear objective, enough explanation to learn something new, a worked model that explains decisions, and practice that responds to misconceptions.',items:['Can the learner access every necessary passage, diagram and data table?','Does the independent task require using the idea in a new situation?','Can the adult see the learner’s explanation and identify what still needs teaching?']},
 {title:'Ask how the year is organized',body:'Look for a sequence that names the targets and makes unfinished learning visible. Schoolday maps 180 learning days across literacy, math, science, humanities and writing Studio. Its completion checks require evidence for each mapped subject lesson; they do not prove mastery or establish comprehensive school requirements.',items:['Ask which grade-level targets are included and how review is scheduled.','Check how missed or held lessons remain visible and can be revisited.','Plan separately for subjects, services and experiences outside the generated core.']},
 {title:'Check how generated content is handled',body:'AI review can miss errors. Schoolday uses source grounding, structural checks, separate accuracy, teaching and alignment reviews, and bounded revisions. A held lesson needs attention; it should not silently count as finished.',items:['Look for a way to report a problem without losing student work.','Ask what happens during a provider outage or spending-limit pause.','Treat live lesson quality and learner outcomes as things to evaluate, not as guarantees from an AI label.']},
 {title:'Try before setting up your family',body:'Schoolday provides one fixed, original math sample for each of grades 6, 7 and 8. It takes about ten minutes and needs no account or card. The sample demonstrates the workflow; it is not a full generated day. Check current access, pricing and policies before purchasing.',items:['Notice whether your learner understands what to do next.','Review the explanation together instead of checking only the final score.','Schoolday is parent-led learning software; buying it does not enroll a child in school.']}
 ]}
] as const;
