import {z} from 'zod';
const subject=z.enum(['Literacy','Math','Science','Humanities','Studio']);
const choice=z.object({text:z.string().min(1).max(800),feedback:z.string().min(10).max(1200)}).strict();
export const lessonSchema=z.object({alignment:z.object({standardId:z.string().min(3).max(80),evidence:z.string().min(40).max(2000)}).strict(),title:z.string().min(3).max(160),subject,grade:z.number().int().min(6).max(8),objective:z.string().min(15).max(600),prerequisite:z.string().min(5).max(600),materials:z.array(z.string().max(200)).max(10),stages:z.array(z.object({kind:z.enum(['notice','teach','model','practice','apply','reflect']),title:z.string().min(3).max(160),content:z.string().min(40).max(15000),prompt:z.string().min(10).max(2500),minutes:z.number().int().min(1).max(40),options:z.array(choice).max(5),answer:z.number().int().min(-1).max(4),hint:z.string().max(1500),rubric:z.array(z.string().max(600)).max(5),example:z.string().max(5000),visual:z.object({kind:z.enum(['none','fraction','numberline','bar']),values:z.array(z.number()).max(12),labels:z.array(z.string().max(100)).max(12),caption:z.string().max(500)}).strict()}).strict()).length(6),sources:z.array(z.object({title:z.string().min(2).max(300),url:z.string().url().max(1000),supports:z.string().min(10).max(1000)}).strict()).min(1).max(8),checks:z.array(z.object({question:z.string().min(10).max(2500),options:z.array(choice).min(3).max(4),answer:z.number().int().min(0).max(3)}).strict()).length(2)}).strict();
export const reviewSchema=z.object({solutions:z.array(z.object({item:z.enum(['practice','check1','check2']),answerIndex:z.number().int().min(0).max(4),reasoning:z.string().min(20).max(2000)}).strict()).max(3),role:z.string().max(100),pass:z.boolean(),issues:z.array(z.object({severity:z.enum(['blocker','major','minor']),location:z.string().max(200),problem:z.string().max(2000),repair:z.string().max(2000)}).strict()).max(20),summary:z.string().max(2000)}).strict();
export const planSchema=z.object({theme:z.string().min(3).max(160),question:z.string().min(10).max(500),items:z.array(z.object({standardId:z.string().min(3).max(80),subject,title:z.string().min(3).max(160),goal:z.string().min(15).max(600),prerequisite:z.string().min(5).max(600),minutes:z.number().int().min(15).max(90)}).strict()).length(5)}).strict();
// JSON Schema is deliberately separate from runtime bounds: the API constrains structure;
// Zod and semantic checks enforce the educational contract after parsing.
const str={type:'string'},num={type:'number'},int={type:'integer'};
const obj=(properties:Record<string,unknown>)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const arr=(items:unknown)=>({type:'array',items});
const c=obj({text:str,feedback:str});
export const lessonJSON=obj({alignment:obj({standardId:str,evidence:str}),title:str,subject:{type:'string',enum:['Literacy','Math','Science','Humanities','Studio']},grade:int,objective:str,prerequisite:str,materials:arr(str),stages:arr(obj({kind:{type:'string',enum:['notice','teach','model','practice','apply','reflect']},title:str,content:str,prompt:str,minutes:int,options:arr(c),answer:int,hint:str,rubric:arr(str),example:str,visual:obj({kind:{type:'string',enum:['none','fraction','numberline','bar']},values:arr(num),labels:arr(str),caption:str})})),sources:arr(obj({title:str,url:str,supports:str})),checks:arr(obj({question:str,options:arr(c),answer:int}))});
export const reviewJSON=obj({solutions:arr(obj({item:{type:'string',enum:['practice','check1','check2']},answerIndex:int,reasoning:str})),role:str,pass:{type:'boolean'},issues:arr(obj({severity:{type:'string',enum:['blocker','major','minor']},location:str,problem:str,repair:str})),summary:str});
export const planJSON=obj({theme:str,question:str,items:arr(obj({standardId:str,subject:{type:'string',enum:['Literacy','Math','Science','Humanities','Studio']},title:str,goal:str,prerequisite:str,minutes:int}))});
