import {validationSummary} from './launch-validation';
import {z} from 'zod';
import {requireOperator} from './accounts';
import {db,HttpError,now,putSetting,runtime,seal,setting} from './server';

export async function salesOpen(){if(await setting('sales_open')!=='true')return false;if(await setting('launch_policy')==='early-access-owner-approved')return (await launchReadiness()).canOpen;return true;}
async function launchReadiness(){
 const billing=JSON.parse(await setting('billing_config')||'null');
 const ai=!!(runtime().OPENAI_API_KEY||await setting('ai_key'));
 const webhook=!!(runtime().STRIPE_WEBHOOK_SECRET||await setting('stripe_webhook_secret'));
 const event=await db().prepare("SELECT created_at FROM payment_events WHERE status IN ('complete','ignored') AND livemode=? AND created_at>=? ORDER BY created_at DESC LIMIT 1").bind(billing?.mode==='live'?1:0,await setting('webhook_changed_at')||'').first();
 const validation=await validationSummary();
 const emailConfig=JSON.parse(await setting('email_config')||'null');
 const advisoryIds=new Set(['lessons','pilots','notices']);
 const checks=[{id:'notices',label:'Verified sender enabled for subscription notices',ready:!!emailConfig?.enabled&&!!await setting('email_key')},{id:'provider',label:'Responses, structured output, and source search tested',ready:validation.probeReady},{id:'lessons',label:'Human content reviews for all 15 grade / subject combinations',ready:validation.matrix.every(c=>c.approved)},{id:'pilots',label:'Observed completed pilot day in each grade',ready:validation.pilots.every(c=>c.approved)},{id:'ai',label:'AI credential configured',ready:ai},{id:'billing',label:'Verified live Stripe prices',ready:billing?.mode==='live'&&billing?.prices?.family?.amount===2900&&billing?.prices?.family?.interval==='month'&&billing?.prices?.family?.intervalCount===1},{id:'policies',label:'Privacy, subscription terms, and support contact',ready:!!billing?.privacyUrl&&!!billing?.termsUrl&&!!billing?.supportEmail},{id:'webhook',label:'Payment event signing secret saved',ready:webhook},{id:'event',label:'Live Stripe event delivery verified',ready:!!event}].map(c=>({...c,blocking:!advisoryIds.has(c.id),status:c.ready?'passed':advisoryIds.has(c.id)?'deferred':'required'}));
 return {canOpen:checks.every(c=>!c.blocking||c.ready),checks,};
}
export async function launchStatus(){await requireOperator();const readiness=await launchReadiness();const event=await db().prepare("SELECT created_at FROM payment_events WHERE status IN ('complete','ignored') AND livemode=1 ORDER BY created_at DESC LIMIT 1").first();return {salesOpen:await salesOpen(),...readiness,globalDailyLimit:Number(await setting('daily_limit')||200),learnerDailyLimit:Number(await setting('learner_daily_limit')||60),lastPaymentEvent:event?.created_at||null,pilotEmails:JSON.parse(await setting('pilot_emails')||'[]'),usage:(await db().prepare('SELECT day,calls FROM ai_usage ORDER BY day DESC LIMIT 7').all()).results,paymentErrors:(await db().prepare("SELECT id,type,error,created_at FROM payment_events WHERE status='error' ORDER BY created_at DESC LIMIT 10").all()).results};
}
export async function saveLaunch(body:unknown){await requireOperator();const b=z.object({salesOpen:z.boolean(),pilotEmails:z.array(z.string().trim().email().transform(s=>s.toLowerCase())).max(20).optional(),globalDailyLimit:z.number().int().min(26).max(100000),learnerDailyLimit:z.number().int().min(26).max(200)}).strict().parse(body);if(b.salesOpen&&!(await launchStatus()).canOpen)throw new HttpError('Finish the connection checks before opening live checkout.',409);await db().batch([db().prepare("INSERT INTO settings(id,value) VALUES('sales_open',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind(String(b.salesOpen)),db().prepare("INSERT INTO settings(id,value) VALUES('daily_limit',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind(String(b.globalDailyLimit)),db().prepare("INSERT INTO settings(id,value) VALUES('learner_daily_limit',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind(String(b.learnerDailyLimit))]);if(b.pilotEmails)await putSetting('pilot_emails',JSON.stringify([...new Set(b.pilotEmails)]));return launchStatus();}
export async function saveWebhookSecret(body:unknown){await requireOperator();const b=z.object({secret:z.string().regex(/^whsec_[A-Za-z0-9]+$/).min(20).max(300)}).strict().parse(body);await putSetting('stripe_webhook_secret',await seal(b.secret));await putSetting('webhook_changed_at',now());await putSetting('sales_open','false');return {ok:true};}
export async function reserveLearnerUsage(pid:string){const day=now().slice(0,10),limit=Number(await setting('learner_daily_limit')||60);await db().prepare('INSERT OR IGNORE INTO learner_usage(profile_id,day,calls) VALUES(?,?,0)').bind(pid,day).run();const r=await db().prepare('UPDATE learner_usage SET calls=calls+1 WHERE profile_id=? AND day=? AND calls<?').bind(pid,day,limit).run();if(!r.meta.changes)throw new HttpError('You have reached today’s lesson preparation allowance. Prepared lessons and saved work are still available. Try new preparation tomorrow.',429);}
