import {z} from 'zod';
import {aiCall,connection,generationFingerprint} from './ai';
import {requireOperator,identity} from './accounts';
import {assertReleased} from './release';
import {db,HttpError,now,putSetting,setting,uid} from './server';
const subjects=['Literacy','Math','Science','Humanities','Studio'];
export async function validationSummary(){const signature=await generationFingerprint();const probe=JSON.parse(await setting('ai_probe')||'null');const approved=(await db().prepare("SELECT r.*,coalesce(y.grade,p.grade) AS grade,a.subject FROM launch_reviews r JOIN activities a ON a.id=r.target_id JOIN days d ON d.id=a.day_id JOIN profiles p ON p.id=d.profile_id LEFT JOIN learning_years y ON y.id=d.learning_year_id WHERE r.kind='lesson' AND r.signature=? AND r.content_hash=a.content_hash AND a.generation_signature=? AND a.status IN ('ready','complete') AND a.superseded_by IS NULL").bind(signature,signature).all()).results;const matrix=[6,7,8].flatMap(grade=>subjects.map(subject=>({grade,subject,approved:approved.some(r=>r.grade===grade&&r.subject===subject)})));const pilots=(await db().prepare("SELECT r.*,coalesce(y.grade,p.grade) AS grade FROM launch_reviews r JOIN days d ON d.id=r.target_id JOIN profiles p ON p.id=d.profile_id LEFT JOIN learning_years y ON y.id=d.learning_year_id WHERE r.kind='day' AND r.signature=? AND d.status='complete' AND (SELECT count(*) FROM activities a WHERE a.day_id=d.id AND a.superseded_by IS NULL AND a.status='complete' AND a.generation_signature=?)=5").bind(signature,signature).all()).results;return {probeReady:!!probe&&probe.signature===signature,probeAt:probe?.signature===signature?probe.checkedAt:null,matrix,pilots:[6,7,8].map(grade=>({grade,approved:pilots.some(p=>p.grade===grade)})),signature};}
async function probeCall(label:string,instructions:string,input:string,schema?:unknown,web=false){try{return await aiCall(instructions,input,schema,web)}catch(e){if(e instanceof HttpError)throw new HttpError(label+': '+e.message,e.status);throw new HttpError(label+': The provider returned an unreadable response. Retry or contact support.',502)}}
export async function validateProvider(){await requireOperator();const lock=uid(),acquired=await db().prepare("INSERT INTO settings(id,value) VALUES('ai_probe_lock',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value WHERE CAST(substr(settings.value,1,13) AS INTEGER)<?").bind(String(Date.now()+180000)+lock,Date.now()).run();if(!acquired.meta.changes)throw new HttpError('A connection test is already running.',409);const lease=String((await setting('ai_probe_lock')));await putSetting('ai_probe','null');await putSetting('sales_open','false');try{const signature=await generationFingerprint();const schema={type:'object',properties:{answer:{type:'integer'}},required:['answer'],additionalProperties:false};const structured=await probeCall('Structured-output test','Compute the answer and return only the required JSON object.','What is 3 multiplied by 7?',schema);let result;try{result=JSON.parse(structured.text)}catch{throw new HttpError('The model did not return valid structured output.',502)}if(result.answer!==21||Object.keys(result).length!==1)throw new HttpError('The structured-output check failed.',502);const search=await probeCall('Source-search test','Use web search to find an official California Department of Education page about grade 6 mathematics standards. Cite the page. Do not use personal information.','Find the official source.',undefined,true);if(!search.urls.length)throw new HttpError('The source-search check returned no accepted citations.',502);if(signature!==await generationFingerprint())throw new HttpError('The connection changed during testing. Run the test again.',409);await putSetting('ai_probe',JSON.stringify({signature,checkedAt:now(),model:(await connection()).model}));return {ok:true};}finally{await db().prepare("DELETE FROM settings WHERE id='ai_probe_lock' AND value=?").bind(lease).run();}}
export async function validationDetails(){await requireOperator();const summary=await validationSummary();const lessons=(await db().prepare("SELECT a.id,a.title,a.subject,a.content_hash,coalesce(y.grade,p.grade) AS grade FROM activities a JOIN days d ON d.id=a.day_id JOIN profiles p ON p.id=d.profile_id LEFT JOIN learning_years y ON y.id=d.learning_year_id WHERE a.status IN ('ready','complete') AND a.generation_signature=? AND a.superseded_by IS NULL ORDER BY a.rowid DESC LIMIT 150").bind(summary.signature).all()).results;const days=(await db().prepare("SELECT d.id,d.day_number,coalesce(y.grade,p.grade) AS grade FROM days d JOIN profiles p ON p.id=d.profile_id LEFT JOIN learning_years y ON y.id=d.learning_year_id WHERE d.status='complete' AND (SELECT count(*) FROM activities a WHERE a.day_id=d.id AND a.superseded_by IS NULL AND a.status='complete' AND a.generation_signature=?)=5 ORDER BY d.created_at DESC LIMIT 30").bind(summary.signature).all()).results;const {signature,...safe}=summary;return {...safe,lessons,days};}
export async function inspectLaunchLesson(id:string){await requireOperator();const a=await db().prepare('SELECT * FROM activities WHERE id=?').bind(id).first();if(!a)throw new HttpError('Lesson not found.',404);await assertReleased(a);return {id:a.id,contentHash:a.content_hash,title:a.title,lesson:JSON.parse(String(a.payload)),standard:JSON.parse(String(a.standard_snapshot))};}
export async function approveLaunchReview(body:unknown){await requireOperator();const b=z.object({kind:z.enum(['lesson','day']),id:z.string().uuid(),contentHash:z.string().length(64).optional(),notes:z.string().trim().min(80).max(4000),confirmed:z.literal(true)}).strict().parse(body);const signature=await generationFingerprint();let fingerprint='';
 if(b.kind==='lesson'){const a=await db().prepare('SELECT * FROM activities WHERE id=?').bind(b.id).first();if(!a||a.superseded_by||a.generation_signature!==signature)throw new HttpError('Review a lesson made with the current connection and generation version.',409);await assertReleased(a);if(a.content_hash!==b.contentHash)throw new HttpError('The lesson changed. Open it and review the current text.',409);fingerprint=String(a.content_hash);}
 else{const d=await db().prepare("SELECT * FROM days WHERE id=? AND status='complete'").bind(b.id).first();if(!d)throw new HttpError('Finish a real pilot day before recording an observation.',409);const activities=(await db().prepare("SELECT * FROM activities WHERE day_id=? AND phase!='routine' AND superseded_by IS NULL").bind(b.id).all()).results;if(activities.length!==5||new Set(activities.map(a=>a.subject)).size!==5)throw new HttpError('The pilot needs all five generated subjects.',409);for(const a of activities){if(a.status!=='complete'||a.generation_signature!==signature)throw new HttpError('Complete every pilot lesson with the current generation version.',409);await assertReleased(a);const count=await db().prepare('SELECT count(*) AS n FROM evidence WHERE activity_id=? AND profile_id=?').bind(a.id,d.profile_id).first();if(count?.n!==8)throw new HttpError('The pilot is missing saved learning responses.',409);}fingerprint=activities.map(a=>a.content_hash).sort().join('|');}
 await db().prepare('INSERT INTO launch_reviews(id,kind,target_id,signature,content_hash,notes,actor,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(kind,target_id,signature) DO UPDATE SET content_hash=excluded.content_hash,notes=excluded.notes,actor=excluded.actor,created_at=excluded.created_at').bind(uid(),b.kind,b.id,signature,fingerprint,b.notes,(await identity())?.id||'operator',now()).run();return {ok:true};}
