import {pipelineConsent} from './pipeline-content';
import {suppressPipeline} from './pipeline';
import {z} from 'zod';
import {requireOperator} from './accounts';
import {db,hash,HttpError,now,runtime,uid} from './server';
import {emailConsent,startConfirmation} from './lead-email';
const consentVersion=emailConsent;
async function purge(){await db().batch([db().prepare("DELETE FROM lead_emails WHERE lead_id NOT IN (SELECT id FROM launch_leads WHERE created_at>=?)").bind(new Date(Date.now()-90*86400000).toISOString()),db().prepare("DELETE FROM launch_leads WHERE created_at < ?").bind(new Date(Date.now()-90*86400000).toISOString()),db().prepare('DELETE FROM lead_limits WHERE day < ?').bind(now().slice(0,10))]);}
export async function captureLead(body:unknown,req:Request){const b=z.object({email:z.string().trim().email().max(254).transform(v=>v.toLowerCase()),audience:z.enum(['family','educator']),adult:z.literal(true),consent:z.literal(true),website:z.string().max(200).default(''),followup:z.boolean().default(false),source:z.string().max(60).regex(/^[a-zA-Z0-9_-]*$/).default('direct')}).strict().parse(body);if(b.website)return {ok:true};await purge();const day=now().slice(0,10),ip=req.headers.get('cf-connecting-ip');const keys=['global',...(ip?[await hash((runtime().APP_SECRET||'')+day+ip)]:[])];for(const key of keys){await db().prepare('INSERT OR IGNORE INTO lead_limits(id,day,calls) VALUES(?,?,0)').bind(key,day).run();const r=await db().prepare('UPDATE lead_limits SET calls=calls+1 WHERE id=? AND day=? AND calls<?').bind(key,day,key==='global'?500:10).run();if(!r.meta.changes)throw new HttpError('Too many requests today. Please try again tomorrow.',429);}
const token=uid()+uid(),id=uid();const result=await db().prepare('INSERT OR IGNORE INTO launch_leads(id,email,audience,source,consent_version,delete_hash,created_at,pipeline_consent) VALUES(?,?,?,?,?,?,?,?)').bind(id,b.email,b.audience,b.source||'direct',consentVersion,await hash(token),now(),b.followup?pipelineConsent:null).run();let emailStatus="off";if(result.meta.changes){try{emailStatus=await startConfirmation(id,token)}catch{emailStatus="error";}}return {ok:true,emailStatus,removalToken:result.meta.changes?token:undefined};}
export async function removeLead(body:unknown){const b=z.object({token:z.string().min(64).max(80)}).strict().parse(body);const h=await hash(b.token);const lead=await db().prepare('SELECT id FROM launch_leads WHERE delete_hash=?').bind(h).first();await db().batch([db().prepare('DELETE FROM lead_emails WHERE lead_id IN (SELECT id FROM launch_leads WHERE delete_hash=?)').bind(h),db().prepare('DELETE FROM launch_leads WHERE delete_hash=?').bind(h)]);if(lead)await suppressPipeline(String(lead.id));return {ok:true};}
export async function listLeads(){await requireOperator();await purge();const rows=await db().prepare('SELECT id,email,audience,source,consent_version,confirmed_at,created_at FROM launch_leads ORDER BY created_at DESC LIMIT 1000').all();return {leads:rows.results};}
export async function deleteLead(body:unknown){await requireOperator();const b=z.object({id:z.string().uuid()}).strict().parse(body);await db().batch([db().prepare('DELETE FROM lead_emails WHERE lead_id=?').bind(b.id),db().prepare('DELETE FROM launch_leads WHERE id=?').bind(b.id)]);await suppressPipeline(b.id);return {ok:true};}
