import {assertReleased} from './release';
import {z} from 'zod';
import {studentLesson} from './quality';
import {activityFor,db,HttpError,now,uid} from './server';
export const modeSchema=z.enum(['solo','solo_async','squad_live','squad_async']);
export type LearningMode=z.infer<typeof modeSchema>;
export async function evidenceFor(pid:string,aid:string){return (await db().prepare('SELECT * FROM evidence WHERE profile_id=? AND activity_id=? ORDER BY stage').bind(pid,aid).all()).results;}
export function nextStage(work:Record<string,unknown>[]){let step=0;while(step<8&&work.some(e=>Number(e.stage)===step&&(step!==3||e.correct===1)))step++;return step;}
export async function saveState(pid:string,mode:LearningMode,aid:string|null,stage:number,roomCode:string|null,paused=false){await db().prepare('INSERT INTO learning_state(profile_id,mode,activity_id,stage,room_code,paused,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(profile_id) DO UPDATE SET mode=excluded.mode,activity_id=excluded.activity_id,stage=excluded.stage,room_code=excluded.room_code,paused=excluded.paused,updated_at=excluded.updated_at').bind(pid,mode,aid,stage,roomCode,paused?1:0,now()).run();}
export async function stateFor(pid:string){return db().prepare('SELECT s.*,a.title,a.subject FROM learning_state s LEFT JOIN activities a ON s.activity_id=a.id WHERE s.profile_id=?').bind(pid).first();}
export async function localActivity(pid:string,aid:string,code?:string){if(!code)return activityFor(aid,pid);const m=await db().prepare('SELECT m.assigned_activity_id,r.activity_id FROM members m JOIN rooms r ON m.room_code=r.code WHERE m.room_code=? AND m.profile_id=?').bind(code,pid).first();if(!m||(m.activity_id!==aid&&m.assigned_activity_id!==aid))throw new HttpError('This lesson is not part of your Squad.',403);return activityFor(String(m.assigned_activity_id||aid),pid);}
export async function getResume(pid:string,aid:string,code?:string){const a=await localActivity(pid,aid,code);if(a.payload&&['ready','complete'].includes(String(a.status)))await assertReleased(a);const work=await evidenceFor(pid,String(a.id));const cursor=a.payload?nextStage(work):(work.length?1:0);const draftRows=await db().prepare('SELECT * FROM drafts WHERE profile_id=? AND activity_id=? ORDER BY updated_at DESC').bind(pid,a.id).all();const {source_pack,lock_token,standard_snapshot,generation_signature,reviews,payload,...safe}=a;return {activityId:a.id,activity:{...safe,payload:['ready','complete'].includes(String(a.status))&&payload?JSON.stringify(studentLesson(JSON.parse(String(payload)))):null},cursor,evidence:work,drafts:draftRows.results};}
export async function saveDraft(pid:string,body:unknown){const b=z.object({id:z.string().uuid(),stage:z.number().int().min(0).max(7),response:z.string().max(15000),choice:z.number().int().min(0).max(4).nullable(),selfCheck:z.array(z.string().max(600)).max(5),version:z.number().int().min(0),room:z.string().length(6).optional(),mode:modeSchema.default('solo'),paused:z.boolean().default(false)}).parse(body);const a=await localActivity(pid,b.id,b.room);if(a.superseded_by||!['ready','complete'].includes(String(a.status)))throw new HttpError('This lesson changed. Your text is still on screen; reopen your day before continuing.',409);if(a.payload)await assertReleased(a);const work=await evidenceFor(pid,String(a.id));if(b.stage>nextStage(work))throw new HttpError('Complete the earlier steps before saving work here.',409);
 const result=b.version===0?await db().prepare('INSERT OR IGNORE INTO drafts(id,profile_id,activity_id,stage,response,choice,self_check,version,updated_at) VALUES(?,?,?,?,?,?,?,1,?)').bind(uid(),pid,a.id,b.stage,b.response,b.choice,JSON.stringify(b.selfCheck),now()).run():await db().prepare('UPDATE drafts SET response=?,choice=?,self_check=?,version=version+1,updated_at=? WHERE profile_id=? AND activity_id=? AND stage=? AND version=?').bind(b.response,b.choice,JSON.stringify(b.selfCheck),now(),pid,a.id,b.stage,b.version).run();
 if(!result.meta.changes)throw new HttpError('A newer draft is saved from another session. Your current text is still on this screen; copy it before reopening the saved step.',409);
 await saveState(pid,b.mode,String(a.id),b.stage,b.room||null,b.paused);return {version:b.version+1,savedAt:now(),activityId:a.id};}
export async function markComplete(pid:string,aid:string){const a=await activityFor(aid,pid);await db().prepare("UPDATE activities SET status='complete' WHERE id=?").bind(aid).run();await db().prepare("UPDATE days SET status='complete' WHERE id=? AND NOT EXISTS(SELECT 1 FROM activities WHERE day_id=? AND superseded_by IS NULL AND status!='complete')").bind(a.day_id,a.day_id).run();}
