export const pipelineOrigin='https://schoolday-os.sickyicky.chatgpt.site';
export const pipelineConsent='family-followup-2026-09-08';
export const pipelineVersion='family-pipeline-v1';
export const pipelineMessages=[
 {id:'sample',flow:'prospect',day:0,subject:'Start with one Schoolday lesson',body:'Start small: choose grade 6, 7, or 8 and try one original math sample. No account or payment is needed. The sample shows the learning steps; it is not a full generated school day.',label:'Choose a free sample',path:'/try'},
 {id:'routine',flow:'prospect',day:2,subject:'What would a Schoolday routine look like?',body:'A useful routine has a clear next activity and time for an adult to check in. Schoolday is designed around literacy, math, science, humanities, and writing projects, with breaks and movement. Learners can work independently or in a small Squad. Start with the sample and decide whether the steps fit your family.',label:'Explore the learning steps',path:'/try'},
 {id:'fit',flow:'prospect',day:4,subject:'Before you choose a homeschool app',body:'Schoolday is parent-led learning software. Purchasing it does not enroll a child in school or complete your family’s education requirements. Review subject coverage and parent responsibilities before choosing. The planned family price is $29 per learner per month; current availability and terms are shown in the app.',label:'Check fit and availability',path:'/join'},
 {id:'welcome',flow:'customer',day:0,subject:'Your next step in Schoolday',body:'Open your adult workspace to check your plan and continue your family setup. Choose the saved learner, then open their learning day. A parent stays involved for questions, review, and homeschool planning. Your current account and access status are always shown in the app.',label:'Continue family setup',path:'/join'},
 {id:'help',flow:'customer',day:2,subject:'A small start is enough',body:'If you have not started yet, open the saved learning day and begin with its first available activity. If you have already begun, pick up where you left off. Questions or a lesson that needs review? Use the help and reporting controls, or reply to this email for support.',label:'Open your workspace',path:'/join'},
 {id:'week',flow:'customer',day:7,subject:'How is Schoolday working for your family?',body:'Take a moment to review the saved work together. What was clear? Where was more help needed? Reply with feedback, keeping learner names and sensitive information out of email. If the sample would help another parent, you can share the public sample link. You can manage your subscription in Plan & billing.',label:'Review your family workspace',path:'/?adult=overview'}
] as const;
export function campaignSource(value:unknown){return typeof value==='string'?value.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,60)||'direct':'direct';}
export function campaignHref(path:string,source:unknown){const url=new URL(path,pipelineOrigin);const s=campaignSource(source);if(s!=='direct')url.searchParams.set('utm_source',s);return url.pathname+url.search;}
