import {z} from 'zod';
import {requireOperator} from './accounts';
import {db,hash,HttpError,now,putSetting,seal,setting,uid} from './server';
import {pipelineConsent,pipelineMessages,pipelineOrigin,pipelineVersion} from './pipeline-content';

type Sender={from:string;replyTo:string;company:string;address:string;revision:string;enabled:boolean;domainId:string};
type Config={revision:string;fingerprint:string;prepared:boolean;enabled:boolean;enabledAt:string|null;property:string;events:Record<string,string>;automations:Record<string,string>;templates:Record<string,string>};
const flows=['prospect','customer'] as const;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function sender():Promise<Sender|null>{return JSON.parse(await setting('email_config')||'null');}
async function config():Promise<Config|null>{return JSON.parse(await setting('pipeline_config')||'null');}
async function provider(path:string,method='GET',body?:unknown,allowMissing=false){
 const raw=await setting('email_key');if(!raw)throw new HttpError('Connect your verified Resend sender in Email follow-up first.',409);
 const headers={Authorization:'Bearer '+await seal(raw,true),'Content-Type':'application/json'};
 try{for(let attempt=0;attempt<2;attempt++){await new Promise(resolve=>setTimeout(resolve,125));const r=await fetch('https://api.resend.com'+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(12000)});if(allowMissing&&r.status===404)return null;if(r.status===429&&attempt===0){const seconds=Number(r.headers.get('retry-after')||'1');if(!Number.isFinite(seconds)||seconds>3)throw Error('Provider quota');await new Promise(resolve=>setTimeout(resolve,Math.max(250,seconds*1000)));continue;}if(!r.ok)throw Error('Provider rejection');return await r.json() as any;}throw Error('Provider unavailable');}
 catch{throw new HttpError('Resend could not complete pipeline setup or delivery. Check permissions and the provider log, then retry safe sync operations.',502);}
}
async function findResource(path:string,predicate:(r:any)=>boolean){let after='';for(let page=0;page<20;page++){const r=await provider(path+'?limit=100'+(after?'&after='+encodeURIComponent(after):''));if(!Array.isArray(r.data))throw new HttpError('Resend returned an unexpected resource list.',502);const matches=r.data.filter(predicate);if(matches.length>1)throw new HttpError('Duplicate pipeline resources need review in Resend.',409);if(matches[0])return matches[0];if(!r.has_more)return null;after=r.data.at(-1)?.id;if(!after)break;}throw new HttpError('Too many provider resources to safely identify this pipeline.',409);}
async function fingerprint(s:Sender){return hash(JSON.stringify({version:pipelineVersion,sender:s.revision,messages:pipelineMessages}));}
async function withLock<T>(name:string,fn:()=>Promise<T>){const token=uid();const r=await db().prepare('INSERT INTO pipeline_locks(id,token,expires_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET token=excluded.token,expires_at=excluded.expires_at WHERE pipeline_locks.expires_at<?').bind(name,token,Date.now()+600000,Date.now()).run();if(!r.meta.changes)throw new HttpError('This pipeline operation is already running. Try again shortly.',409);try{return await fn()}finally{await db().prepare('DELETE FROM pipeline_locks WHERE id=? AND token=?').bind(name,token).run();}}

export async function pipelineStatus(){await requireOperator();const s=await sender(),c=await config();const mode=JSON.parse(await setting('billing_config')||'null')?.mode||'pilot';const cutoff=new Date(Date.now()-90*86400000).toISOString();const rows=(await db().prepare(`SELECT l.source,count(*) leads,sum(l.confirmed_at IS NOT NULL) confirmed,
 sum(EXISTS(SELECT 1 FROM accounts a WHERE lower(a.email)=l.email AND a.kind='family')) accounts,
 sum(EXISTS(SELECT 1 FROM accounts a JOIN subscriptions s ON s.account_id=a.id WHERE lower(a.email)=l.email AND a.kind='family' AND s.plan='family' AND s.status='active' AND s.period_end>? AND ?='live')) subscribers,
 sum(EXISTS(SELECT 1 FROM accounts a JOIN account_learners al ON al.account_id=a.id JOIN days d ON d.profile_id=al.profile_id JOIN activities ac ON ac.day_id=d.id WHERE lower(a.email)=l.email AND a.kind='family' AND ac.payload IS NOT NULL AND ac.status='complete')) learning
 FROM launch_leads l WHERE l.created_at>=? AND l.audience='family' GROUP BY l.source ORDER BY leads DESC LIMIT 100`).bind(Date.now()/1000,mode,cutoff).all()).results;
 return {senderReady:!!s,sendingEnabled:!!s?.enabled,config:c,needsRefresh:!!s&&!!c&&c.fingerprint!==await fingerprint(s),mode,messages:pipelineMessages,consent:pipelineConsent,sources:rows,totals:rows.reduce((t:any,r:any)=>{for(const k of ['leads','confirmed','accounts','subscribers','learning'])t[k]+=Number(r[k]||0);return t},{leads:0,confirmed:0,accounts:0,subscribers:0,learning:0}),recent:(await db().prepare('SELECT lead_id,state,prospect_status,customer_status,error,updated_at FROM pipeline_contacts ORDER BY updated_at DESC LIMIT 20').all()).results};
}

export async function preparePipeline(){await requireOperator();return withLock('setup',async()=>{const s=await sender();if(!s)throw new HttpError('Connect your verified Resend sender first.',409);const old=await config();if(old?.enabled)throw new HttpError('Pause new sequences before preparing changes.',409);const fp=await fingerprint(s);if(old&&old.fingerprint!==fp)throw new HttpError('The existing pipeline uses a different sender or message version. Review and retire its running automations in Resend before migration.',409);
 const c:Config=old||{revision:s.revision,fingerprint:fp,prepared:false,enabled:false,enabledAt:null,property:'schoolday_'+fp.slice(0,12),events:{},automations:{},templates:{}};await putSetting('pipeline_config',JSON.stringify(c));
 const property=await findResource('/contact-properties',r=>r.key===c.property);if(property&&property.type!=='string')throw new HttpError('The pipeline contact property has an incompatible type.',409);if(!property)await provider('/contact-properties','POST',{key:c.property,type:'string',fallback_value:'suppressed'});
 for(const flow of flows){const name='schoolday.'+fp.slice(0,12)+'.'+flow;const event=await findResource('/events',r=>r.name===name);if(!event)await provider('/events','POST',{name});c.events[flow]=name;await putSetting('pipeline_config',JSON.stringify(c));}
 for(const m of pipelineMessages){const alias='schoolday-'+fp.slice(0,12)+'-'+m.id;let t=c.templates[m.id]?{id:c.templates[m.id]}:await provider('/templates/'+alias,'GET',undefined,true);if(!t){const url=pipelineOrigin+m.path;const html='<div style="font-family:Arial,sans-serif;color:#17101f;font-size:16px;line-height:1.6;max-width:560px;margin:auto;padding:24px"><p style="color:#4b167a;font-weight:bold">SCHOOLDAY</p><h1 style="font-size:24px">'+esc(m.subject)+'</h1><p>'+esc(m.body)+'</p><p><a href="'+esc(url)+'">'+esc(m.label)+'</a></p>'+(m.id==='fit'?'<p><a href="'+pipelineOrigin+'/family-guide">Read the family guide</a></p>':'')+(m.id==='week'?'<p><a href="'+pipelineOrigin+'/try?utm_source=family_referral">Share the free sample</a></p>':'')+'<hr><p style="font-size:14px">You requested Schoolday sample, launch, pricing, and getting-started emails.<br><a href="{{{RESEND_UNSUBSCRIBE_URL}}}">Unsubscribe from emails</a></p><p style="font-size:14px">'+esc(s.company)+'<br>'+esc(s.address)+'</p></div>';t=await provider('/templates','POST',{name:alias,alias,from:s.company.replace(/[<>\r\n]/g,'')+' <'+s.from+'>',subject:m.subject,reply_to:s.replyTo,html});}if(!t?.id)throw new HttpError('Resend did not return a template identifier.',502);c.templates[m.id]=t.id;await putSetting('pipeline_config',JSON.stringify(c));await provider('/templates/'+encodeURIComponent(t.id)+'/publish','POST',{});}
 for(const flow of flows){const name='Schoolday '+flow+' '+fp.slice(0,12);let existing=c.automations[flow]?{id:c.automations[flow]}:await findResource('/automations',r=>r.name===name);if(!existing){const steps:any[]=[{key:'start',type:'trigger',config:{event_name:c.events[flow]}}],connections:any[]=[];let previous='start',day=0;for(const m of pipelineMessages.filter(m=>m.flow===flow)){if(m.day>day){const wait='wait_'+m.id;steps.push({key:wait,type:'delay',config:{duration:(m.day-day)+' days'}});connections.push({from:previous,to:wait,type:'default'});previous=wait;}const gate='check_'+m.id;steps.push({key:gate,type:'condition',config:{type:'rule',field:'contact.properties.'+c.property,operator:'eq',value:flow}},{key:m.id,type:'send_email',config:{template:{id:c.templates[m.id]},from:s.company.replace(/[<>\r\n]/g,'')+' <'+s.from+'>',reply_to:s.replyTo,subject:m.subject}});connections.push({from:previous,to:gate,type:'default'},{from:gate,to:m.id,type:'condition_met'});previous=m.id;day=m.day;}existing=await provider('/automations','POST',{name,status:'disabled',steps,connections});}if(!existing?.id)throw new HttpError('Resend did not return an automation identifier.',502);c.automations[flow]=existing.id;await putSetting('pipeline_config',JSON.stringify(c));}
 c.prepared=true;await putSetting('pipeline_config',JSON.stringify(c));return pipelineStatus();});}

export async function switchPipeline(body:unknown){await requireOperator();const b=z.object({enabled:z.boolean(),reviewed:z.literal(true)}).strict().parse(body);return withLock('setup',async()=>{const c=await config(),s=await sender();if(!c?.prepared||!s||c.fingerprint!==await fingerprint(s))throw new HttpError('Prepare and review the current sender and messages first.',409);if(b.enabled&&!s.enabled)throw new HttpError('Enable confirmation emails in Email follow-up first.',409);if(b.enabled&&c.enabled)return pipelineStatus();c.enabled=false;await putSetting('pipeline_config',JSON.stringify(c));for(const flow of flows){if(b.enabled)await provider('/automations/'+c.automations[flow],'PATCH',{status:'enabled'});else await provider('/automations/'+c.automations[flow]+'/stop','POST',{});}c.enabled=b.enabled;if(b.enabled)c.enabledAt=now();await putSetting('pipeline_config',JSON.stringify(c));return pipelineStatus();});}

export async function enrollPipeline(leadId:string){const l=await db().prepare('SELECT * FROM launch_leads WHERE id=?').bind(leadId).first();if(!l?.confirmed_at||l.audience!=='family'||l.pipeline_consent!==pipelineConsent)return;const c=await config(),s=await sender();if(!c?.enabled||!s?.enabled||!c.enabledAt||String(l.confirmed_at)<c.enabledAt)return;await db().prepare("INSERT OR IGNORE INTO pipeline_contacts(lead_id,email_cipher,state,prospect_status,customer_status,revision,created_at,updated_at) VALUES(?,?,'prospect','pending','pending',?,?,?)").bind(leadId,await seal(String(l.email)),c.revision,now(),now()).run();await syncPipelineContact(leadId);}

async function syncPipelineContact(leadId:string){return withLock('contact:'+leadId,async()=>{const row=await db().prepare('SELECT * FROM pipeline_contacts WHERE lead_id=?').bind(leadId).first();const c=await config(),s=await sender();if(!row||!c||!s||c.revision!==s.revision||row.revision!==c.revision)return;const l=await db().prepare('SELECT * FROM launch_leads WHERE id=?').bind(leadId).first();const removed=row.state==='suppressed'||!l||!l.confirmed_at||l.pipeline_consent!==pipelineConsent||String(l.created_at)<new Date(Date.now()-90*86400000).toISOString();let stage='suppressed';
 try{const email=await seal(String(row.email_cipher),true);if(removed){const renewed=await db().prepare("SELECT l.id FROM launch_leads l JOIN pipeline_contacts p ON p.lead_id=l.id WHERE l.email=? AND l.id!=? AND l.confirmed_at IS NOT NULL AND l.pipeline_consent=? AND p.state!='suppressed'").bind(email,leadId,pipelineConsent).first();if(renewed){await db().prepare('DELETE FROM pipeline_contacts WHERE lead_id=?').bind(leadId).run();return;}}const mode=JSON.parse(await setting('billing_config')||'null')?.mode;const sub=await db().prepare("SELECT s.status,s.period_end FROM accounts a JOIN subscriptions s ON s.account_id=a.id WHERE lower(a.email)=? AND a.kind='family' AND s.plan='family' ORDER BY s.checked_at DESC LIMIT 1").bind(email).first();const live=mode==='live'&&sub?.status==='active'&&Number(sub.period_end)>Date.now()/1000;stage=removed?'suppressed':live?'customer':(row.customer_status!=='pending'||row.state==='customer'||row.state==='inactive')?'inactive':'prospect';await db().prepare('UPDATE pipeline_contacts SET state=?,updated_at=? WHERE lead_id=?').bind(stage,now(),leadId).run();
 if(!c.enabled||!s.enabled){if(stage!=='suppressed'&&stage!=='inactive'&&stage!=='customer')return;}
 let contact=await provider('/contacts/'+encodeURIComponent(String(row.contact_id||email)),'GET',undefined,true);if(!contact){if(stage==='suppressed'){await db().prepare('DELETE FROM pipeline_contacts WHERE lead_id=?').bind(leadId).run();return;}contact=await provider('/contacts','POST',{email,properties:{[c.property]:stage}});}else await provider('/contacts/'+encodeURIComponent(contact.id),'PATCH',{properties:{[c.property]:stage}});if(!contact?.id)throw Error('Missing contact');await db().prepare("UPDATE pipeline_contacts SET contact_id=?,error=CASE WHEN prospect_status IN ('sending','uncertain') OR customer_status IN ('sending','uncertain') THEN error ELSE NULL END,updated_at=? WHERE lead_id=?").bind(contact.id,now(),leadId).run();
 if(stage==='suppressed'){await db().prepare('DELETE FROM pipeline_contacts WHERE lead_id=?').bind(leadId).run();return;}if(contact.unsubscribed||!c.enabled||!s.enabled||!['prospect','customer'].includes(stage))return;
 const column=stage==='prospect'?'prospect_status':'customer_status';const claim=await db().prepare(`UPDATE pipeline_contacts SET ${column}='sending',updated_at=? WHERE lead_id=? AND ${column}='pending'`).bind(now(),leadId).run();if(!claim.meta.changes)return;
 try{await provider('/events/send','POST',{event:c.events[stage],contact_id:contact.id});await db().prepare(`UPDATE pipeline_contacts SET ${column}='accepted',error=NULL,updated_at=? WHERE lead_id=?`).bind(now(),leadId).run();}catch{await db().prepare(`UPDATE pipeline_contacts SET ${column}='uncertain',error='Sequence acceptance is uncertain. Check Resend runs; it will not be blindly restarted.',updated_at=? WHERE lead_id=?`).bind(now(),leadId).run();}
 }catch{await db().prepare("UPDATE pipeline_contacts SET error='Contact sync needs retry. Pending provider messages may still run until the state update is accepted.',updated_at=? WHERE lead_id=?").bind(now(),leadId).run();}
 });}

export async function syncPipelineForAccount(accountId:string,mode:string){if(mode!=='live')return;const ids=await db().prepare('SELECT p.lead_id FROM pipeline_contacts p JOIN launch_leads l ON l.id=p.lead_id JOIN accounts a ON lower(a.email)=l.email WHERE a.id=?').bind(accountId).all();for(const p of ids.results)try{await syncPipelineContact(String(p.lead_id))}catch{/* Billing state stays independent of email availability. */}}
export async function suppressPipeline(leadId:string){await db().prepare("UPDATE pipeline_contacts SET state='suppressed',updated_at=? WHERE lead_id=?").bind(now(),leadId).run();try{await syncPipelineContact(leadId)}catch{/* The retained encrypted contact allows the operator to retry removal. */}}
export async function retryPipeline(){await requireOperator();const rows=await db().prepare('SELECT lead_id FROM pipeline_contacts ORDER BY updated_at LIMIT 3').all();for(const row of rows.results)await syncPipelineContact(String(row.lead_id));return pipelineStatus();}
