import {z} from 'zod';
import {account,identity,ownLearner,requireOperator,setupAccount} from './accounts';
import {db,HttpError,now,uid} from './server';
export const noticeVersion='family-privacy-2026-09-09-v1';
export async function consentFor(accountId:string){return db().prepare('SELECT * FROM family_consents WHERE account_id=?').bind(accountId).first();}
export async function requireConsent(accountId:string,squads=false){const c=await consentFor(accountId);if(!c||c.version!==noticeVersion||c.status!=='verified'||squads&&c.squads!==1)throw new HttpError(squads?'Your adult needs to approve Squad sharing in Privacy controls.':'Your adult needs to complete parental consent in Privacy controls before learner setup or access.',403);}
export async function requireLearnerConsent(pid:string,squads=false){const link=await db().prepare('SELECT account_id FROM account_learners WHERE profile_id=?').bind(pid).first();if(!link)throw new HttpError('Ask your adult to finish learner setup.',403);await requireConsent(String(link.account_id),squads);}
export async function privacyHome(){const a=await account(false);return {account:a,identity:await identity(),version:noticeVersion,subscription:a?await db().prepare('SELECT status,quantity,cancel_at_end FROM subscriptions WHERE account_id=?').bind(a.id).first():null,consent:a?await consentFor(String(a.id)):null,learners:a?(await db().prepare('SELECT p.id,p.name,p.grade,l.expires_at FROM profiles p JOIN account_learners a ON a.profile_id=p.id LEFT JOIN learner_lifecycle l ON l.profile_id=p.id WHERE a.account_id=?').bind(a.id).all()).results:[]};}
export async function requestConsent(body:unknown){const b=z.object({name:z.string().trim().min(2).max(150),pin:z.string().regex(/^\d{6}$/).optional(),guardian:z.literal(true),notice:z.literal(true),squads:z.boolean()}).strict().parse(body);let a=await account(false);let recovery:string|null=null;if(!a){const r=await setupAccount({name:b.name,kind:'family',adult:true,pin:b.pin});recovery=r.recovery;a=await account();}if(a!.kind!=='family')throw new HttpError('School accounts require a separate documented authorization process.',409);const old=await consentFor(String(a!.id));if(old?.status==='verified'&&old.version===noticeVersion&&(!b.squads||old.squads===1)){await db().prepare('UPDATE family_consents SET squads=? WHERE account_id=?').bind(b.squads?1:0,a!.id).run();return {ok:true,recovery};}await db().prepare("INSERT INTO family_consents(account_id,version,status,squads,requested_at,verified_at,verified_by,method,reference) VALUES(?,?,'pending',?,?,NULL,NULL,NULL,NULL) ON CONFLICT(account_id) DO UPDATE SET version=excluded.version,status='pending',squads=excluded.squads,requested_at=excluded.requested_at,verified_at=NULL,verified_by=NULL,method=NULL,reference=NULL").bind(a!.id,noticeVersion,b.squads?1:0,now()).run();return {ok:true,recovery};}
export async function consentQueue(){await requireOperator();return {requests:(await db().prepare("SELECT c.*,a.email,a.name FROM family_consents c JOIN accounts a ON c.account_id=a.id WHERE c.status='pending' ORDER BY c.requested_at LIMIT 100").all()).results};}
export async function verifyConsent(body:unknown){await requireOperator();const b=z.object({accountId:z.string().min(1).max(200),method:z.enum(['signed_form','video_call']),reference:z.string().trim().min(12).max(500),confirmed:z.literal(true)}).strict().parse(body);const result=await db().prepare("UPDATE family_consents SET status='verified',verified_at=?,verified_by=?,method=?,reference=? WHERE account_id=? AND status='pending' AND version=?").bind(now(),(await identity())!.id,b.method,b.reference,b.accountId,noticeVersion).run();if(!result.meta.changes)throw new HttpError('This request changed. Reload the consent queue.',409);return {ok:true};}
export async function revokeConsent(){const a=await account();await db().batch([db().prepare("UPDATE family_consents SET status='revoked',squads=0 WHERE account_id=?").bind(a!.id),db().prepare("UPDATE profiles SET session=lower(hex(randomblob(32))) WHERE id IN (SELECT profile_id FROM account_learners WHERE account_id=?)").bind(a!.id),db().prepare('DELETE FROM device_codes WHERE profile_id IN (SELECT profile_id FROM account_learners WHERE account_id=?)').bind(a!.id)]);return {ok:true};}
const tables=['evidence','drafts','events','family_journal','family_setups','help_requests','learner_preferences','learning_state','learning_years','school_records'] as const;
export async function exportLearner(pid:string){const p=await ownLearner(pid);const out:Record<string,unknown>={learner:p,exportedAt:now()};for(const table of tables)out[table]=(await db().prepare('SELECT * FROM '+table+' WHERE profile_id=?').bind(pid).all()).results;out.days=(await db().prepare('SELECT * FROM days WHERE profile_id=?').bind(pid).all()).results;out.activities=(await db().prepare('SELECT a.* FROM activities a JOIN days d ON a.day_id=d.id WHERE d.profile_id=?').bind(pid).all()).results;out.discussion=(await db().prepare('SELECT * FROM room_responses WHERE profile_id=?').bind(pid).all()).results;out.replies=(await db().prepare('SELECT * FROM squad_replies WHERE profile_id=?').bind(pid).all()).results;return out;}
export async function deleteLearner(body:unknown){const b=z.object({id:z.string().uuid(),confirmation:z.literal('DELETE')}).strict().parse(body);await ownLearner(b.id);await db().prepare('DELETE FROM profiles WHERE id=?').bind(b.id).run();return {ok:true};}
export async function retentionSweep(){// Bounded maintenance on app requests; expired sessions are also denied synchronously.
 await db().prepare('DELETE FROM profiles WHERE id IN (SELECT profile_id FROM learner_lifecycle WHERE expires_at<? LIMIT 5)').bind(Date.now()).run();
}
export async function touchLearner(pid:string){const life=await db().prepare('SELECT expires_at FROM learner_lifecycle WHERE profile_id=?').bind(pid).first();if(life&&Number(life.expires_at)<=Date.now())throw new HttpError('This learner record has expired under the retention policy. Contact your adult.',403);await db().prepare('INSERT INTO learner_lifecycle(profile_id,expires_at) VALUES(?,?) ON CONFLICT(profile_id) DO UPDATE SET expires_at=excluded.expires_at WHERE learner_lifecycle.expires_at<?').bind(pid,Date.now()+365*86400000,Date.now()+364*86400000).run();}
