import {z} from 'zod';
import {headers} from 'next/headers';
import {activityFor,db,hash,HttpError,now,requireEducator,runtime,setting,uid} from './server';
import {evidenceFor} from './learning';
export const schoolSources=[
 {title:'CDE independent study requirements',url:'https://www.cde.ca.gov/sp/eo/is/legal.asp'},
 {title:'CDE independent study FAQs',url:'https://www.cde.ca.gov/sp/eo/is/faq.asp'},
 {title:'CDE instructional time table',url:'https://www.cde.ca.gov/fg/aa/pa/instructionaltimetable.asp'},
 {title:'California Education Code 51747',url:'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=EDC&sectionNum=51747.'},
 {title:'California pupil data contracts',url:'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=EDC&sectionNum=49073.1.'}
];
const ref=z.string().trim().max(1500).default('');
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Enter a real date.');
const optionalDate=z.union([date,z.literal('')]).default('');
export const configSchema=z.object({schoolName:z.string().trim().max(150).default(''),type:z.enum(['unselected','district','charter']).default('unselected'),cds:ref,year:z.string().max(40).default('2026–2027'),authorizationRef:ref,policyRef:ref,privacyRef:ref,attendanceRef:ref,supportRef:ref,curriculumRef:ref,calendarDates:z.array(date).max(240).default([]),grade6:z.string().max(4000).default(''),grade7:z.string().max(4000).default(''),grade8:z.string().max(4000).default('')}).strict().refine(c=>new Set(c.calendarDates).size===c.calendarDates.length,'Remove duplicate calendar dates.');
export async function schoolConfig(){return configSchema.parse(JSON.parse(await setting('school_config')||'{}'));}
async function actor(){await requireEducator();return (await headers()).get('oai-authenticated-user-email')!.toLowerCase();}
async function record(kind:string,pid:string|null,key:string,data:unknown,email:string){await db().prepare('INSERT INTO school_records(id,kind,profile_id,record_key,data,actor,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),kind,pid,key,JSON.stringify(data),email,now()).run();}
async function latest(kind:string,pid:string,key?:string){const r=await db().prepare('SELECT * FROM school_records WHERE kind=? AND profile_id=?'+(key?' AND record_key=?':'')+' ORDER BY rowid DESC LIMIT 1').bind(kind,pid,...(key?[key]:[])).first();return r?{...r,id:String(r.id),data:JSON.parse(String(r.data))}:null;}
async function pupil(pid:string){const p=await db().prepare('SELECT id,name,grade FROM profiles WHERE id=?').bind(pid).first();if(!p)throw new HttpError('Learner not found.',404);return p;}
export function readiness(c:z.infer<typeof configSchema>){const requiredDays=c.type==='charter'?175:c.type==='district'?180:null;const checks=[
 ['School of record',!!c.schoolName&&!!c.cds&&!!c.authorizationRef&&c.type!=='unselected'],
 ['Adopted independent study policies',!!c.policyRef],['Student data and AI vendor agreements',!!c.privacyRef],['School attendance accounting procedures',!!c.attendanceRef],['Student support, access and safeguarding arrangements',!!c.supportRef],['Approved curriculum and course access',!!c.curriculumRef&&!!c.grade6&&!!c.grade7&&!!c.grade8],['Instructional calendar',!!requiredDays&&c.calendarDates.length>=requiredDays]
 ];return {status:'Pilot · school authorization not verified',officialEnrollmentEnabled:false,officialAttendanceEnabled:false,requiredDays,annualMinutes:54000,calendarDays:c.calendarDates.length,planningMinutesPerDay:c.calendarDates.length?Math.ceil(54000/c.calendarDates.length):null,checks:checks.map(([label,present])=>({label,present})),notice:'Records support school review. They do not establish authorization, enrollment, funding eligibility, or legal compliance. School identity, family access, credentials, contracts, accessibility and attendance-system integration still require verification.'};}
export async function schoolAdmin(pid?:string){await requireEducator();const config=await schoolConfig();const learners=(await db().prepare('SELECT id,name,grade FROM profiles WHERE grade BETWEEN 6 AND 8 ORDER BY created_at DESC LIMIT 200').all()).results;let records:unknown[]=[],activities:unknown[]=[];if(pid){await pupil(pid);records=(await db().prepare('SELECT * FROM school_records WHERE profile_id=? ORDER BY rowid DESC LIMIT 250').bind(pid).all()).results.map(r=>({...r,data:JSON.parse(String(r.data))}));activities=(await db().prepare('SELECT a.id,a.title,a.subject,a.status,d.created_at,count(e.id) AS evidence_count FROM activities a JOIN days d ON a.day_id=d.id LEFT JOIN evidence e ON e.activity_id=a.id AND e.profile_id=d.profile_id WHERE d.profile_id=? GROUP BY a.id ORDER BY d.day_number DESC,a.position LIMIT 100').bind(pid).all()).results;}
return {config,readiness:readiness(config),learners,records,activities,sources:schoolSources,teacherEmails:(runtime().TEACHER_EMAILS||'').split(',').map(e=>e.trim().toLowerCase()).filter(Boolean)};}
export async function schoolStudent(pid:string){const c=await schoolConfig();const enrollment=await latest('enrollment',pid);const sessions=(await db().prepare("SELECT * FROM school_records WHERE profile_id=? AND kind='session' AND rowid IN (SELECT MAX(rowid) FROM school_records WHERE profile_id=? AND kind='session' GROUP BY record_key) ORDER BY created_at DESC").bind(pid,pid).all()).results.map(r=>({id:r.record_key,...JSON.parse(String(r.data))})).filter(s=>s.status!=='cancelled'&&s.startsAt>=now().slice(0,10)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).slice(0,10).map(({title,startsAt,minutes,kind,url,teacherName,status})=>({title,startsAt,minutes,kind,url,teacherName,status}));return {schoolName:c.schoolName,teacherName:enrollment?.data.teacherName||'',status:'Learning pilot',requirement:'Grades 6–8: daily live interaction and at least weekly teacher-led synchronous instruction for long-term independent study.',sessions};}
export async function saveSchool(body:unknown){const email=await actor();const b=z.object({config:configSchema}).parse(body);const data=JSON.stringify(b.config);await db().batch([db().prepare("INSERT INTO settings(id,value) VALUES('school_config',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind(data),db().prepare('INSERT INTO school_records(id,kind,profile_id,record_key,data,actor,created_at) VALUES(?,\'configuration\',NULL,\'school\',?,?,?)').bind(uid(),data,email,now())]);return {ok:true,readiness:readiness(b.config)};}
export async function saveSchoolRecord(body:unknown){const email=await actor();const base=z.object({kind:z.enum(['enrollment','session','work_review','reengagement']),profileId:z.string().uuid(),data:z.unknown()}).parse(body);await pupil(base.profileId);
 if(base.kind==='enrollment'){const b=z.object({studentRecordRef:ref,teacherName:z.string().trim().min(2).max(150),teacherEmail:z.string().email(),credentialRef:ref,agreementRef:ref,start:optionalDate,end:optionalDate,signedOn:optionalDate,allRequiredSignaturesVerified:z.boolean(),supportRef:ref}).strict().parse(base.data);if(!(runtime().TEACHER_EMAILS||'').toLowerCase().split(',').map(s=>s.trim()).includes(b.teacherEmail.toLowerCase()))throw new HttpError('Assign an educator with access to this app.');b.teacherEmail=b.teacherEmail.toLowerCase();if(b.start&&b.end&&b.end<b.start)throw new HttpError('Agreement end must follow its start.');if(b.allRequiredSignaturesVerified&&(!b.agreementRef||!b.signedOn||!b.start||!b.end||b.signedOn>b.start))throw new HttpError('For this long-term study workflow, record a completed agreement with all required signatures obtained before instruction starts.');await record(base.kind,base.profileId,base.profileId,b,email);return {ok:true};}
 const enrollment=await latest('enrollment',base.profileId);if(!enrollment?.data.teacherEmail)throw new HttpError('Assign a supervising teacher first.');if(enrollment.data.teacherEmail!==email)throw new HttpError('The assigned teacher must record instruction and personally review work.',403);
 if(base.kind==='session'){const b=z.object({id:z.string().uuid().optional(),kind:z.enum(['live_interaction','synchronous']),title:z.string().trim().min(3).max(200),startsAt:z.string().datetime(),minutes:z.number().int().min(1).max(240),url:z.union([z.string().url().refine(u=>new URL(u).protocol==='https:'),z.literal('')]),status:z.enum(['scheduled','participated','nonparticipatory','cancelled']),note:z.string().max(2000).default('')}).strict().parse(base.data);const id=b.id||uid();if(b.id&&!await latest('session',base.profileId,b.id))throw new HttpError('Session not found.',404);if(['participated','nonparticipatory'].includes(b.status)&&Date.parse(b.startsAt)>Date.now())throw new HttpError('Record participation after the session has occurred.');await record('session',base.profileId,id,{...b,teacherName:enrollment.data.teacherName,teacherEmail:email},email);return {ok:true};}
 if(base.kind==='work_review'){const b=z.object({activityId:z.string().uuid(),workDate:date,timeValueMinutes:z.number().int().min(0).max(600),progress:z.enum(['satisfactory','needs_support','insufficient_evidence']),note:z.string().trim().min(10).max(4000),personallyReviewed:z.literal(true)}).strict().parse(base.data);const a=await activityFor(b.activityId,base.profileId),evidence=await evidenceFor(base.profileId,b.activityId);if(!evidence.length)throw new HttpError('This activity has no submitted work to review.');if(!a.payload)throw new HttpError('Breaks and routine check-ins are not instructional work reviews.');if(b.workDate>now().slice(0,10))throw new HttpError('Work review date cannot be in the future.');const c=await schoolConfig();if(!c.calendarDates.includes(b.workDate))throw new HttpError('Choose a date in the configured instructional calendar.');const snapshot={activity:{id:a.id,title:a.title,subject:a.subject,goal:a.goal,payload:a.payload,reviews:a.reviews},evidence};const prior=await latest('work_review',base.profileId,b.activityId);await record('work_review',base.profileId,b.activityId,{...b,snapshot,snapshotHash:await hash(JSON.stringify(snapshot)),supersedes:prior?.id||null,attendanceStatus:'Pending school attendance review',eligibleADA:null},email);return {ok:true};}
 const b=z.object({note:z.string().trim().min(10).max(4000),nextAction:z.string().trim().min(5).max(1000),dueDate:date,contactRecordRef:ref}).strict().parse(base.data);await record('reengagement',base.profileId,uid(),b,email);return {ok:true};}
export async function schoolWork(pid:string,aid:string){await requireEducator();const a=await activityFor(aid,pid);return {activity:{id:a.id,title:a.title,subject:a.subject,payload:a.payload},evidence:await evidenceFor(pid,aid)};}
export async function schoolExport(pid:string){await requireEducator();const p=await pupil(pid);const c=await schoolConfig();const rows=(await db().prepare('SELECT * FROM school_records WHERE profile_id=? OR kind=\'configuration\' ORDER BY rowid').bind(pid).all()).results;return {exportedAt:now(),purpose:'School review support; not certified attendance, transcript, or enrollment.',learner:p,config:c,readiness:readiness(c),records:rows.map(r=>({...r,data:JSON.parse(String(r.data))})),sources:schoolSources};}
