import {env} from 'cloudflare:workers';
import {cookies,headers} from 'next/headers';
export function db(){if(!env.DB)throw new Error('Learning storage is temporarily unavailable. Please try again.');return env.DB;}
export function runtime(){return env as unknown as Record<string,string>;}
export async function educator(){const h=await headers();const email=h.get('oai-authenticated-user-email')?.toLowerCase();return !!email&&await (await import('./adult-lock')).adultAllowed()&&(runtime().TEACHER_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).includes(email);}
export async function requireEducator(){if(!await educator())throw new HttpError('Educator access required.',403);}
export class HttpError extends Error{constructor(message:string,public status=400){super(message);}}
export const uid=()=>crypto.randomUUID();
export const now=()=>new Date().toISOString();
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function profile(){const c=await cookies();const token=c.get('schoolday_session')?.value;if(!token)throw new HttpError('Start with your name and grade to save your work.',401);const p=await db().prepare('SELECT id,name,grade FROM profiles WHERE session=?').bind(await hash(token)).first();if(!p)throw new HttpError('Please start your learning profile again.',401);await (await import('./privacy-controls')).requireLearnerConsent(String(p.id));await (await import('./privacy-controls')).touchLearner(String(p.id));return p as {id:string;name:string;grade:number};}
export async function activityFor(id:string,pid:string){const a=await db().prepare('SELECT a.*,coalesce(y.grade,p.grade) AS lesson_grade FROM activities a JOIN days d ON a.day_id=d.id JOIN profiles p ON p.id=d.profile_id LEFT JOIN learning_years y ON y.id=d.learning_year_id WHERE a.id=? AND d.profile_id=?').bind(id,pid).first();if(!a)throw new HttpError('This lesson is not available in your school day.',404);return a;}
export async function jsonInput(req:Request){const raw=await req.text();if(raw.length>30000)throw new HttpError('That response is too long. Please shorten it.');try{return JSON.parse(raw);}catch{throw new HttpError('Please send a valid request.');}}
export async function route(fn:()=>Promise<unknown>){try{return Response.json(await fn(),{headers:{'Cache-Control':'no-store'}});}catch(e){const err=e as Error;const status=e instanceof HttpError?e.status:err.name==='ZodError'?400:500;if(status===500)console.error('Schoolday operation failed',err.name);return Response.json({error:status===500?'This step could not be completed. Your saved work is safe; please retry.':err.name==='ZodError'?'Please check the information you entered and try again.':err.message},{status,headers:{'Cache-Control':'no-store'}});}}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError('Invalid request origin.',403);}
export async function setting(key:string){const r=await db().prepare('SELECT value FROM settings WHERE id=?').bind(key).first();return r?.value as string|undefined;}
export async function putSetting(key:string,value:string){await db().prepare('INSERT INTO settings(id,value) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind(key,value).run();}
export async function seal(value:string,decrypt=false){const secret=runtime().APP_SECRET;if(!secret)throw new HttpError('The educator connection is not configured yet.',503);const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt']);if(decrypt){const bytes=Uint8Array.from(atob(value),c=>c.charCodeAt(0));return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.slice(0,12)},key,bytes.slice(12)));}const iv=crypto.getRandomValues(new Uint8Array(12));const data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value)));return btoa(String.fromCharCode(...iv,...data));}
