import {requireLearnerConsent} from './privacy-controls';
import {assertReleased} from './release';
import {z} from 'zod';
import {activityFor,db,HttpError,now,uid} from './server';
import {evidenceFor,markComplete,nextStage,saveState} from './learning';
import {studentLesson} from './quality';
type Learner={id:string;grade:number};
async function releaseOtherSquads(pid:string,code:string){await db().prepare("UPDATE members SET pacing='async' WHERE profile_id=? AND room_code!=? AND pacing='follow'").bind(pid,code).run();}
export async function squadMembership(code:string,pid:string){await requireLearnerConsent(pid,true);const m=await db().prepare('SELECT m.*,r.host,r.activity_id,r.stage,r.state,r.mode FROM members m JOIN rooms r ON m.room_code=r.code WHERE m.room_code=? AND m.profile_id=?').bind(code,pid).first();if(!m)throw new HttpError('Join this Squad to see its work.',403);return m;}
export const isAsync=(m:Record<string,unknown>)=>m.mode==='async'||m.pacing==='async'||m.pacing==='solo'||m.state==='complete';
export async function roomView(code:string,pid:string,requestedStage?:number){const me=await squadMembership(code,pid);const a=await db().prepare('SELECT * FROM activities WHERE id=?').bind(me.activity_id).first();const own=await activityFor(String(me.assigned_activity_id||me.activity_id),pid);if(!a||!["ready","complete"].includes(String(a.status))||!["ready","complete"].includes(String(own.status)))throw new HttpError('This shared lesson has been held for review.',409);
 await assertReleased(a);await assertReleased(own);const myWork=await evidenceFor(pid,String(own.id));const cursor=nextStage(myWork);const asynchronous=isAsync(me);const stage=asynchronous?(requestedStage===undefined?Math.min(cursor,7):requestedStage):Number(me.stage);if(!Number.isInteger(stage)||stage<0||stage>7||stage>cursor)throw new HttpError('Complete your earlier steps before opening this discussion.',409);
 const members=await db().prepare('SELECT m.profile_id,m.ordinal,m.pacing,m.assigned_activity_id,p.name FROM members m JOIN profiles p ON m.profile_id=p.id WHERE m.room_code=? ORDER BY m.ordinal').bind(code).all();
 const responses=(await db().prepare('SELECT id,profile_id,stage,response,choice FROM room_responses WHERE room_code=? AND stage=?').bind(code,stage).all()).results;
 const following=members.results.filter(m=>m.pacing==='follow');const allReady=following.length>0&&following.every(m=>responses.some(r=>r.profile_id===m.profile_id));const submitted=responses.some(r=>r.profile_id===pid);const visible=responses.filter(r=>r.profile_id===pid||(stage<6&&(asynchronous?submitted:allReady)));
 const allReplies=(await db().prepare('SELECT r.*,p.name FROM squad_replies r JOIN profiles p ON r.profile_id=p.id WHERE r.room_code=? ORDER BY r.created_at').bind(code).all()).results;
 const decorated=await Promise.all(members.results.map(async m=>({profile_id:m.profile_id,ordinal:m.ordinal,name:m.name,pacing:m.pacing,isYou:m.profile_id===pid,ready:responses.some(r=>r.profile_id===m.profile_id),cursor:nextStage(await evidenceFor(String(m.profile_id),String(m.assigned_activity_id||me.activity_id)))})));
 return {room:{code,activity_id:me.activity_id,assigned_activity_id:own.id,host:me.host===pid,mode:me.mode,effectiveMode:asynchronous?'async':'live',pacing:me.pacing,state:me.state,stage,cursor,complete:cursor>=8},lesson:studentLesson(JSON.parse(String(a.payload))),members:decorated,responses:visible,replies:allReplies.filter(r=>visible.some(v=>v.id===r.target_id)),allReady,submitted};
}
export async function listRooms(pid:string){const items=(await db().prepare('SELECT r.code,r.mode,r.state,r.stage,r.activity_id,m.assigned_activity_id,m.pacing,a.title,a.subject FROM members m JOIN rooms r ON m.room_code=r.code JOIN activities a ON r.activity_id=a.id WHERE m.profile_id=? ORDER BY r.created_at DESC LIMIT 30').bind(pid).all()).results;return Promise.all(items.map(async r=>{const progress=nextStage(await evidenceFor(pid,String(r.assigned_activity_id||r.activity_id)));const peers=(await db().prepare('SELECT id FROM room_responses WHERE room_code=? AND profile_id!=? AND stage IN (4,5)').bind(r.code,pid).all()).results;const replied=await db().prepare('SELECT id FROM squad_replies WHERE room_code=? AND profile_id=? LIMIT 1').bind(r.code,pid).first();return {...r,cursor:progress,peerTask:progress<6?'Learn and contribute':replied?'Peer response saved':peers.length?'A peer idea is ready':'Waiting for peer ideas'};}));}
export async function createRoom(p:Learner,body:unknown){await requireLearnerConsent(p.id,true);const b=z.object({id:z.string().uuid(),mode:z.enum(['live','async']).default('live')}).parse(body);const a=await activityFor(b.id,p.id);if(!a.payload||!["ready","complete"].includes(String(a.status)))throw new HttpError('Prepare a lesson before starting a Squad.');await assertReleased(a);if(!a.standard_id)throw new HttpError('Earlier pilot lessons cannot start new Squads until their standards are reviewed.',409);const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),b=>alphabet[b%alphabet.length]).join('');const start=nextStage(await evidenceFor(p.id,b.id));if(b.mode==='live'&&start>=8)throw new HttpError('You finished this lesson. Start an asynchronous discussion, or choose an unfinished lesson for live learning.');const existing=(await db().prepare('SELECT * FROM evidence WHERE profile_id=? AND activity_id=? AND stage<?').bind(p.id,b.id,start).all()).results;
 const inserts=[db().prepare('INSERT INTO rooms(code,host,activity_id,mode,stage,state,created_at) VALUES(?,?,?,?,?,?,?)').bind(code,p.id,b.id,b.mode,b.mode==='live'?Math.min(start,7):0,b.mode==='async'?'active':'lobby',now()),db().prepare("INSERT INTO members(id,room_code,profile_id,ordinal,assigned_activity_id,pacing) VALUES(?,?,?,0,?,'follow')").bind(uid(),code,p.id,b.id)];
 const l=JSON.parse(String(a.payload));for(const e of existing){const stage=Number(e.stage);const option=stage<6?l.stages[stage].options:l.checks[stage-6].options;inserts.push(db().prepare('INSERT INTO room_responses(id,room_code,profile_id,stage,response,choice) VALUES(?,?,?,?,?,?)').bind(uid(),code,p.id,stage,e.response||(e.choice!==null?option[Number(e.choice)]?.text||'Response saved':'Response saved'),e.choice));}await db().batch(inserts);await releaseOtherSquads(p.id,code);await saveState(p.id,b.mode==='async'?'squad_async':'squad_live',b.id,Math.min(start,7),code);return {code};}
export async function joinRoom(p:Learner,body:unknown){await requireLearnerConsent(p.id,true);const code=z.string().regex(/^[A-Z2-9]{6}$/).parse(String((body as {code?:string}).code||'').toUpperCase());const room=await db().prepare('SELECT r.*,coalesce(y.grade,p.grade) AS grade FROM rooms r JOIN profiles p ON r.host=p.id JOIN activities a ON a.id=r.activity_id JOIN days d ON d.id=a.day_id LEFT JOIN learning_years y ON y.id=d.learning_year_id WHERE r.code=?').bind(code).first();if(!room)throw new HttpError('No Squad has that code. Check the six characters.');const existing=await db().prepare('SELECT assigned_activity_id FROM members WHERE room_code=? AND profile_id=?').bind(code,p.id).first();if(existing)return {code};if(room.mode==='live'&&room.state!=='lobby')throw new HttpError('This live Squad has started. The starter can switch it to asynchronous so you can join.');if(room.grade!==p.grade)throw new HttpError('Choose a Squad working at your grade level.');
 const ownDay=await db().prepare("SELECT * FROM days WHERE profile_id=? AND status='ready' ORDER BY day_number DESC LIMIT 1").bind(p.id).first();if(!ownDay)throw new HttpError('Create your school day before joining a Squad.');const shared=await db().prepare('SELECT * FROM activities WHERE id=?').bind(room.activity_id).first();if(!shared||!["ready","complete"].includes(String(shared.status)))throw new HttpError('That lesson is not available for joining yet.');await assertReleased(shared);if(!shared.standard_id)throw new HttpError('This shared pilot lesson needs a standards review before new learners can join.',409);const own=await db().prepare("SELECT * FROM activities WHERE day_id=? AND subject=? AND superseded_by IS NULL AND status!='complete'").bind(ownDay.id,shared.subject).first();if(!own)throw new HttpError('You already finished this subject today. Join a Squad for another subject.');
 if(own.course_context&&own.standard_id!==shared.standard_id)throw new HttpError('This Squad is studying a different target. Start a Squad from your current lesson, or join when your targets match.',409);
 if(own.course_context){const assigned=JSON.parse(String(own.course_context)),offered=shared.course_context?JSON.parse(String(shared.course_context)):null;if(!offered||['version','unitId','stage','targetLesson'].some(key=>assigned[key]!==offered[key]))throw new HttpError('This Squad is on a different part of the unit. Start from your current lesson, or join a Squad at the same learning step.',409);}
 const work=await evidenceFor(p.id,String(own.id));const drafts=await db().prepare('SELECT id FROM drafts WHERE profile_id=? AND activity_id=? LIMIT 1').bind(p.id,own.id).first();if((work.length||drafts)&&own.payload!==shared.payload)throw new HttpError('Your existing work belongs to a different lesson. Start a Squad from that lesson to keep it together.');
 const insert=db().prepare("INSERT INTO members(id,room_code,profile_id,ordinal,assigned_activity_id) SELECT ?,?,?,count(*),? FROM members WHERE room_code=? HAVING count(*)<4 AND EXISTS(SELECT 1 FROM rooms WHERE code=? AND (mode='async' OR state='lobby'))").bind(uid(),code,p.id,own.id,code,code);
 const update=db().prepare("UPDATE activities SET title=?,goal=?,prerequisite=?,payload=?,status='ready',phase='ready',reviews=?,source_pack=?,standard_id=?,standard_snapshot=?,content_hash=?,generation_signature=?,minutes=?,generation_attempts=0,next_retry_at=0,locked_until=0,lock_token=NULL WHERE id=? AND EXISTS(SELECT 1 FROM members WHERE room_code=? AND profile_id=?) AND (payload=? OR (NOT EXISTS(SELECT 1 FROM evidence WHERE activity_id=activities.id) AND NOT EXISTS(SELECT 1 FROM drafts WHERE activity_id=activities.id)))").bind(shared.title,shared.goal,shared.prerequisite,shared.payload,shared.reviews,shared.source_pack,shared.standard_id,shared.standard_snapshot,shared.content_hash,shared.generation_signature,shared.minutes,own.id,code,p.id,shared.payload);
 const result=await db().batch([insert,update]);if(result[0].meta.changes&&!result[1].meta.changes){await db().prepare('DELETE FROM members WHERE room_code=? AND profile_id=?').bind(code,p.id).run();throw new HttpError('Your lesson changed while joining. Reopen your saved work and try again.',409);}if(!result[0].meta.changes)throw new HttpError('This Squad is full or has just started.');
 const lesson=JSON.parse(String(shared.payload));for(const e of work.filter(e=>Number(e.stage)<nextStage(work))){const step=Number(e.stage),options=step<6?lesson.stages[step].options:lesson.checks[step-6].options;await db().prepare('INSERT OR IGNORE INTO room_responses(id,room_code,profile_id,stage,response,choice) VALUES(?,?,?,?,?,?)').bind(uid(),code,p.id,step,e.response||(e.choice!==null?options[Number(e.choice)]?.text||'Response saved':'Response saved'),e.choice).run();}
 await releaseOtherSquads(p.id,code);await saveState(p.id,room.mode==='async'?'squad_async':'squad_live',String(own.id),Math.min(nextStage(work),7),code);return {code};}
export async function squadAction(p:Learner,body:unknown){const b=z.object({code:z.string().length(6),command:z.enum(['start','advance','set-mode','set-pacing']),mode:z.enum(['live','async']).optional(),pacing:z.enum(['follow','async','solo']).optional()}).parse(body);const me=await squadMembership(b.code,p.id);
 if(b.command==='set-pacing'){if(!b.pacing)throw new HttpError('Choose how you want to continue.');const cursor=nextStage(await evidenceFor(p.id,String(me.assigned_activity_id)));if(b.pacing==='follow'&&me.mode==='live'&&me.state==='active'&&cursor!==me.stage)throw new HttpError('You are on a different step. Choose asynchronous Squad mode to keep your place.');if(b.pacing!=='solo')await releaseOtherSquads(p.id,b.code);await db().prepare('UPDATE members SET pacing=? WHERE room_code=? AND profile_id=?').bind(b.pacing,b.code,p.id).run();await saveState(p.id,b.pacing==='solo'?'solo_async':b.pacing==='async'||me.mode==='async'?'squad_async':'squad_live',String(me.assigned_activity_id),Math.min(cursor,7),b.pacing==='solo'?null:b.code);return {ok:true};}
 if(me.host!==p.id)throw new HttpError('Only the Squad starter can change shared pacing.',403);
 const members=(await db().prepare("SELECT * FROM members WHERE room_code=? AND pacing='follow'").bind(b.code).all()).results;
 if(b.command==='set-mode'){
 if(!b.mode)throw new HttpError('Choose live or asynchronous.');let stage=Number(me.stage);if(b.mode==='live'){const cursors=await Promise.all(members.map(async m=>nextStage(await evidenceFor(String(m.profile_id),String(m.assigned_activity_id)))));if(cursors.length<2||new Set(cursors).size!==1||cursors[0]>=8)throw new HttpError('Live pacing needs at least two learners at the same unfinished step. Keep learning asynchronously for now.');stage=cursors[0];}
 await db().prepare("UPDATE rooms SET mode=?,stage=?,state='active' WHERE code=?").bind(b.mode,stage,b.code).run();return {ok:true};}
 if(me.mode==='async')throw new HttpError('Each learner moves independently in an asynchronous Squad.');
 if(b.command==='start'){if(members.length<2)throw new HttpError('Invite another learner, or choose asynchronous to start now.');const cursor=await Promise.all(members.map(async m=>nextStage(await evidenceFor(String(m.profile_id),String(m.assigned_activity_id)))));if(cursor.some(c=>c>=8)||new Set(cursor).size!==1)throw new HttpError('Learners are at different steps. Switch this Squad to asynchronous so everyone can keep their work.');await db().prepare("UPDATE rooms SET state='active',stage=? WHERE code=? AND state='lobby'").bind(Math.min(cursor[0],7),b.code).run();return {ok:true};}
 if(me.state!=='active')throw new HttpError('This Squad is not on an active step.',409);const responses=(await db().prepare('SELECT profile_id FROM room_responses WHERE room_code=? AND stage=?').bind(b.code,me.stage).all()).results;
 if(!members.length||!members.every(m=>responses.some(r=>r.profile_id===m.profile_id)))throw new HttpError('Give every learner following live time to respond.');
 if(me.stage===7){await db().prepare("UPDATE rooms SET state='complete' WHERE code=?").bind(b.code).run();for(const m of members)await markComplete(String(m.profile_id),String(m.assigned_activity_id));}
 else await db().prepare('UPDATE rooms SET stage=stage+1 WHERE code=? AND stage=?').bind(b.code,me.stage).run();return {ok:true};}
export async function postReply(pid:string,body:unknown){const b=z.object({code:z.string().length(6),target:z.string().uuid(),response:z.string().trim().min(10).max(4000)}).parse(body);await squadMembership(b.code,pid);const target=await db().prepare('SELECT * FROM room_responses WHERE id=? AND room_code=?').bind(b.target,b.code).first();if(!target||target.profile_id===pid||Number(target.stage)>=6)throw new HttpError('Reply to a teammate’s learning contribution, not an independent check.');const view=await roomView(b.code,pid,Number(target.stage));if(!view.responses.some(r=>r.id===b.target))throw new HttpError('Save your own thinking at this step before reading and replying.',409);await db().prepare('INSERT INTO squad_replies(id,room_code,profile_id,target_id,response,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(room_code,profile_id,target_id) DO UPDATE SET response=excluded.response,created_at=excluded.created_at').bind(uid(),b.code,pid,b.target,b.response,now()).run();return {ok:true};}
