import {z} from 'zod';
import {requireOperator} from './accounts';
import {billingConfig,connectBilling,stripe} from './billing';
import {db,hash,HttpError,uid} from './server';
const accountEmail='novapath711@gmail.com';
export async function setupLiveStripe(body:unknown,origin:string){await requireOperator();const b=z.object({key:z.string().regex(/^[sr]k_live_/).min(20).max(500),privacyUrl:z.string().url().refine(v=>new URL(v).protocol==='https:'),termsUrl:z.string().url().refine(v=>new URL(v).protocol==='https:'),supportEmail:z.string().email()}).strict().parse(body);
 const lease=String(Date.now()+180000)+uid();const acquired=await db().prepare("INSERT INTO settings(id,value) VALUES('stripe_setup_lock',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value WHERE CAST(substr(settings.value,1,13) AS INTEGER)<?").bind(lease,Date.now()).run();if(!acquired.meta.changes)throw new HttpError('Stripe setup is already running. Wait a moment, then check billing.',409);
 try{const owner=await stripe('account',undefined,b.key);if(String(owner.email||'').toLowerCase()!==accountEmail)throw new HttpError('This Stripe account does not identify itself as '+accountEmail+'. Use the intended account or verify its account email in Stripe.',409);if(owner.charges_enabled!==true)throw new HttpError('Stripe has not enabled live charges for this account. Finish its account requirements in Stripe first.',409);
 const previous=await billingConfig();if(previous&&(previous.accountId!==owner.id||previous.mode!=='live')&&await db().prepare('SELECT id FROM subscriptions LIMIT 1').first())throw new HttpError('Existing subscriptions require a migration before changing the Stripe account or mode.',409);
 let priceId=previous&&previous.accountId===owner.id&&previous.mode==='live'?previous.familyPrice:undefined;
 if(!priceId){const lookup='schoolday_family_29_month_'+(await hash(origin)).slice(0,16);const found=await stripe('prices?'+new URLSearchParams({'lookup_keys[]':lookup,limit:'2'}),undefined,b.key);if(!Array.isArray(found.data)||found.data.length>1)throw new HttpError('The family price lookup needs review in Stripe.',409);if(found.data.length)priceId=found.data[0].id;else{const price=await stripe('prices',{currency:'usd',unit_amount:'2900','recurring[interval]':'month','recurring[interval_count]':'1','recurring[usage_type]':'licensed',lookup_key:lookup,'product_data[name]':'Schoolday Family · Grades 6–8','product_data[metadata][schoolday_origin]':origin,'metadata[schoolday_plan]':'family'},b.key,'schoolday-family-price-'+await hash(owner.id+origin));priceId=price.id;}}
 if(typeof priceId!=='string'||!/^price_[A-Za-z0-9]+$/.test(priceId))throw new HttpError('Stripe did not return a usable family price.',502);
 const saved=await connectBilling({key:b.key,config:{mode:'live',familyPrice:priceId,...(previous&&previous.accountId===owner.id&&previous.mode==='live'&&previous.organizationPrice?{organizationPrice:previous.organizationPrice}:{}),privacyUrl:b.privacyUrl,termsUrl:b.termsUrl,supportEmail:b.supportEmail}},origin);return {...saved,accountEmail,chargesEnabled:true,payoutsEnabled:owner.payouts_enabled===true};
 }finally{await db().prepare("DELETE FROM settings WHERE id='stripe_setup_lock' AND value=?").bind(lease).run();}
}
