import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),session:text('session').notNull(),name:text('name').notNull(),grade:integer('grade').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('profiles_session').on(t.session)]);
export const days=sqliteTable('days',{learningYearId:text('learning_year_id'),yearDay:integer('year_day'),lockToken:text('lock_token'),id:text('id').primaryKey(),profileId:text('profile_id').notNull(),dayNumber:integer('day_number').notNull(),theme:text('theme').notNull(),question:text('question').notNull(),status:text('status').notNull(),lockedUntil:integer('locked_until').notNull().default(0),error:text('error'),createdAt:text('created_at').notNull()},t=>[index('days_profile').on(t.profileId),uniqueIndex('days_number').on(t.profileId,t.dayNumber),uniqueIndex('days_year_position').on(t.learningYearId,t.yearDay)]);
export const activities=sqliteTable('activities',{lessonKey:text('lesson_key'),courseContext:text('course_context'),generationSignature:text('generation_signature'),supersededBy:text('superseded_by'),standardId:text('standard_id'),standardSnapshot:text('standard_snapshot'),contentHash:text('content_hash'),generationAttempts:integer('generation_attempts').notNull().default(0),nextRetryAt:integer('next_retry_at').notNull().default(0),id:text('id').primaryKey(),dayId:text('day_id').notNull(),subject:text('subject').notNull(),title:text('title').notNull(),goal:text('goal').notNull(),prerequisite:text('prerequisite').notNull(),minutes:integer('minutes').notNull(),position:integer('position').notNull(),status:text('status').notNull().default('queued'),phase:text('phase').notNull().default('research'),revision:integer('revision').notNull().default(0),payload:text('payload'),sourcePack:text('source_pack'),reviews:text('reviews').notNull().default('[]'),error:text('error'),lockedUntil:integer('locked_until').notNull().default(0),lockToken:text('lock_token')},t=>[index('activities_day').on(t.dayId)]);
export const evidence=sqliteTable('evidence',{id:text('id').primaryKey(),profileId:text('profile_id').notNull(),activityId:text('activity_id').notNull(),stage:integer('stage').notNull(),response:text('response').notNull(),choice:integer('choice'),correct:integer('correct'),selfCheck:text('self_check').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('evidence_step').on(t.profileId,t.activityId,t.stage)]);
export const settings=sqliteTable('settings',{id:text('id').primaryKey(),value:text('value').notNull()});
export const rooms=sqliteTable('rooms',{code:text('code').primaryKey(),host:text('host').notNull(),activityId:text('activity_id').notNull(),stage:integer('stage').notNull().default(0),state:text('state').notNull().default('lobby'),mode:text('mode').notNull().default('live'),createdAt:text('created_at').notNull()});
export const members=sqliteTable('members',{id:text('id').primaryKey(),roomCode:text('room_code').notNull(),profileId:text('profile_id').notNull(),ordinal:integer('ordinal').notNull(),assignedActivityId:text('assigned_activity_id'),pacing:text('pacing').notNull().default('follow')},t=>[uniqueIndex('member_room_profile').on(t.roomCode,t.profileId)]);
export const roomResponses=sqliteTable('room_responses',{id:text('id').primaryKey(),roomCode:text('room_code').notNull(),profileId:text('profile_id').notNull(),stage:integer('stage').notNull(),response:text('response').notNull(),choice:integer('choice')},t=>[uniqueIndex('room_response_stage').on(t.roomCode,t.profileId,t.stage)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),profileId:text('profile_id').notNull(),kind:text('kind').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('events_profile').on(t.profileId)]);

export const aiUsage=sqliteTable('ai_usage',{day:text('day').primaryKey(),calls:integer('calls').notNull().default(0)});

export const learningState=sqliteTable('learning_state',{profileId:text('profile_id').primaryKey(),mode:text('mode').notNull().default('solo'),activityId:text('activity_id'),stage:integer('stage').notNull().default(0),roomCode:text('room_code'),paused:integer('paused').notNull().default(0),updatedAt:text('updated_at').notNull()});
export const drafts=sqliteTable('drafts',{id:text('id').primaryKey(),profileId:text('profile_id').notNull(),activityId:text('activity_id').notNull(),stage:integer('stage').notNull(),response:text('response').notNull().default(''),choice:integer('choice'),selfCheck:text('self_check').notNull().default('[]'),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('draft_step').on(t.profileId,t.activityId,t.stage)]);
export const squadReplies=sqliteTable('squad_replies',{id:text('id').primaryKey(),roomCode:text('room_code').notNull(),profileId:text('profile_id').notNull(),targetId:text('target_id').notNull(),response:text('response').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('squad_reply_target').on(t.roomCode,t.profileId,t.targetId),index('squad_replies_room').on(t.roomCode)]);
export const schoolRecords=sqliteTable('school_records',{id:text('id').primaryKey(),kind:text('kind').notNull(),profileId:text('profile_id'),recordKey:text('record_key').notNull(),data:text('data').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('school_record_history').on(t.profileId,t.kind,t.recordKey)]);
export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),kind:text('kind').notNull(),createdAt:text('created_at').notNull()});
export const accountLearners=sqliteTable('account_learners',{profileId:text('profile_id').primaryKey(),accountId:text('account_id').notNull(),createdAt:text('created_at').notNull()},t=>[index('account_roster').on(t.accountId,t.createdAt)]);
export const subscriptions=sqliteTable('subscriptions',{id:text('id').primaryKey(),accountId:text('account_id').notNull(),customerId:text('customer_id').notNull(),plan:text('plan').notNull(),status:text('status').notNull(),quantity:integer('quantity').notNull(),periodEnd:integer('period_end').notNull(),cancelAtEnd:integer('cancel_at_end').notNull().default(0),checkedAt:integer('checked_at').notNull()},t=>[uniqueIndex('subscription_account').on(t.accountId)]);
export const checkoutAttempts=sqliteTable('checkout_attempts',{sessionId:text('session_id').primaryKey(),accountId:text('account_id').notNull(),quantity:integer('quantity').notNull(),createdAt:integer('created_at').notNull()},t=>[index('checkout_account').on(t.accountId,t.createdAt)]);

export const learnerPreferences=sqliteTable('learner_preferences',{profileId:text('profile_id').primaryKey(),preferences:text('preferences').notNull(),updatedAt:text('updated_at').notNull()});
export const helpRequests=sqliteTable('help_requests',{id:text('id').primaryKey(),profileId:text('profile_id').notNull(),activityId:text('activity_id').notNull(),stage:integer('stage').notNull(),question:text('question').notNull(),response:text('response'),responder:text('responder'),status:text('status').notNull(),openKey:text('open_key'),createdAt:text('created_at').notNull(),answeredAt:text('answered_at')},t=>[uniqueIndex('help_open_step').on(t.openKey),index('help_profile_status').on(t.profileId,t.status)]);

export const deviceCodes=sqliteTable('device_codes',{profileId:text('profile_id').primaryKey(),codeHash:text('code_hash').notNull(),expiresAt:integer('expires_at').notNull()},t=>[uniqueIndex('device_code_hash').on(t.codeHash)]);
export const learnerUsage=sqliteTable('learner_usage',{profileId:text('profile_id').notNull(),day:text('day').notNull(),calls:integer('calls').notNull().default(0)},t=>[uniqueIndex('learner_usage_day').on(t.profileId,t.day)]);
export const paymentEvents=sqliteTable('payment_events',{id:text('id').primaryKey(),type:text('type').notNull(),livemode:integer('livemode').notNull(),status:text('status').notNull(),lease:integer('lease').notNull().default(0),token:text('token'),error:text('error'),createdAt:text('created_at').notNull()});

export const adultSecurity=sqliteTable('adult_security',{accountId:text('account_id').primaryKey(),pinHash:text('pin_hash').notNull(),salt:text('salt').notNull(),recoveryHash:text('recovery_hash').notNull(),failedAttempts:integer('failed_attempts').notNull().default(0),blockedUntil:integer('blocked_until').notNull().default(0)});

export const launchLeads=sqliteTable('launch_leads',{pipelineConsent:text('pipeline_consent'),confirmHash:text('confirm_hash'),confirmedAt:text('confirmed_at'),emailToken:text('email_token'),id:text('id').primaryKey(),email:text('email').notNull(),audience:text('audience').notNull(),source:text('source').notNull(),consentVersion:text('consent_version').notNull(),deleteHash:text('delete_hash').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('launch_lead_email').on(t.email)]);
export const leadLimits=sqliteTable('lead_limits',{id:text('id').notNull(),day:text('day').notNull(),calls:integer('calls').notNull().default(0)},t=>[uniqueIndex('lead_limits_day').on(t.id,t.day)]);
export const leadEmails=sqliteTable('lead_emails',{id:text('id').primaryKey(),leadId:text('lead_id').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),payload:text('payload'),revision:text('revision').notNull(),providerId:text('provider_id'),error:text('error'),lease:integer('lease').notNull().default(0),lockToken:text('lock_token'),firstAttempt:integer('first_attempt').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('lead_email_owner').on(t.leadId)]);
export const standardCache=sqliteTable('standard_cache',{id:text('id').primaryKey(),snapshot:text('snapshot').notNull()});
export const familySetups=sqliteTable('family_setups',{accountId:text('account_id').notNull(),profileId:text('profile_id').notNull(),schoolYear:text('school_year').notNull(),data:text('data').notNull(),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('family_setup_owner_year').on(t.accountId,t.profileId,t.schoolYear)]);
export const familyJournal=sqliteTable('family_journal',{id:text('id').primaryKey(),accountId:text('account_id').notNull(),profileId:text('profile_id').notNull(),schoolYear:text('school_year').notNull(),schoolDate:text('school_date').notNull(),revision:integer('revision').notNull(),data:text('data').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('family_journal_date_revision').on(t.accountId,t.profileId,t.schoolDate,t.revision),index('family_journal_year').on(t.accountId,t.profileId,t.schoolYear)]);

export const launchReviews=sqliteTable('launch_reviews',{id:text('id').primaryKey(),kind:text('kind').notNull(),targetId:text('target_id').notNull(),signature:text('signature').notNull(),contentHash:text('content_hash').notNull(),notes:text('notes').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('launch_review_target').on(t.kind,t.targetId,t.signature)]);

export const pipelineContacts=sqliteTable('pipeline_contacts',{leadId:text('lead_id').primaryKey(),emailCipher:text('email_cipher').notNull(),contactId:text('contact_id'),state:text('state').notNull(),prospectStatus:text('prospect_status').notNull(),customerStatus:text('customer_status').notNull(),revision:text('revision').notNull(),error:text('error'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('pipeline_contact_updated').on(t.updatedAt)]);
export const pipelineLocks=sqliteTable('pipeline_locks',{id:text('id').primaryKey(),token:text('token').notNull(),expiresAt:integer('expires_at').notNull()});

export const learningYears=sqliteTable('learning_years',{id:text('id').primaryKey(),profileId:text('profile_id').notNull(),grade:integer('grade').notNull(),curriculumVersion:text('curriculum_version').notNull(),startDay:integer('start_day').notNull(),totalDays:integer('total_days').notNull().default(180),review:text('review'),reviewSignature:text('review_signature'),reviewedBy:text('reviewed_by'),reviewedAt:text('reviewed_at'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('learning_year_start').on(t.profileId,t.startDay)]);
export const familyConsents=sqliteTable('family_consents',{accountId:text('account_id').primaryKey(),version:text('version').notNull(),status:text('status').notNull(),squads:integer('squads').notNull().default(0),requestedAt:text('requested_at').notNull(),verifiedAt:text('verified_at'),verifiedBy:text('verified_by'),method:text('method'),reference:text('reference')});
export const learnerLifecycle=sqliteTable('learner_lifecycle',{profileId:text('profile_id').primaryKey(),expiresAt:integer('expires_at').notNull()});
export const billingNotices=sqliteTable('billing_notices',{attempts:integer('attempts').notNull().default(0),firstAttempt:integer('first_attempt').notNull().default(0),nextAttempt:integer('next_attempt').notNull().default(0),id:text('id').primaryKey(),accountId:text('account_id').notNull(),subscriptionId:text('subscription_id').notNull(),kind:text('kind').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull(),sentAt:text('sent_at'),providerId:text('provider_id'),error:text('error'),lease:integer('lease').notNull().default(0)});
